### ISSUE TITLE
Use PyPI's "Trusted Publisher" functionality to publish packages

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/operator#1021]
It'd likely be worth moving to PyPI's [Trusted Publisher](https://docs.pypi.org/trusted-publishers/) system (basically, using OIDC rather than API tokens or username/passwords). From a security point of view it's tighter because the tokens are short-lived and scoped tightly to the specific package.

**Comment by tonyandrewmeyer** [comment]
@benhoyt the first half of this requires [a short config on PyPI](https://docs.pypi.org/trusted-publishers/adding-a-publisher/), so you'll need to do that part. Feel free to pass back to me after that to adjust the workflow, or just do that yourself as well.

**Comment by benhoyt** [comment]
Done!
