### ISSUE TITLE
Add new Pebble types for log forwarding

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1026]
[`ops/pebble.py`](https://github.com/canonical/operator/blob/ecc805224badfae40b42a0a5ab2c3a3aca740d65/ops/pebble.py#L691) does not have newly-added types and typed dicts for the log forwarding work.

Specifically, we're missing the top-level `log-targets` mapping on the plan. See Pebble's [`plan.go`](https://github.com/canonical/pebble/blob/ae456c980200384e092cf664002e1b3a40d0d60e/internals/plan/plan.go#L490).

We should get these added (and make sure any other new fields in the Pebble plan are in there too).

**Comment by tonyandrewmeyer** [comment]
#1073 was a dupe of this, but we missed that at the time. I did also look over the Pebble plan at the time and nothing else seemed to be missing.

**Comment by benhoyt** [comment]
Excellent, thanks Tony. Fixed by PR https://github.com/canonical/operator/issues/1026 -- closing.
