### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#1039]
https://github.com/canonical/operator/blob/a55a07ac3bbda5bfb4228ad8d2a7904b2482ed1f/ops/version.py#L25

We wanted to have a sane default for ops but mostly rely on the git tag. However, 1.0 is now pretty old relative to current ops, so we should probably bump this.

**Comment by benhoyt** [comment]
Huh, thanks. I didn't even know that this existed. I'm not sure I love the way version.py handles it (I'd rather not be running git on import!) so maybe we can reconsider that at the same time.

**Comment by tonyandrewmeyer** [comment]
#1068 fixed this also.
