### ISSUE TITLE
See if Relation.app can be non-Optional

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1040]
It's currently typed as `Optional[Application]`, but it looks like we try very hard to set it, falling back to using `JUJU_REMOTE_APP` if we can't get it via relation data. Need to investigate whether it could ever be None, and whether we can change the type annotation to plain `Application`.

Otherwise charmers that using type checking have to add these annoying assertions:

```python
    @property
    def host(self) -> str:
        """Fetch the SMTP host from the relation."""
        assert self.relation.app
        return self.relation.data[self.relation.app].get("host")

    @property
    def port(self) -> int:
        """Fetch the SMTP port from the relation."""
        assert self.relation.app
        return int(self.relation.data[self.relation.app].get("port"))
```

**Comment by tonyandrewmeyer** [comment]
One way to have it be `None` (this was microk8s on Juju 3.1.6, with ops 2.9):

1. Add app 1 and app2 and integrate
2. Scale app 1 to multiple units
3. Scale app 1 down a unit

There's a relation-departed event for the departing unit, and [a relation-broken event for the departing unit](https://bugs.launchpad.net/juju/+bug/1979811). In that relation-broken event, `event.relation.app` is currently None.

**Comment by tonyandrewmeyer** [comment]
> One way to have it be `None` (this was microk8s on Juju 3.1.6, with ops 2.9):
> 
> 1. Add app 1 and app2 and integrate
> 2. Scale app 1 to multiple units
> 3. Scale app 1 down a unit
> 
> There's a relation-departed event for the departing unit, and [a relation-broken event for the departing unit](https://bugs.launchpad.net/juju/+bug/1979811). In that relation-broken event, `event.relation.app` is currently None.

However, I was unable to reproduce this :disappointed:.

The conclusion (see #1128) is that JUJU_REMOTE_APP is always set (and if it is not, it should be), so it does seem safe to make `app` non-optional.
