### ISSUE TITLE
Type hint of Port.port leaks implementation detail

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1045]
When the port number is passed around like so:

```python
PORTS = {"api": Port("tcp", 9093), "ha": Port("tcp", 9094)}
# ...
self.component = SomeCharmLib(port=PORTS["api"].port)
```

then the static checker complains:
```
Type "int | None" cannot be assigned to type "int"
```

This is because the type hint has `Optional`.

https://github.com/canonical/operator/blob/6428ff6b43998747d34a03490d8015102317ca26/ops/model.py#L702-L703

Now, we know given the PORTS definition there's no chance it's None, so we'd need to sprinkle `cast` everywhere.

One option is to make things more static by being more specific with the type:

```python
PORTS = {"api": TcpPort(9093), "ha": TcpPort(9094)}
```

Another option is mild duplication:

```python
api_port = 9093
ha_port = 9094
PORTS = {"api": Port("tcp", api_port), "ha": Port("tcp", ha_port)}
```
And never use Port.port.

But a class called Port with port being None seems like a wrong abstraction?

**Comment by PietroPasotti** [comment]
Yeah having dataclasses with interdependent fields (this is none only if and only if that other field is [this literal]) is never a great design.

Other approach could be having separate `TCPPort(port: int)`, `ICMPPort()` classes?

**Comment by benhoyt** [comment]
Hmm, interesting. This seems like (another?) case of type annotations getting in the way of perfectly valid code. Arguably we should have `TCPPort(port: int)` and similar subclasses, but I'm not sure if I want to add that "typing weight" at this point in the game. I'd recommend just using `cast`: `port=cast(int, PORTS["api"].port)`.

What do you think, @tonyandrewmeyer?

**Comment by tonyandrewmeyer** [comment]
> But a class called Port with port being None seems like a wrong abstraction?

I don't really like having a class called `Port` with an attribute called `port`. But the issue is that the two "port"s are different things (are different levels), one is really the port number rather than the port - but no-one says "port number".

> Arguably we should have `TCPPort(port: int)` and similar subclasses, but I'm not sure if I want to add that "typing weight" at this point in the game. I'd recommend just using `cast`: `port=cast(int, PORTS["api"].port)`.

+1, although I think I would perhaps do it like this if there are a lot of references to the ports:

```python
class TCPPort(typing.Protocol):
    protcol: typing.Literal['tcp']
    port: int

PORTS = {"api": typing.cast(TCPPort, Port("tcp", 9093)), "ha": typing.cast(TCPPort, Port("tcp", 9094))}
x: int = PORTS["api"].port
```

It seems wrong that this isn't solved by overloads, for example:

```python
class Port:
    @typing.overload
    def __init__(self, protocol: typing.Literal['tcp', 'udp'], port: int): ...

    @typing.overload
    def __init__(self, protocol: typing.Literal['icmp'], port: None): ...

    def __init__(self, protocol: typing.Literal['tcp', 'udp', 'icmp'], port: typing.Optional[int]):
        self.protocol = protocol
        self.port = port
```

The type checkers know that `Port("icmp", 25)` is wrong, so it seems to me they ought to also be able to infer that if the `Port` is created with `tcp` or `udp` then `port` will be `int`. Unfortunately, that's not the case :disappointed:. Maybe there's some way to do this that I'm not aware of?

**Comment by benhoyt** [comment]
Thanks @tonyandrewmeyer. Actually, stepping back a bit, we now have `set_ports`, which takes plain `int`s and assumes TCP. So I'd like to see this in the context of your charm to make more specific suggestions.

Perhaps `Port` isn't needed here at all?

```python
PORTS = {"api": 9093, "ha": 9094}
# ...
self.component = SomeCharmLib(port=PORTS["api"])
unit.set_ports(PORTS["api"], PORTS["ha"])
```

Or even this (why does PORTS need to be a dict -- is dynamic lookup by name necessary?):

```python
API_PORT = 9093
HAHA_PORT = 9094
# ...
self.component = SomeCharmLib(port=API_PORT)
unit.set_ports(API_PORT, HAHA_PORT)
```

**Comment by sed-i** [comment]
That would work @benhoyt.

It just seems odd that we implicitly rely on the default being tcp.
And when we need udp, we'd need to split it into separate declarations, and the declaration style would have to change to use Port.

```python
OTHER_PORT = 9999
OTHER_PROTOCOL = "udp"

unit.set_ports(
    API_PORT,
    Port(OTHER_PORT, OTHER_PROTOCOL),
    Port("icmp"),
)
```

(In python we can't really force [invalid states to be unrepresentable](https://geeklaunch.io/blog/make-invalid-states-unrepresentable/), unfortunately.)

**Comment by benhoyt** [comment]
I suspect UDP is fairly rare, but I'm not quite sure.

In any case, I don't think we'll do anything further here right now: the workarounds add too much complexity to justify what they're fixing IMO. My suggestion is to use plain port numbers if you're dealing with TCP, or `Port` with a `cast()` in those rarer cases where you're using UDP.
