### ISSUE TITLE
[secret API] secret_get should choose one of label/URI

### ISSUE THREAD

**Issue by phvalguima** [canonical/operator#1058]
Hi team,

This bug was originally filed on Juju: https://bugs.launchpad.net/juju/+bug/2042594
However, after discussing with the bug author, it makes sense to be addressed in `ops`.

When we pass both label and URI to secrets, there are corner cases, e.g. the owner of the secret, where ` secret-get`  throws an error. For example:
```
Juju v3.1.6

$ secret-get secret://0edb9324-2780-4882-8b68-131cf978ae40/cl5jcpbctt33jmcqlvp0
password: ...
username: relation-3
$ secret-set --label blabla secret://0edb9324-2780-4882-8b68-131cf978ae40/cl5jcpbctt33jmcqlvp0
$ secret-get secret://0edb9324-2780-4882-8b68-131cf978ae40/cl5jcpbctt33jmcqlvp0
password: ...
username: relation-3
$ secret-get --label blabla
password: ...
username: relation-3
$ secret-get secret://0edb9324-2780-4882-8b68-131cf978ae40/cl5jcpbctt33jmcqlvp0 --label blabla
ERROR either URI or label should be used for getting an owned secret but not both
```

I think the best would be to agree with Juju what should be used: label or ID, and then select just one before passing to `secret-get`.

**Comment by tonyandrewmeyer** [comment]
See discussion in #1060 - we feel this should be addressed in Juju. I'll make a note in the Juju issue.
