### ISSUE TITLE
[testing] ValueError: Secret owner cannot use refresh=True

### ISSUE THREAD

**Issue by juditnovak** [canonical/operator#1062]
This error occurs only on unittests, relating to `Harness`.

The problem is that -- this false alarm prevents us from being able to realitically test charms code... We need to apply workarounds either on the tests (that's well elaborate), or even worse, on the code... Which is highly incorrect -- yet keeps us secure in case it may be more than a `Harness` bug (at any point)...)

All in all: reliable unittesting is _essential_ to be able to deliver reliable code... If you could please address it with "non-negligable" priority :-)

Thank you.

The issue have been discussed in https://chat.charmhub.io/charmhub/pl/aekfocgk8tbtfcsda7311uurxe

**Comment by benhoyt** [comment]
Per discussion at the engineering sprint, Juju is planning to change the behaviour of secrets so secret owners can track secrets the same way as observers, and also use refresh=True. So this problem will go away.

However, we need to change the behaviour in Harness too. I think we basically need to remove the `if secret.owner_name in [self.app_name, self.unit_name]` block in `_TestingModelBackend.secret_get` and have that go through the same code path for owners and observers, and have it solely based on what's passed in.

Per discussion with John M, we'll plan to move ops forward to the new/upcoming Juju behaviour (even before it's shipped). Charms can always use peek=True (without refresh) to get the current behaviour on both old and new Juju. The Juju team's plan is to ship this change in Juju 3.1.7 and Juju 3.3.1 in December.
