### ISSUE TITLE
Misleading docstring for `get_filesystem_root`

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1063]
The docstring for [`Harness.get_filesystem_root`](https://ops.readthedocs.io/en/latest/#ops.testing.Harness.get_filesystem_root) suggests that:
1. Using plain `open` in charm code operates on workload containers;
2. Passing "charm" as an arg to `get_filesystem_root` would give the charm container.

However, both are wrong:
1. A plain `open` would operate on the charm container;
2. Cannot pass "charm" as an arg: `return self._backend._pebble_clients[container_name]._root KeyError: 'charm'`

https://github.com/canonical/operator/blob/848fb52e8d953e20a8e37ceb4f13fe791cd3fa7b/ops/testing.py#L1638-L1650

**Comment by benhoyt** [comment]
Thanks. Does this change address your concerns? https://github.com/canonical/operator/pull/1065
