### ISSUE TITLE
Add mediator for interacting with charm container

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1064]
Sometimes, charm code operates on the charm container. For example:
- https://github.com/canonical/prometheus-k8s-operator/blob/b4d67ad7cc48d7c6d39246a6e34e23c2fa3547b1/src/charm.py#L436
- https://github.com/canonical/cos-proxy-operator/blob/de6fab3c97482bea50124ee683fea4facebf4400/src/charm.py#L314
- https://github.com/canonical/cos-configuration-k8s-operator/blob/cc1ba978238a2d1d9238191b96fd0af7f5f464fa/src/charm.py#L272

As a result, we have to add (somewhat brittle) patches in test code, and when we forget to patch, then unit tests attempt to do sketchy things to the host's `/etc`, `/usr` and other paths.

It would be handy if there was a mediator `ops` offered for interacting with the charm container to avoid such situations as much as possible.

Related: #1063.

**Comment by benhoyt** [comment]
I can definitely see how the misleading docstring on `Harness.get_filesystem_root` caused confusion (per #1063), however, I don't think this is a good idea. Charm code is just normal Python code and the charm container is local, so like with VM charms you can do anything you want (and have to patch/mock as required). A mediator would just be an unnecessary layer of indirection, and I think most charms would just skip the mediator and interact directly in any case, so the problem wouldn't go away.

@tonyandrewmeyer what are your thoughts?

**Comment by tonyandrewmeyer** [comment]
Agreed. Forgetting to patch the fs seems no different than any other Python code testing (and `/etc/`, `/usr/` etc ought to be protected anyway, so it'll be failing tests rather than mangling someone's system).

@sed-i what makes the patches "brittle"? Do you have an example (perhaps for one of those charms you linked)?

**Comment by benhoyt** [comment]
Given the above, I don't think we're going to do this. @sed-i feel free to still post links/examples of said "brittle" patches.
