### ISSUE TITLE
collect-status should default to Active

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#1069]
Issue:
the idea seems to be that we should write collect-status handlers like so:
```
if something_wrong:
    event.set_status(BlockedStatus("foo"))
if something_also_wrong:
    event.set_status(BlockedStatus("bar"))
if something_somewhat_wrong:
    event.set_status(WaitingStatus("baz"))
```

But do we also need to manage ourselves the negative, the 'everything looks allright' path?

Logically, ActiveStatus takes the lowest priority, so I can achieve what I want by doing:
```
if something_wrong:
    event.set_status(BlockedStatus("foo"))
if something_also_wrong:
    event.set_status(BlockedStatus("bar"))
if something_somewhat_wrong:
    event.set_status(WaitingStatus("baz"))

event.set_status(ActiveStatus(""))
```

Result: if none of the other statuses is applicable, you'll see `active`.

However I feel that this is always the desirable behaviour, so why doesn't collect-status by default fall back to an `active` status if `set_status` is never called?

**Comment by benhoyt** [comment]
This is an interesting idea. Off the top of my head, the main reason why not is "explicit is better than implicit" (and gives you control over the status message -- though for Active that's often empty string anyway).

Would this change be backwards-compatible? I guess not strictly speaking, as with the change it would then overwrite any previously-set status with Active. But it seems unlikely if people are using collect-status they'd *not* want that.

In terms of implementation, we'd need to be able to distinguish between "not subscribed to the collect-status event at all" and "no statuses added" -- presumably not hard, though not quite sure how to do that at a quick glance.

**Comment by PietroPasotti** [comment]
That'd be a matter of going through the `framework._observers` mapping IIRC

**Comment by benhoyt** [comment]
We've discussed this and believe it's better to keep it explicit. You can `event.add_status(ops.ActiveStatus())` as the first line to make it clearer if you want. However, we think doing it implicitly is less clear, and also kind of confusing to think about when you have multiple collect-status observers.
