### ISSUE TITLE
Combine Pebble layers in testing get_plan; merge "checks" and "log-targets"

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1112]
As I discovered when reviewing https://github.com/canonical/operator/pull/1111 ([comment](https://github.com/canonical/operator/pull/1111#discussion_r1463868110)), we don't combine layers properly in the `_TestingPebbleClient.get_plan` result.

We already kind of have the code to combine a layer ([in `_TestingPebbleClient.add_layer`](https://github.com/canonical/operator/blob/dc47640f8ea915049d9e20a1fe4ea189c96ae8d1/ops/testing.py#L2912-L2929)), we just need to use it for `get_plan` as well.

Additionally, we need to combine/merge health checks and log targets. We have `pebble.Service._merge` (used by `add_layer` above), but we'll need similar `_merge` methods on `pebble.Check` and `pebble.LogTarget` and update appropriately.

**Comment by amandahla** [comment]
Hi, I've come across this issue while working on this PR:
https://github.com/canonical/synapse-operator/pull/404

Is there another way of creating a unit test for check changes?
