### ISSUE TITLE
Model JUJU_CHARM_*_PROXY environment variables in ops

### ISSUE THREAD

**Issue by yanksyoon** [canonical/operator#1113]
Reading environment variables `JUJU_CHARM_HTTP_PROXY`, `JUJU_CHARM_HTTPS_PROXY`, `JUJU_CHARM_NO_PROXY` is a common pattern in a few of the charms ([example implementation](https://github.com/canonical/tmate-ssh-server-operator/blob/main/src/state.py#L51) in tmate-ssh-server operator charm), which can benefit charmers when included in the ops library.
[link to original PR discussion](https://github.com/canonical/tmate-ssh-server-operator/pull/10/files#r1463373669)

[Documentation for proxy settings](https://ubuntu.com/kubernetes/docs/proxies)

**Comment by tonyandrewmeyer** [comment]
```
tameyer@tam-canoncial-1:~/code/charm-analysis/.cache$ rg -e 'JUJU_CHARM_.+_PROXY' --count
charm-apt-mirror/src/charm.py:2
charm-apt-mirror/tests/unit/test_charm.py:2
wordpress-k8s-operator/src/state.py:3
wordpress-k8s-operator/tests/unit/test_charm.py:6
charm-simple-streams/src/charm.py:6
charm-simple-streams/tests/unit/test_charm.py:8
indico-operator/src/state.py:3
indico-operator/tests/unit/test_state.py:1
indico-operator/tests/unit/test_core.py:1
indico-operator/tests/unit/conftest.py:3
discourse-k8s-operator/tests/unit/test_charm.py:3
discourse-k8s-operator/src/charm.py:3
flask-k8s-operator/src/charm_state.py:3
flask-k8s-operator/tests/unit/test_flask_app.py:5
alertmanager-k8s-operator/src/alertmanager.py:3
synapse-operator/src/charm_state.py:3
synapse-operator/tests/unit/test_synapse_workload.py:5
grafana-k8s-operator/src/charm.py:3
jenkins-k8s-operator/src/state.py:3
jenkins-k8s-operator/tests/unit/test_state.py:4
cos-configuration-k8s-operator/src/charm.py:3
```

**Comment by benhoyt** [comment]
We talked to the Juju team about this, and there's messiness with these environment variables (the `JUJU_` prefixed ones and the non-`JUJU_`-prefixed ones, for example) and they're not convinced they're the way forward in any case, so we don't want to lock ourselves into the current messiness. They want to step back and have a discussion about this to redesign (in Madrid).

In the meantime you can work around by just accessing the environment variables directly in your charm.

**Comment by benhoyt** [comment]
Some more context in this [Juju bug report](https://bugs.launchpad.net/juju/+bug/2054839) - for example, Rob's comment with the list of the 12 env vars.

**Comment by yanksyoon** [comment]
Thank you for the context - hope to have a good discussion on Madrid!
