### ISSUE TITLE
Adjust Python logging level based on Juju logging-config value

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/operator#1126]
In Juju, logs from charms get a `unit.name/ordinal` prefix and can be filtered out entirely by (e.g.):

```
juju model-config logging-config="unit.mysql/0=INFO"
```

Or filtered from the `debug-log` output with `--include` or `--exclude`.

However, within the Python code, even if the log level is set high (e.g. to error/critical) the Python logging code can't optimise the lower level log emits out because everything is sent through to Juju.

It would be nice to be able to have something like:

```
logger.debug("This is really noisy or expensive to str the arg: %s", x)
```

And have that only reach Juju if the logging config meant that it would be stored.

Juju supports period-separated hierarchical logging identifiers, in the same fashion as Python, so this could actually be even more fine-grained, like:

```
juju model-config logging-config="unit.mysql/0.sublogger=DEBUG"
```

And ops could then apply that appropriately in `ops.log`.

Note that this has a prerequisite on a Juju enhancement (to be opened) to add, e.g. `JUJU_CHARM_LOG_LEVEL` as an environment variable (exact format to be figured out, depending on whether this can be a simple `info` or a more complex structure describing different log levels at different hierarchy levels.

**Comment by benhoyt** [comment]
Discussed: this is an interesting idea, but we don't feel the need is strong enough to warrant a whole new feature at this point. Can always re-open if there's concrete evidence from charmers they need/want something like this.
