### ISSUE TITLE
Harness should always provide the remote app name in relation-broken

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/operator#1128]
Although it seems like sometimes JUJU_REMOTE_APP is not set in relation-broken, the [conclusion in the Juju investigation](https://bugs.launchpad.net/juju/+bug/1960934) was that this should not happen, and it couldn't be reproduced.

We should remove [the special-casing in Harness that acts as if this *is* the case](https://github.com/search?q=repo%3Acanonical%2Foperator%20https%3A%2F%2Fbugs.launchpad.net%2Fjuju%2F%2Bbug%2F1960934&type=code).

**Comment by jameinel** [comment]
It could easily be that it reproduces with something like Juju 2.8, but I
don't think we need to keep compatibility with 2.8 anymore.
