### ISSUE TITLE
Unable to add additional arguments to event handlers

### ISSUE THREAD

**Issue by jdkandersson** [canonical/operator#1129]
Consider the following simple charm:

```python
#!/usr/bin/env python3
# Copyright 2021 Ben
# See LICENSE file for licensing details.

"""Charm the service."""

import logging

from ops.charm import CharmBase
from ops.main import main
from ops.model import ActiveStatus, ModelError
from ops.pebble import ServiceStatus

logger = logging.getLogger(__name__)


def inject_charm_state(
    func: Callable[[CharmBase, EventBase], Any]
) -> Callable[..., Callable[[CharmBase, EventBase], Any]]:
    """Create a decorator that injects the charm_state into the charm instance, and removes it after."""

    @functools.wraps(func)
    def wrapper(charm: CharmBase, event: EventBase) -> Any:
        charm_state = CharmState.from_charm(charm)
    return func(charm, event, charm_state)

    return wrapper



class SnappassTestCharm(CharmBase):
    """Charm the service."""

    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(
            self.on.snappass_pebble_ready, self._on_snappass_pebble_ready
        )
        self.framework.observe(self.on.redis_pebble_ready, self._on_redis_pebble_ready)

    def _on_snappass_pebble_ready(self, event):
        logger.info("_on_snappass_pebble_ready")
        container = self.unit.containers["redis"]

        if self._is_running(container, "redis"):
            logger.info("redis already started")
            self._start_snappass()

    def _start_snappass(self):
        logger.info("_start_snappass")
        container = self.unit.containers["snappass"]

        if self._is_running(container, "snappass"):
            logger.info("snappass already started")
            return

        snappass_layer = {
            "summary": "snappass layer",
            "description": "snappass layer",
            "services": {
                "snappass": {
                    "override": "replace",
                    "summary": "snappass service",
                    "command": "snappass",
                    "startup": "enabled",
                }
            },
        }

        container.add_layer("snappass", snappass_layer, combine=True)
        container.autostart()
        self.unit.status = ActiveStatus("snappass started")

    @inject_charm_state
    def _on_redis_pebble_ready(self, event, charm_state):
        charm_state = CharmState.from_charm(self)

    logger.info("_on_redis_pebble_ready")
        container = event.workload

        if self._is_running(container, "redis"):
            logger.info("redis already started")
            return

        redis_layer = {
            "summary": "redis layer",
            "description": "redis layer",
            "services": {
                "redis": {
                    "override": "replace",
                    "summary": "redis service",
                    "command": "redis-server",
                    "startup": "enabled",
                }
            },
        }

        container.add_layer("redis", redis_layer, combine=True)
        container.autostart()
        self.unit.status = ActiveStatus("redis started")
        # Prod snappass to start
        self._start_snappass()

    def _is_running(self, container, service):
        """Helper method to determine if a given service is running
        in a given container"""
        try:
            service = container.get_service(service)
        except ModelError:
            return False
        return service.current == ServiceStatus.ACTIVE


if __name__ == "__main__":
    main(SnappassTestCharm)
```

The `inject_charm_state` adds an additional `charm_state` argument to the event handler. `ops` currently will throw a runtime error (apologies don't have the error on hand) saying that the function is not a valid observer. As discussed, this should probably be done in a linting type of tool rather than as a runtime check. It would also be great if any linting tool will consider the modifications made by the decorator.

Also as discussed, I believe the following code in `ops` does this check: https://github.com/canonical/operator/blob/2f304d3af048edd758bee8b4b4d59f474b33a286/ops/framework.py#L811

**Comment by tonyandrewmeyer** [comment]
Interestingly, this does work:

```python
def dec(func):
    def wrapped(a, b):
        return func(a, b, 1)
    return wrapped

import inspect

@dec
def f(a, b, c):
    pass

print(inspect.signature(f))  # prints (a, b)
```

As does this:

```python
import inspect

class X:
    def __init__(self):
        self.observe(None, self.f)

    @dec
    def f(self, x, y):
        pass

    def observe(self, a, func):
        print(inspect.signature(func))  # prints (b)

X()
```

**Comment by tonyandrewmeyer** [comment]
But this doesn't:

```python

**Comment by tonyandrewmeyer** [comment]
Options:

1. Completely remove this check, trusting other tools to catch the issue (ruff/flake8/pylint, pyright/mypy). (Do they?)
2. Check for the `__wrapped__` attribute that `functools.update_wrapper` adds to get to the function that will actually be called.

Workarounds:
1. Don't use `functools.wrap` (or use it more minimally)
2. Provide a default argument for the state knowing (and asserting) that it will never be used
3. Just call the function inside the handlers

**Comment by benhoyt** [comment]
Ah yes, it has to do with the wrapping that `functool.wraps` is doing, and the unwrapping `inspect.signature` is doing. I notice that it's trivial to fix this by changing the [`inspect.signature`](https://docs.python.org/3/library/inspect.html#inspect.signature) call [here](https://github.com/canonical/operator/blob/2f304d3af048edd758bee8b4b4d59f474b33a286/ops/framework.py#L799) to:

```python
sig = inspect.signature(observer, follow_wrapped=False)
```

This test exercises it (will need cleaning up):

```python
import functools
def inject_charm_state(func):
    @functools.wraps(func)
    def wrapper(charm, event):
        charm_state = "CHARM_STATE"
        return func(charm, event, charm_state)

    return wrapper

class TestObserver(unittest.TestCase):
    def test_observer_decorator(self):
        class MyCharm(ops.CharmBase):
            @inject_charm_state
            def _on_foo(self, event, charm_state):
                print("FOO", charm_state)

        framework = self.create_framework()
        charm = MyCharm(framework)
        framework.observe(charm.on.install, charm._on_foo)
        charm.on.install.emit()
```

For reference, the original error was:

```
TypeError: MyCharm._on_foo has extra required parameter
```

**Comment by benhoyt** [comment]
While we're fixing this issue, we should also test why a lambda observer doesn't work, and see if that's easily fixable -- I know that's been a pain point for some non-typical use cases.

**Comment by jdkandersson** [comment]
For the default, I understand it would work, the issue is that it is a workaround and would pollute the type hint for the argument (now it has to, for example, be nullable and there needs to be a check that it isn't `None` and it isn't clear what the charm should do in that case and so on)

**Comment by tonyandrewmeyer** [comment]
> While we're fixing this issue, we should also test why a lambda observer doesn't work, and see if that's easily fixable -- I know that's been a pain point for some non-typical use cases.

I don't think it is. It's straightforward to adjust the check that the observer is a method (and check that it's a callable instead), but it then fails because the observer isn't an `Object`. Having the handlers be (methods on) an `Object` is core to how the framework handles emitting (and deferring) so that doesn't seem like something we can easily change.

We could probably come up with a solution for this, but I think it should be in a separate ticket with the use-cases outlined.

**Comment by benhoyt** [comment]
Good point @tonyandrewmeyer -- let's leave the lambda case for now (no need to open a separate ticket -- we can always open one if it becomes more of an issue).
