### ISSUE TITLE
[doc] What happens when timeout period in `Container.exec()` elapses?

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1131]
ops.model and ops.pebble don't specify what happens when timeout is elapsed.
Context: https://github.com/canonical/alertmanager-k8s-operator/pull/218

https://github.com/canonical/operator/blob/1836df5affb42b3183125b1904c794090aa1862b/ops/model.py#L2711-L2712

https://github.com/canonical/operator/blob/1836df5affb42b3183125b1904c794090aa1862b/ops/pebble.py#L2526-L2528

**Comment by tonyandrewmeyer** [comment]
See also #826

**Comment by sed-i** [comment]
Also: #867

**Comment by sed-i** [comment]
Potentially related: `container.exec` also leaks `http.client.RemoteDisconnected`, as can be seen here: https://github.com/canonical/cos-lite-bundle/issues/103

**Comment by IronCore864** [comment]
We decided against putting Raises TimeoutError in these methods, because they really need to go in all of them, so there's the note in the class docstring instead.

See discussion [here](https://github.com/canonical/operator/pull/1155#discussion_r1538423137).

Close now.
