### ISSUE TITLE
Update get_notices "select=all" to "users=all"

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1132]
Per discussion with @olivercalder and Gustavo, we're going to change the `select=all` parameter in Pebble (and snapd) to `users=all`, and we should make the same change in [`pebble.Client.get_notices`](https://ops.readthedocs.io/en/latest/#ops.pebble.Client.get_notices) (as well as `Container.get_notices`). This is a breaking change, but it's almost certain that no one is using this yet (if anything they'll fetch the notice via `event.notice` for a custom event), so I think we should just go ahead and make the breaking change before it's too late, rather than try to alias everything and try to have fallbacks for different Pebble versions, and so on.

For reference, the spec for user-specific notices is [OP042](https://docs.google.com/document/d/1tQwUxz-rV-NjH-UodDbSDhGcMJGfD3OSoTnBLI9aoGU/edit).

**Comment by olivercalder** [comment]
The relevant PR for pebble is: https://github.com/canonical/pebble/pull/368
