### ISSUE TITLE
[BUG][regression] Error introduced between ops versions 2.9.0 and 2.10.0

### ISSUE THREAD

**Issue by juditnovak** [canonical/operator#1135]
Since moving to v2.10.0 of the `ops` code we're observing the following error.

```
    self._secret_meta = self.charm.model.get_secret(
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/model.py", line 281, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/model.py", line 3375, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/ops/model.py", line 3021, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR only unit leaders can update an application owned secret label
```
Since secret labels are internal to the charm, they shouldn't even know about each other's labels -- but that may just be a misleading error message.

The error is raised by `secret-get`... Perhaps when aiming to attach the label for the first time...?

NOTE: No code changes on our side, the issue appeared on upgrading `ops` versions.

**Comment by tonyandrewmeyer** [comment]
I get the same behaviour with 2.9 and 2.10. I'm using this minimal charm:

```python
import json

import ops

class TestingSecretsCharm(ops.CharmBase):
    """Charm the application."""

    def __init__(self, framework: ops.Framework):
        super().__init__(framework)
        framework.observe(self.on.install, self._on_install)
        framework.observe(self.on.get_app_secret_action, self._on_get_app_secret_action)

    def _on_install(self, event: ops.InstallEvent):
        if not self.unit.is_leader():
            return
        content = {"username": "admin", "password": "admin"}
        app_secret = self.app.add_secret(content)
        if not self.peers:
            event.defer()
            return
        self.set_peer_data("app-secret-id", app_secret.id)

    def _on_get_app_secret_action(self, event: ops.ActionEvent):
        id = self.get_peer_data("app-secret-id")
        kwargs = {}
        if event.params.get("id"):
            kwargs["id"] = id
        if event.params.get("label"):
            kwargs["label"] = "my-app-secret"
        event.set_results({"password": self.model.get_secret(**kwargs).get_content()})

    @property
    def peers(self):
        return self.model.get_relation("secret-peers")

    def set_peer_data(self, key: str, data: typing.Any):
        self.peers.data[self.app][key] = json.dumps(data)

    def get_peer_data(self, key: str) -> typing.Any:
        data = self.peers.data[self.app].get(key, "")
        return json.loads(data) if data else {}

if __name__ == "__main__":  # pragma: nocover
    ops.main(TestingSecretsCharm)  # type: ignore
```

And then:

1. Pack, deploy, add-unit.
2. `juju run testing-secrets/0 get-app-secret id=true label=false`
3. `juju run testing-secrets/1 get-app-secret id=true label=true`

This fails as described with the "only unit leaders can update an application owned secret label", both with ops 2.9 and with ops 2.10.

You said there were no code changes on your side - any chance there was a Juju version change as well as an ops one?

Do you have a unit test or other small repro that I could run with 2.9 and 2.10 to see different behaviour?

Secret labels are internal to the charm, but this is two units within the charm, not a remote unit.

**Comment by tonyandrewmeyer** [comment]
I can reproduce this with the Juju hooks, no ops:

```shell
root@testing-secrets-1:/var/lib/juju/agents/unit-testing-secrets-1/charm# ../../../tools/unit-testing-secrets-1/secret-get cnf90f7mp25c76423tkg
password: admin
username: admin
root@testing-secrets-1:/var/lib/juju/agents/unit-testing-secrets-1/charm# ../../../tools/unit-testing-secrets-1/secret-get cnf90f7mp25c76423tkg --label=my-app-secret
ERROR only unit leaders can update an application owned secret label
```

I [asked in #juju](https://matrix.to/#/!xzmWHtGpPfVCXKivIh:ubuntu.com/$oW7KqhY21GN5VQEwDu1UWgXARFySbJVdtxfOHM7oDCQ?via=ubuntu.com&via=matrix.org&via=fsfe.org) and this is meant to be possible (despite the error message that seems clear that it should not?) so I'll check against Juju 3.1 and 3.3 and open a Juju bug.

**Comment by tonyandrewmeyer** [comment]
Opened [a bug in Juju](https://bugs.launchpad.net/juju/+bug/2055244). Leaving this open for now to hear back about if there is some way to get different ops behaviour in 2.9 vs 2.10.

**Comment by tonyandrewmeyer** [comment]
The Juju bug has been fixed. I'm going to assume there was no ops regression here.
