### ISSUE TITLE
Versioning for the Operator Framework?

### ISSUE THREAD

**Issue by relaxdiego** [canonical/operator#116]
Firstly, great job on this framework!

Currently, the readme recommends adding the framework as a submodule, using the master branch, to a charm's directory structure. Is there already an existing plan to implement versioning (preferably SemVer 2.x-compliant) for the framework? The reason I ask is because using just `master` is a bit worrisome since it introduces some variability when developing charms and it will be hard to determine whether it's a good time to upgrade the framework or not.

**Comment by dshcherb** [comment]
We will have tags and/or branches in due course. There is no expectation that people will always have to use the latest master commit.

**Comment by relaxdiego** [comment]
Thanks again for your work on this @dshcherb and team! I'm very excited to use this framework.

Regarding the versioning, it's not so much whether we are expected to always use the latest master commit but rather the need to ensure that charm developers are able to update their copy of the framework to the latest patch release without fear of pulling in unwanted, or worse, breaking changes. I think adopting SemVer 2.x early on, especially now that there's a huge push to refactor our existing charms and write all future charms on top of this framework, will do a lot to help ensure a good charm developer experience.

**Comment by relaxdiego** [comment]
Also, I hope you reconsider re-opening this issue since versioning is not just a matter of adding a version file in the project. It also involves designing a process around it that the team can agree on.

**Comment by jameinel** [comment]
I do think the intent is to follow semantic versioning, with the main caveat that the library is still considered to be 0.x
https://semver.org/#spec-item-4

I don't know whether we will do strict semver, though most of it is common sense. (don't reuse numbers, bump PATCH when doing bug fixes, MINOR when doing backward compatible updates, MAJOR when doing incompatible changes.)

I do think it is too early to commit to an official structure as a 1.0, as we are still doing some major wording changes, and while most basic functionality is in place, there are still some changes in Juju that we'll want to leverage (saved state, dispatch functionality) that is waiting for at least Juju 2.8, and I wouldn't want to go to 1.0 until that is finally worked through.

**Comment by relaxdiego** [comment]
Using `0.y.z` initially is perfect actually as it gives you the ability to signal whether it's safe to upgrade or not without fear of breaking changes (via incrementing `z` for bug fix changes only) without tying the project too soon to a rigid MAJOR versioning scheme the way 1.y.z and above will impose on it.

I hope the versioning happens soon though if we are to start using this framework for all of our team's charming initiatives.
