### ISSUE TITLE
`Harness` does not support creation of user secrets

### ISSUE THREAD

**Issue by DnPlas** [canonical/operator#1175]
As of today, there is no support for creating and handling "user" secrets that can emulate the behaviour of secrets added via the CLI with `juju add-secret`. The expectation would be to extend `Harness` to allow charmers to add user secrets, grant access, update the secret contents, and remove the secret. An initial discussion about adding support for this has started [here](https://github.com/canonical/operator/issues/1166#issuecomment-2027412308), but I thought adding an issue for this enhancement in particular would be better to increase visibility.

For the record, there is an implementation to support "charm" secrets in [`add_model_secret`](https://github.com/canonical/operator/blob/main/ops/testing.py#L1512).

**Comment by tonyandrewmeyer** [comment]
Note that this is currently being done in #1166.

**Comment by benhoyt** [comment]
Thanks for the report, @DnPlas. As Tony mentioned, we're discussing this further over at #1166, so even though strictly speaking it's not a dupe, I'll close this one so we can keep the discussion in one place.
