### ISSUE TITLE
Refactor Ops tests to use pytest instead of unittest

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1177]
We've been moving to pytest for Harness and other examples in our docstrings and docs. However, the Ops tests themselves are still all written in unittest with ugly `self.assertEqual(...)` calls and the like. Let's go all in on pytest here too.

This is going to be a huge diff -- maybe we can do 1 file per PR to split it up?

Let's look to see if there are existing tools that do this. If not, we may want to consider writing our own AST-based hack that can do most of it.

**Comment by tonyandrewmeyer** [comment]
Should this be closed now? There was potential further work, if I recall correctly, but the main change is complete, right?

**Comment by benhoyt** [comment]
Yes, thanks!
