### ISSUE TITLE
Getting the application version

### ISSUE THREAD

**Issue by BalabaDmitri** [canonical/operator#1180]
You have an implementation for setting the version of "application" https://github.com/canonical/operator/blob/b7e5ba33e7a18022b56535a4d3d84363e1091f5b/ops/model.py#L3265
and for example it is possible to set the status and get it from "application", but there is no way to get the current version of "application". Tell me, is there a way to get the "application" version?

**Comment by tonyandrewmeyer** [comment]
Hi @BalabaDmitri  - the expectation is that the charm knows how to get the workload/application version and provides that to Juju, so wouldn't ever need to ask Juju for it. This is unlike status, where Juju sometimes sets the status.

Can you explain a bit about your use case for this?

**Comment by benhoyt** [comment]
In addition to what Tony said, there is no Juju hook tool `application-version-get` (only set).

**Comment by BalabaDmitri** [comment]
@tonyandrewmeyer I want to check if I am using a database with a different version. I already have a leader and I will connect a second one from another cluster with a different version of the database, I need to block the application since there are different versions of the database.

**Comment by BalabaDmitri** [comment]
@benhoyt I understand. I have a question about how I can get application version information. I understand correctly that at the moment there is no such possibility. or is there some other possibility

**Comment by tonyandrewmeyer** [comment]
> @tonyandrewmeyer I want to check if I am using a database with a different version. I already have a leader and I will connect a second one from another cluster with a different version of the database, I need to block the application since there are different versions of the database.

This sounds like peer data would be the best choice. Each unit can populate the peer relation databag with the version of the database locally, and then whichever units need to make decisions about what to do if they don't match can just look at what's in the databags.

**Comment by BalabaDmitri** [comment]
> > @tonyandrewmeyer I want to check if I am using a database with a different version. I already have a leader and I will connect a second one from another cluster with a different version of the database, I need to block the application since there are different versions of the database.
> 
> This sounds like peer data would be the best choice. Each unit can populate the peer relation databag with the version of the database locally, and then whichever units need to make decisions about what to do if they don't match can just look at what's in the databags.

Thank you, it helped me
