### ISSUE TITLE
Add support for writing to juju logs

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#119]
Please add support for writing to juju logs. Obviously this can be done manually but it would be much cleaner if this was provided by the framework. Something like:

self.log(msg)
self.log(msg, "DEBUG")

**Comment by jameinel** [comment]
I believe Dmitrii was looking into writing the python standard logger into
juju-log.

John
=:->

**Comment by dshcherb** [comment]
Here is a PR that introduces the support for juju-log via standard library logging mechanisms:
https://github.com/canonical/operator/pull/133

Hopefully we can come up to something at the Juju level as well: https://bugs.launchpad.net/juju/+bug/1861987

**Comment by dshcherb** [comment]
This can now be used via default logger without referring to juju-log in any way:

```
import logging

logger = logging.getLogger(__name__)

logger.info('my message')
```
