### ISSUE TITLE
`RelationDataContent` should be update-able via keyword arguments only

### ISSUE THREAD

**Issue by addyess** [canonical/operator#1225]
https://github.com/canonical/operator/pull/1183 created a regression where `RelationDataContent` could not be updated via the `.update(...)` method if only keyword arguments were passed to it. 

[this module](https://github.com/charmed-kubernetes/interface-aws-integration/blob/main/ops/ops/interface_aws/requires.py#L188-L191) previously could execute
```python
some_dict = {"foo": "bar"}
self.relation.data[self.charm.model.unit].update(**some_dict)
```

but now there's an exception because i don't have an `other` argument
```
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/venv/ops/interface_aws/requires.py", line 133, in _joined
    self._request({"instance-id": self.instance_id, "region": self.region})
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/venv/ops/interface_aws/requires.py", line 190, in _request
    self._to_publish.update(**kwds)
TypeError: RelationDataContent.update() missing 1 required positional argument: 'other'
```

This is acceptable in normal python and should be restored as shown in this example where both styles are acceptable in an `update`

```python
Python 3.12.3 (main, May 22 2024, 13:41:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = {}
>>> a.update(**{"a": 1})
>>> a
{'a': 1}
>>> b = {"b": 2}
>>> a.update(b)
>>> a
{'a': 1, 'b': 2}
>>> c, d = {"c": 3}, {"d": 4}
>>> a.update(c, **d)
>>> a
{'a': 1, 'b': 2, 'c': 3, 'd': 4}
```

**Comment by addyess** [comment]
Addressed by https://github.com/canonical/operator/pull/1226

**Comment by addyess** [comment]
@tonyandrewmeyer thanks for closing.  When might i expect an `ops` library release to provide this feature?

**Comment by tonyandrewmeyer** [comment]
> @tonyandrewmeyer thanks for closing. When might i expect an `ops` library release to provide this feature?

We usually do an ops release at the end of each month. We haven't talked about it yet (will do in our daily today) but I'd expect that we'd do a release in the first half of this week.

**Comment by dimaqq** [comment]
@addyess done, enjoy!
