### ISSUE TITLE
Introduce base classes for interface into the framework

### ISSUE THREAD

**Issue by majduk** [canonical/operator#123]
Currently the InterfaceProvides and InterfaceRequires classes inherit after ops.framework.Object class. I would like to propose creating interim base class serving as a base for interface and including what effectively is a boilerplate code:
- relation name setup
- relations and fields properties
- is joined status
- is ready status
- goal state

**Comment by stub42** [comment]
I'm interested in base classes to guide people towards preferred patterns. Do we create a class to handle a single relation, or a class for the endpoint that handles all relations using a particular relation_name? If both are patterns we want to promote, how should we name them?

**Comment by petevg** [comment]
Since we've moved away from integrating the requires and provides concepts into the framework, I believe that this issue can be closed.

I agree that we should be providing guidance on best practices. I believe that current work on libraries represents our best efforts to this end.
