### ISSUE TITLE
Add pebble log forwarding support check to `jujuversion`

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1230]
Following up on #1074, should we add something to `ops/jujuversion.py`?
E.g. `supports_pebble_log_forwarding`.
I realize it's a pebble feature, but since the two are in lockstep then perhaps it makes sense?

**Comment by benhoyt** [comment]
@sed-i Do you think this will be needed in charms, that is, support for both older versions of Juju (without log forwarding) and newer ones with it?

**Comment by sed-i** [comment]
I've been asked to for postgresql-k8s.

Afaiu, in air-gapped, the plan is to use juju 3.4.1+ (and not download promtail), but otherwise to not force people to upgrade. Having the ability to use either, helps charm authors by not requiring them to open a new track.

It seems like this check will be repeated in every charm that logs to loki and that needs to work with juju < 3.4.1 and be deployed airgapped. Not sure about the number of charms in that intersection.

**Comment by benhoyt** [comment]
I'm okay with adding a `JujuVersion.support_pebble_log_forwarding` property. However, there's "log forwarding with Loki" (Pebble v1.4.0) and log labels (Pebble v1.6.0) -- without log labels, log forwarding isn't nearly as useful. Juju 3.3 includes Pebble v1.4.x (basic log forwarding), and Juju 3.4 includes Pebble v1.7.x (log labels as well). Do you think `support_pebble_log_forwarding` should be from Juju 3.4 onwards?

**Comment by sed-i** [comment]
Thanks @benhoyt.
Yes, I think 3.4 (3.4.1?) is the right way to go.

From a first glance at [github search results](https://github.com/search?q=org%3Acanonical+LogProxyConsumer+lang%3Apython+AND+NOT+path%3Aloki_push_api.py&type=code), this might get used around.
