### ISSUE TITLE
Documentation is missing for StoredState behavior

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1270]
Documentation is missing for StoredState behavior, in particular across upgrades.
In charm code we import StoredState so seems reasonable to have it documented in the docstring there.

- For vm charms, there are no docs. What happens to stored state across upgrades? Does `use_juju_for_storage` have an impact?
- For k8s charms, info is sparse and fragmented, so need to parse the code every time just to be sure.

https://github.com/canonical/operator/blob/89ea7f4d56173ea314d59a271e4304b18cd129ed/ops/framework.py#L1037-L1038

https://github.com/canonical/operator/blob/89ea7f4d56173ea314d59a271e4304b18cd129ed/ops/main.py#L354-L355

https://github.com/canonical/operator/blob/89ea7f4d56173ea314d59a271e4304b18cd129ed/ops/main.py#L540-L543

**Comment by benhoyt** [comment]
@tonyandrewmeyer is going to try to do this as part of his new doc on StoredState.
