### ISSUE TITLE
Warn charms that use collect-metrics, series-upgrade that they are not supported in Juju 4

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/operator#1280]
Juju 4 will not support the collect-metrics event. ops needs to continue supporting it as long as ops supports Juju 3.x, but we can help alert charmers to the need to move away from it.

* We should generate a DeprecationWarning when calling an observer of a collect-metrics event (or when a CollectMetricsEvent object is initialised, etc), that warns the charmer that Juju 4 will not emit these events and gives them info (e.g. a doc link) that helps them move to an alternative. This will end up in debug-log every 5 minutes.

The same applies to the pre-series-upgrade and post-series-upgrade events. A DeprecationWarning may not make sense here, given the circumstances of when these events occur - however, we can make sure it's clear in the documentation.

For what it's worth, I can't find any operator charms that observe collect-metrics, or pre-series-upgrade, and only one that observes post-series-upgrade.

**Comment by benhoyt** [comment]
Thanks. DeprecationWarning sounds good. Initially I was thinking only the [first one](https://docs.python.org/3/library/warnings.html#warning-filter) would be surfaced, but of course it's a new Python instance each time, so yeah, every 5 minutes. That's probably okay if someone is doing this.

I think given the very small usage (if any?) that we've seen of collect-metrics, so I'd say let's not worry about ops.jujuversion.
