### ISSUE TITLE
Simplify Pebble enum|str types to just enum

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1287]
Per our discussion at Charm Tech daily sync today, we'd like to simplify the various pebble enum types from `Union[EnumType | str]` to just `EnumType`, for example, `ServiceInfo.current` now has type `Union[ServiceStatus, str]`, which can be awkward for us (and for charms) to deal with.

The original reason I made them `|str` was so that if a charm is deployed to a newer version of Juju, which has a newer version of Pebble that add a new value to the enum, code won't fail when the enum is being created. To create the value we have code like this:

```python
        try:
            current = ServiceStatus(d['current'])
        except ValueError:
            current = d['current']
```

But that means code that uses these fields have to have awkward types and sometimes have to do awkward things like `use(info.current) if isinstance(info.current, str) else use(info.current.value)`.

So we'd like to simplify the type of these to just the enum type, for example just `ServiceStatus` in this example.

To avoid the charm code raising an exception, we want to add a new value `UNKNOWN = 'unknown'` to all the enum types that are used in this way. If we got an invalid or unknown string value from Pebble, we'd set it to that instead, and give a warning. The code to create the value from Pebble JSON would become something like:

```python
        try:
            current = ServiceStatus(d['current'])
        except ValueError:
            warnings.warn(f'Unknown ServiceStatus value {d["current"]!r}')
            current = ServiceStatus.UNKNOWN
```

(Note that `FileType` already has an `UNKNOWN` value, which is handy.)

**Comment by benhoyt** [comment]
@james-garner-canonical Assigning this to you to see if you can squeeze it in before The Hague.

**Comment by james-garner-canonical** [comment]
Due to backwards compatibility, we can't make this planned change (see discussion on PR #1400).
