### ISSUE TITLE
[BUG] `event.relation.app` is sometimes None

### ISSUE THREAD

**Issue by Gu1nness** [canonical/operator#1306]
While [the code](https://github.com/canonical/operator/blob/main/ops/model.py#L1548-L1625) says `relation.app` should never be None, I encountered at least two cases where this sometimes happens:
 * During a [RelationChanged event](https://github.com/canonical/mongodb-operator/actions/runs/10172341888/job/28135077732#step:27:426)
 * During a [RelationBroken event](https://github.com/canonical/mongodb-operator/blob/6/edge/lib/charms/mongodb/v1/shards_interface.py#L754-L757)

I don't know exactly why the fallback fails here, but it forces us (DataPlatformTeam) to add some edge cases to handle which are not expected.

A bit more information:
 * LXD version : `lxd 6.1-c14927a from Canonical`
 * Juju versions:
 ```
agent_bootstrap_option=--agent-version=3.4.4
snap_channel=3.4/stable
snap_channel_for_artifact=3.4-stable
```
 * ops version: `2.15.0`

**Comment by tonyandrewmeyer** [comment]
Please open a Juju bug for this, with as much information as possible. We've worked on this before and weren't able to find a way to reproduce it, but the Juju team agreed that `JUJU_REMOTE_APP` should always be set and that it's a Juju bug if not. You may wish to reference this [existing closed bug](https://bugs.launchpad.net/juju/+bug/1960934).
