### ISSUE TITLE
Run 'tox -e smoke' in CI

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/operator#1322]
We currently don't run the smoke tests (which at the moment is just packing and deploying on supported bases) in CI, which means that these tests don't get exercised regularly.

We should add a workflow that runs `tox -e smoke` - note that this requires a real Juju, so the environment will need to install Juju, charmcraft, and a local cloud of some sort (e.g. microk8s/k8s or LXD), and bootstrap a controller.

We need to figure out:
* Do we want to just pick a Juju and charmcraft version and use that, or do we want to put those in a matrix (perhaps Juju 2.9, 3.5 (until 3.6 is released), and 4.0, with the latest charmcraft 2.x and 3.x)?
* What should trigger this? A schedule (perhaps just before we expect to release, like the charm dep checks), or only on a merge to main, or on each PR? The tests will be slow, but wouldn't have to be required.

**Comment by dimaqq** [comment]
Poor recollection of stand-up discussion:

- probably a good idea to run the smoke tests sometimes
- can be optional in a PR (is run, not required to merge)
- can be on main branch only (we'd notice before a release)
