### ISSUE TITLE
Remove copyright years from source files

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#1325]
Per team discussion, we're going to remove the copyright year (or year range in some cases) from the top of each source file, but leave the copyright notice itself, so the first line just says `# Copyright Canonical Ltd.`.

[This blog post](https://hynek.me/til/copyright-years/) notes that various large projects and companies have started doing this ([curl](https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/), [React](https://github.com/facebook/react/pull/13593), [Amazon](https://chatter.quux.world/@mark/109621622761353381)), so there's a good precedent.

As mentioned in the [Curl commit])(https://github.com/curl/curl/commit/2bc1d775f510196154283374284f98d3eae03544), there's no legal need:

> - they are mostly pointless in all major jurisdictions
> - many big corporations and projects already don't use them
> - saves us from pointless churn
> - git keeps history for us

**Comment by tonyandrewmeyer** [comment]
FYI, this is the [ruff rule](https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy) I mentioned. I have the feeling we may need to turn it off, because the regex expects a year and can't be customised in ruff. Not 100% sure on that, though.

**Comment by benhoyt** [comment]
Hmm, apparently our legal team recommends keeping just the creation year. And as @james-garner-canonical found, the appendix in the Apache license says to use the format "Copyright [yyyy] [name of copyright owner]" with the year. Oh well, let's be safe and change all the files to just the year the file was created (and no ranges).

**Comment by james-garner-canonical** [comment]
I've standardised the copyright headers to use just creation year, and to always include the full boilerplate from LICENSE.txt

There should be no issues with ruff, as copyright notices with a single year always passed linting.

Note that it looks like docs generation automatically uses just the year, e.g. "Copyright 224 Canonical Ltd." (see docs/custom_conf.py)
