### ISSUE TITLE
`status_set`: document (or link to) the list of valid values

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#1343]
Currently, the docstring doesn't mention that "status" is limited to a set of valid values.
https://github.com/canonical/operator/blob/796918744ef259df0a449a4366b2c184da732029/ops/model.py#L3405-L3410

**Comment by benhoyt** [comment]
Hey Leon, this is the docstring of a method on a private (underscore-prefixed `_ModelBackend`) class, that we see as an implementation detail of Ops. I don't mind adding the set of values it's limited to, but I'm wondering why this is important in the documentation for a method on a private class?

**Comment by tonyandrewmeyer** [comment]
Same question about why it's worthwhile (given that if someone is building something on top of ops so has a legitimate reason to use a private class, they ought to know enough about Juju to know the possible values), but for what it's worth, I'd suggest we would do this by just type annotating `status`, [identically to how it already is in Harness's backend](https://github.com/canonical/operator/blob/8bc7ad8ddf9a0fb9f90c2b6c7c3583467cc040f5/ops/testing.py#L2492).

**Comment by tonyandrewmeyer** [comment]
This was fixed in #1354.
