### ISSUE TITLE
Operator Framework logo

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/operator#136]
Hi there,

I'm in the process of documenting the Framework, one thing I noticed is there's no logo! can we get one? :smile: 

Cheers,
Peter

**Comment by jameinel** [comment]
We have Juju logos from here: 
https://design.ubuntu.com/downloads/
Specifically the Juju ones come in a few formats (print formats, .png, .ico, etc):
https://assets.ubuntu.com/v1/a14dcb39-6a.-JUJU_BRANDMARK_AW.zip

![juju_orange_hex](https://user-images.githubusercontent.com/202877/74325598-54256900-4da2-11ea-9235-a8ffa4153c45.png)

That isn't quite right for the charming operator framework, but it is a start.

**Comment by VariableDeclared** [comment]
@jameinel. Thanks i'll add this to the docs!
