### ISSUE TITLE
Pass charm type to Context.manager

### ISSUE THREAD

**Issue by Batalex** [canonical/operator#1444]
Hi,

When I am writing tests using the new testing framework formerly known as scenario, I find myself adding a line like this:

```python
    with ctx(ctx.on.start(), state_in) as manager:
        charm = cast(KafkaCharm, manager.charm)  #  <-- This line...
        assert not charm.broker.healthy  # <-- ...gives me autocomplete and type checker validation

```

In larger code bases, this boilerplate adds up to numerous lines.

With a few tweaks to `Context` and `Manager`, we can make them variadic types and get this nice user experience:

![Capture d’écran du 2024-10-31 17-27-55](https://github.com/user-attachments/assets/bcd0b7e2-07b3-45b1-b8a6-7eaa67e02fc3)

If that's something you are interested in, I can open a PR. Have a look at [my branch on ops-scenario](https://github.com/Batalex/ops-scenario/commit/94931d34363913deeb527aff12b2a852ceb386f1), and let me know what you think!

**Comment by tonyandrewmeyer** [comment]
> If that's something you are interested in, I can open a PR. Have a look at [my branch on ops-scenario](https://github.com/Batalex/ops-scenario/commit/94931d34363913deeb527aff12b2a852ceb386f1), and let me know what you think!

That would be great, thanks!
