### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by gnuoy** [canonical/operator#158]
I know this is stating the obvious but the lack of documentation makes writing a charm a much less pleasurable experience. It is not always clear what the intent is of parts of the design, it means features that could be leveraged are missed and on a practical level it means lots of hunting around to try and workout how to do trivial things.

I would be reluctant to publish a charm and mark it production if  there was no documentation supporting the framework it is written in.

I'm sure this on someones roadmap but I thought I'd raise a bug to track it.

**Comment by chipaca** [comment]
working on it. Sorry it's taking so long.

**Comment by VariableDeclared** [comment]
@chipaca is there a branch for this? I don't want to duplicate your work.

**Comment by chipaca** [comment]
@VariableDeclared not yet. Your work in #135 is part of the answer, here, though!

**Comment by VariableDeclared** [comment]
Cool, cheers @chipaca. I have some questions coming your way

**Comment by jnsgruk** [comment]
This could now be closed with https://juju.is/docs/sdk going live?

**Comment by gnuoy** [comment]
> This could now be closed with https://juju.is/docs/sdk going live?

Yes, I think its fine to close it, thanks.
