### ISSUE TITLE
[Question] Does the operator framework support actions? If so, how can we do this

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/operator#167]
Hi Charm Team,

As the title says, does the new Framework provide actions? If so, how can this be done? Code examples welcome.

Cheers,
Peter

**Comment by dshcherb** [comment]
- create actions.yaml as usual;
- self.framework.observe(self.on.<action_name>_action, on_<action_name>_action);
- The `event` argument passed into a handler will be an instance of ActionEvent;
- `event.params`, `event.log`, `event.set_results`, `event.fail` methods are available for working with the action context.

Example:

```
class MyCharm:

    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(self.on.upgrade_action, self.on_upgrade_action)

    def on_upgrade_action(self, event):
        my_param = event.params[“my_param”]

        event.log(“Upgrade progress: 42%”)
    
        event.set_results({“success”: “false”})
        event.fail(“Almost got it but not quite.”) 
```

**Comment by VariableDeclared** [comment]
Nice! thank you @dshcherb
