### ISSUE TITLE
A way to easily drop the developer inside their running Python code

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#180]
*(chat excerpt so we don't loose the idea)*

facubatista: which is the fastest/simplest/easiest way to "locally debug a charm"? IOW, I have some code, and I want to run it, send events, see what happens, etc
niemeyer: facubatista: This is an interesting area to think about.. it would be great to have a way to very easily drop people _inside their Python code_
niemeyer: facubatista: debug-hook will drop you into a shell
niemeyer: facubatista: What we're talking about now is enabling someone to run the charm for real and having a breakpoint on it
facubatista: 1. a tool/mechanism for charm developers to debug their charms in real situations; a way to do something like "import operator_pdb;operator_pdb.set_trace()" in the code, then "juju deploy mycharm" in a real life situation, which would block, and "juju connect-pdb something"
niemeyer: facubatista: Yeah, except hopefully the breakpoint mechanism is generic instead of Python specific, but otherwise yes
niemeyer: facubatista: Also, ideally it wouldn't depend on you adding that breakpoint into the code itself
niemeyer: facubatista: In other words, the framework should support stopping at interesting points by itself
niemeyer: facubatista: So you don't need to change the charm to introspect it

**Comment by dshcherb** [comment]
One thing I have in mind is providing a PDB plugin which would expose a pdb session over a unix socket.

The problem with exposing a network socket is that a system becomes vulnerable as a root shell is essentially provided without authentication (this is what rpdb would do).

Providing a unix socket accessible by a root user seems better and `juju ssh` can then be used to ssh into the target and connect to this unix socket.

This doesn't address the problem of allowing breakpoints in arbitrary places though.

**Comment by stub42** [comment]
Related, I'd like visibility in my logs to what the framework is doing, such emitting log messages when events are fired, observers called, events deferred. This would provide visibility and discoverability (questions I had were things like when do deferred events get refired? If an event is deferred, do other observers still get invoked? Do observers get called in the order they are registered?). DEBUG and TRACE level logging to the Python logger would be fine for this, allowing the charm to turn it on or off as needed. It may be turned on automatically in some circumstances, perhaps reacting to the Juju model log settings.

**Comment by jameinel** [comment]
We do already hook into 'juju-log' to allow Python logging lifecycle events
to end up in the overall log for the unit. (I believe we default to INFO as
passed through.)
There isn't currently a way for Juju to signal the Charm that we want a
different logging level (though the charm could always define its own
config for that.)
I think there is an intent to have a bit more logging by default in the
operator framework, though if there are particular things that you feel are
missing, feel free to point them out.
Also, we chose to stick with Python logging, which means that there isn't a
TRACE, but there is a DEBUG level.

**Comment by matuskosut** [comment]
looking at ipython may be useful, it can be launched within code using embed, with all the context. Also it allows to set predefined commands, which could help setting up pdb.

**Comment by facundobatista** [comment]
The code for this is already in master and working with Juju >= 2.8.

We're still working on the last details regarding documenting all this.

**Comment by facundobatista** [comment]
[Docs!](https://discourse.juju.is/t/live-debugging-at-python-level/2914)
