### ISSUE TITLE
Implement a method to expose the version (application-version-set)

### ISSUE THREAD

**Issue by woutervb** [canonical/operator#183]
Currently it is not possible to set the version string of the code that the charm is running.

I think it's a matter of adding it to the ModelBackend class in model.py, but there might be a reason it's not implemented yet, so I am willing to implement, unless there are objections.

**Comment by mthaddon** [comment]
I think this is a duplicate of https://github.com/canonical/operator/issues/174 ?

**Comment by chipaca** [comment]
yep
