### ISSUE TITLE
"pod spec" will become "k8s spec" in Juju

### ISSUE THREAD

**Issue by dshcherb** [canonical/operator#185]
https://github.com/juju/juju/pull/11323

We will need to use the new hook tool name as of the Juju version which will get this.

**Comment by niemeyer** [comment]
It really shouldn't while we're working out the details of the k8s support improvement that we might have happening soon.

@jameinel Can you please close this ticket once we've confirmed that this change is paused for the time being?

**Comment by jnsgruk** [comment]
@jameinel This should probably be closed on account of the change in design for k8s charms?
