### ISSUE TITLE
Improve calling for Object descendant tree 

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#188]
Everything inheriting Object needs to be instantiated passing `framework` and `key` as parameters.

However, not always makes sense to have a `key`, but we're forced to pass it and end up passing None (as in charm.py l.193, when we instantiate all charms!).

I propose the Handle class' `__init__.py` signature to be...

    def __init__(self, parent, kind, key=None):

...allowing everybody to not pass a key if "only one instance of the object is intended".

Beyond this more explicitly defined behaviour, there are some other benefits:

- `Handle.__init__` can be more explicit; start to ask "if key is None", for example, currently it has a more weak comparison to False, which would produce strange situations if 0 or "" is passed.

- we could stop passing Nones all around for this

- documented (and suggested) way to write a charm would make more sense:

    ```
    def __init__(self, framework):
        super().__init__(framework)
    ```

    (instead of having `*args` or worse: passing a key that is always None)

**Comment by jameinel** [comment]
I'd want to see the implications in code, but it does sound sensible. Especially having CharmBase not expect to have a key that it then ignores. (Though we could just do that with the CharmBase.__init__ signature without having to change all of Object.)
I don't think *most* objects are intended to be singletons, so I would be cautious about making it too easy to write it that way, and then having to rewrite once you realize what is really going on.

I definitely support it for CharmBase, not sure about changing the root Object.__init__.

**Comment by facundobatista** [comment]
What about "detecting" that the developer is instantiating two instances of the same class while not providing a differentiating key?

This way we could keep the simple case "simple", using key only for non-unique instances, and not giving room for the error.

**Comment by jameinel** [comment]
We already do. If you instantiate 2 Objects in the same Framework with the
same Handle we will throw an error.
