### ISSUE TITLE
DEBUG log messages not emitted

### ISSUE THREAD

**Issue by stub42** [canonical/operator#198]
The JujuLogHandler in ops/log.py defaults its loglevel to INFO. This means that it will not handle DEBUG log messages from the Logger instances. I believe normally it should default to NOTSET, handling all log level messages, but DEBUG may be better here since juju-log will not handle lower priority messages. With the Handler handling all levels of messages, calling setLevel on the relevant logger will have the desired effect.

**Comment by facundobatista** [comment]
If Juju accepts log lines in DEBUG level, we should NOT filter them in the handler.

OTOH, it's fine for the logger to start in INFO, the developer can easily change that.
