### ISSUE TITLE
Testing hardness: _TestingModelBackend.relation_ids raises KeyError if a relation present in the charm meta has not been added via Harness.add_relation

### ISSUE THREAD

**Issue by dshcherb** [canonical/operator#202]
The current real backend behavior is to return an empty list of relation ids for a relation endpoint for which there are not relation ids yet.
```
juju run --unit cockroachdb/0 'relation-ids --format=yaml proxy-listen-tcp'
[]
```
The same is true for endpoint names that are not even declared in the charm metadata.yaml:
```
juju run --unit cockroachdb/0 'relation-ids --format=yaml does-not-exist'  
[]
```

`testing.py` code currently uses `self._relation_ids_map[relation_name]`, not `self._relation_ids_map.get(relation_name, [])` to retrieve a list of relation ids from the test backend which is a deviation from the real backend behavior.

```python3 -m unittest
E
======================================================================
ERROR: test_real_relation_data (test.test_cluster.TestCockroachDBCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/src/canonical/juju/cockroachdb-operator/test/test_cluster.py", line 29, in setUp
    self.harness.begin()
  File "lib/ops/testing.py", line 101, in begin
    self._charm = TestCharm(self._framework, self._framework.meta.name)
  File "src/charm.py", line 81, in __init__
    self.tcp_load_balancer = ProxyListenTcpInterfaceProvides(self, 'proxy-listen-tcp')
  File "lib/interface_proxy_listen_tcp.py", line 81, in __init__
    self._relation = self.model.get_relation(relation_name)
  File "lib/ops/model.py", line 61, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
  File "lib/ops/model.py", line 268, in _get_unique
    num_related = len(self[relation_name])
  File "lib/ops/model.py", line 245, in __getitem__
    for rid in self._backend.relation_ids(relation_name):
  File "lib/ops/testing.py", line 345, in relation_ids
    return self._relation_ids_map[relation_name]
KeyError: 'proxy-listen-tcp'
```

**Comment by dshcherb** [comment]
For endpoints that do not exist in metadata.yaml there is an earlier check in `model.py` so in that case the expected result _is_ a KeyError.

  File "/home/ubuntu/src/canonical/juju/operator/ops/model.py", line 268, in _get_unique
    num_related = len(self[relation_name])
  File "/home/ubuntu/src/canonical/juju/operator/ops/model.py", line 242, in __getitem__
    relation_list = self._data[relation_name]
KeyError: 'does-not-exist'

**Comment by jameinel** [comment]
I don't know if you intended to close this, but I think I did:
https://github.com/canonical/operator/pull/196
While it still raises an error if you call relation-ids for a relation that doesn't exist, I feel like that is more helpful to charmers than harmful

**Comment by dshcherb** [comment]
@jameinel I think #196 covers what I need when it comes to not raising an exception when an endpoint is in the metadata but there are no relation-ids yet. I will close #204 in favor of #196.
