### ISSUE TITLE
REQ: Access to kubernetes secrets

### ISSUE THREAD

**Issue by tcuthbert** [canonical/operator#208]
Sometimes secrets are generated as part of the charm deployment and need to be exposed to users. We traditionally achieved this with Juju actions that read the secrets from disk however this isn't suitable for k8s deployments. It would be preferable for the operator framework to have read/write access to kubernetes secrets so that when secrets are generated we are able to store them securely and in a way that allows operators to access them if need be.

**Comment by timClicks** [comment]
Meta comment - please add feature requests to the charming category within the Juju discourse.

**Comment by jameinel** [comment]
Reading through the K8s docs
https://kubernetes.io/docs/concepts/configuration/secret

It seems there are several ways to 'access secrets' which I think we need a bit more clarification from you.
It is common to mount secrets as a volume for the running application, which means you can just write an action which reads it from disk and reports it back.
Either way, the charm is probably the code that is creating the secret and telling K8s how it is meant to be used (where to put it on disk/in an env var/using the secrets api.)

I think if we want to support a GET request on the K8s Secrets API, that is a great thing for a Component to handle. We're currently looking at polishing and promoting the de facto standard K8s adapter into a standard library component for people to share. Having access to things like secrets from that object feels like a good place to put that functionality.

**Comment by relaxdiego** [comment]
@jameinel can you share a link to this de facto standard k8s adapter? I'd like to help contribute to it. I already have a working k8s adapter in a couple charms I'm working on (e.g. https://github.com/relaxdiego/charm-k8s-prometheus/blob/129aa60fb4906bd78fd3117c2dd8228d09b7e0ef/src/adapters/k8s.py) and am quite familiar with how secrets are created and consumed by pods.

**Comment by chipaca** [comment]
@relaxdiego dude, it's yours

**Comment by relaxdiego** [comment]
@chipaca oh lol. well alrighty then! 😂

**Comment by jnsgruk** [comment]
A brief update to this; we are currently working on Juju Secrets, which will create a first class notion of what a secret is across substrates. There is already early code landed behind a feature flag, but the Operator Framework implementation is still to follow.

In later iterations, there will be the option to back a model's secrets in different data stores, one of which will be Kubernetes Secrets.

**Comment by benhoyt** [comment]
The Secrets API has just been merged. The latest released version of Juju only supports the Juju controller as a backend, but work is underway to support K8s Secrets and Hashicorp Vault backends -- I'm guessing that wil be released in January. Leaving this open a bit longer to notify here when that happens.

**Comment by benhoyt** [comment]
Closing this now that "kubernetes" is one of the backends for Juju Secrets in Juju 3.0.2. See more in the QA steps at https://github.com/juju/juju/pull/14676 (though I believe the model-config field is called `secret-backend` now).
