### ISSUE TITLE
Test Harness prevents charm from registering events

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/operator#217]
Hi,

When trying to use the test harness it takes our charm and [prevents the charm from registering events](https://github.com/canonical/operator/blob/17f4885b73d7b2bfb7445388e7e62b9fcd040859/ops/testing.py#L96) which dependencies/interfaces might refer to later. e.g. `mysql_relation_joined`. 

This presents a problem when coming to register the charm, for example in my case an interface will attempt to register these events causing an [AttributeError](https://github.com/johnsca/interface-mysql/blob/7c51f5aa38a19d03ab844491b09ed6611f9b54b8/interface_mysql.py#L76).

```
AttributeError: 'CharmEvents' object has no attribute 'mysql_relation_changed'   
```

The charm init looks like this:

```
class OSMUIK8sCharm(CharmBase):
    state = StoredState()

    def __init__(self, framework, key):
        super().__init__(framework, key)
        # breaks here
        self.mysql = MySQLClient(self, 'mysql')
        self.ui_image = OCIImageResource(self, 'osm_ui_image')
        # TODO(pjds): How can we set the maintenance status?
        self.framework.observe(
            self.mysql.on.database_available,
            self.configure_pod
        )
        self.framework.observe(
            self.mysql.on.database_changed,
            self.configure_pod
        )
        self.framework.observe(self.on.config_changed, self.configure_pod)
```

I'm attempting to test like so:

```
class TestOSMCharm(unittest.TestCase):

    @patch('interface_mysql.MySQLClient')
    def test_set_leader(self, *args):
        harness = Harness(OSMUIK8sCharm)

        harness.set_leader(False)
        harness.begin()
        self.assertFalse(harness.charm.model.unit.is_leader())
```

Is there some other way that I should be approaching the harness? 

Thanks in advance
Peter

**Comment by dshcherb** [comment]
Hi Peter,

Could you please post your metadata.yaml?

**Comment by VariableDeclared** [comment]
Hey @dshcherb 

Thanks for pointing that out, I was missing the interfaces section from the metadata.yaml:

```
requires:
    mysql:
        interface: mysql
```

Cheers!
Peter

**Comment by dshcherb** [comment]
No problem, feel free to reach out if you are stuck!
