### ISSUE TITLE
The pod spec API must be improved

### ISSUE THREAD

**Issue by niemeyer** [canonical/operator#229]
The initial support for the operator framework operator was implemented with a single function:
```
model.pod.set_spec(my_spec_yaml)
```
That's not a great API to use from Python, and that was known at the time. The rationale for that very minimal API is that we want to improve the behavior of k8s charms further in the near future, so ideally the proper API in the operator framework will be designed with more understanding of what is to come. That also makes more clear why we have a Pod object supporting a single method: this method reflects the API currently supported by juju itself, and we'll be able to maintain it working for as long as juju itself preserves compatibility.

This issue will remain open while we sort these details out.

**Comment by jnsgruk** [comment]
Closing this for now, we have now implemented support for Kubernetes charms using the sidecar pattern. I wrote a post about this [on Discourse](https://discourse.charmhub.io/t/the-future-of-charmed-operators-on-kubernetes/4361). The pod spec API will remain for now, but is not the focus for active development of new features, etc. 

I think the introduction of the sidecar pattern charms closes this ticket nicely :)
