### ISSUE TITLE
Review of wordpress kubernetes charm

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#243]
Hi,

We'd like to have the charmcraft team review the wordpress kubernetes charm that we've been working on. 

The charm is available here: https://jaas.ai/u/wordpress-charmers/wordpress
The code is available here: https://code.launchpad.net/~wordpress-charmers/charm-k8s-wordpress/+git/charm-k8s-wordpress/+ref/master 
I don't think you'll be too interested in the docker image we use with this, but if you are, the code we use to build the image is here: https://code.launchpad.net/~wordpress-charmers/charm-k8s-wordpress/+git/wordpress-k8s-image-builder

Thanks, Tom

**Comment by relaxdiego** [comment]
Might be good to add this to https://github.com/canonical/operator/issues/205 as well.

**Comment by mthaddon** [comment]
I think this can be closed now, the review happened via other means.
