### ISSUE TITLE
Incorporate type hinting in all public methods, and check them

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#255]
As part of our "journey to stable" we decided that will incorporate type hints in all our public methods, functions, etc.

Also, we should check in our unittests that we're not breaking that contract.

**Comment by jnsgruk** [comment]
Agree with this, once #621 is merged, we have a nice route to add `mypy` into our linting. I'll add this to the backlog for the team now.

**Comment by benhoyt** [comment]
This is now complete with the release of `ops` [1.5.3](https://github.com/canonical/operator/releases/tag/1.5.3).
