### ISSUE TITLE
Auto determining handlers is actually not recommended

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#265]
Now that we've had some time with the framework, the fact that you can do: 
```
  self.framework.observe(self.on.config_changed, self)
```

actually seems to be a misfeature. We actually prefer to have the observer methods being private (_on_config_changed), and having the above actually takes away from the 'explicit' nature that we actually prefer. (With the above syntax you can't actually grep for places that call your handler, you have to know the magic and search for the on.config_changed rather than the function name.)
It also leads people to want things like:
```
self.framework.observe(self)
```
Some form of 'just look at the object and figure it out yourself.'. 
It also suffers from things like typos (why isn't self.on_cnofig_changed getting called). Being explicit avoids a lot of the pitfalls, so we'd like to just remove the automatic discovery.

We'll need to be careful, and message it clearly because certainly existing charms are using the short form.

**Comment by facundobatista** [comment]
+1 to remove this.

We can take this opportunity and start talking about "deprecation warnings".

**Comment by jameinel** [comment]
dup: #297

**Comment by jameinel** [comment]
Duplicate of #297
