### ISSUE TITLE
Relation.role should be 'peer' not 'peers'

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#271]
The other sections "provides" and "requires" feel fine as a role name, but "peers" is not a role as much as "peer" is the role.

This is a breaking change, as any code that was doing Relation.role == 'peers' will no longer work.

I wouldn't expect charms to be using role particularly often (they are the ones that are defining a given relation is a peer relation, thus they can use the name of the relation rather than the role attribute). We do use it in our own code.

The fix is small, but we have to be clear that it is changing of a public attribute.

**Comment by facundobatista** [comment]
Is there something we can do for people not writing code comparing to "magic strings"?

Something like `Relation.role == Relation.PEER`?
