### ISSUE TITLE
Currently no way to get the model name

### ISSUE THREAD

**Issue by relaxdiego** [canonical/operator#274]
The framework does not expose an API endpoint that allows a charm to get the model it is deployed in. I'm currently using it to get to the k8s namespace where the underlying k8s pod is deployed in so that I can get the latter's liveness/readiness status. Here is a sample code: https://github.com/relaxdiego/charm-k8s-grafana/blob/master/src/charm.py#L93

Currently I am using `os.environ["JUJU_MODEL_NAME"]` to get this information. Is it possible to have the framework provide an abstraction for this instead?

**Comment by jameinel** [comment]
I think it makes sense to expose this as `self.model.name`. We can add that attribute to Model and have it populated during main() from `os.environ`.
