### ISSUE TITLE
recommend install hook over start

### ISSUE THREAD

**Issue by jetpackdanger** [canonical/operator#290]
The "start" hook seems to run too late to catch events early in a charm's lifecycle.  Here's an example where I deployed mattermost and related it to postgresql immediately:

```
application-mattermost: 17:24:27 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running install hook
application-mattermost: 17:24:28 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running db-relation-created hook
application-mattermost: 17:24:29 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running leader-elected hook
application-mattermost: 17:24:29 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running config-changed hook
application-mattermost: 17:24:29 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running start hook
application-mattermost: 17:24:30 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running db-relation-joined hook
application-mattermost: 17:24:31 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running db-relation-changed hook
application-mattermost: 17:24:33 DEBUG juju.worker.uniter [AGENT-STATUS] idle: 
application-mattermost: 17:24:42 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running db-relation-changed hook
application-mattermost: 17:24:43 DEBUG juju.worker.uniter [AGENT-STATUS] idle: 
application-mattermost: 17:24:56 DEBUG juju.worker.uniter [AGENT-STATUS] executing: running db-relation-changed hook
application-mattermost: 17:24:58 DEBUG juju.worker.uniter [AGENT-STATUS] idle:
```
Since this charm only symlinks hooks/start as recommended, it misses the first four hooks above. In particular, a charm design that relies on deferring config-changed may, in a situation like this, never receive a config-changed at all.

**Comment by jameinel** [comment]
The issue is that in Juju 2.7 it only issued 'start', and was fixed to
start giving 'install' hooks. So we recommend both 'start' and 'install' as
2.7 won't trigger an install hook, and 2.8 triggers 'install' as the first
hook.
In 2.8 we actually recommend using 'dispatch', which is a path in the top
level directory that avoids the need to symlink every event. (if a
$CHARMDIR/dispatch exists, then it is called for all hooks rather than the
individual 'hooks/*'.)

**Comment by facundobatista** [comment]
Even if we have the "dispatch mechanism", people needs to hook on the events, and it's the same situation: shall they hook to `install` or to `start`.

That said, after having "dispatch" this falls more on the Juju side of documentation/learning. 

Also, now that we automatically log all events that are received, and if they're handled or not, this would be much more discoverable.

**Comment by chipaca** [comment]
What we need to do is update our README to follow the right recommendations, and why. I'll do this.
