### ISSUE TITLE
Add resources to harness for oci-images

### ISSUE THREAD

**Issue by chris-sanders** [canonical/operator#295]
When writing K8s charms before calling pod.set_spec the image information is fetched. The current Harness doesn't have any resources registered and returns a keyerror when trying to run the fetch.

By registering a temporary file into the resource map and populating it with the three values that OCI images contain, you can use Harness to retrieve image information and process the pod spec for validation.

**Comment by relaxdiego** [comment]
dup of #262

**Comment by jameinel** [comment]
duplicate: #262
