### ISSUE TITLE
Use git describe to log version when running from git

### ISSUE THREAD

**Issue by chipaca** [canonical/operator#304]
Have something like
```python
def _get_version() -> str:
    # if we're running from git, return the git describe
    # BUT, don't mistake “running from git” with “running from a virtualenv in
    # something else's git tree”.
    # easy '90%' approach: check for ../.git
    p = os.path.dirname(__file__)
    version = ops.__version__
    if os.path.exists(os.path.join(p, "../.git")):
        try:
            proc = subprocess.run(
                ['git', 'describe', '--always', '--dirty'],
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                cwd=p,
                check=True)
        except Exception:
            pass
        else:
            version = proc.stdout.strip().decode('utf8')
    return version

```
in main.py to log that.

**Comment by jameinel** [comment]
Wouldn't it be better to have a Makefile with:

ops/version.py:
  echo "__version__ = '`git describe --always --dirty`'" > ops/version.py

which we could then potentially save into our Pip tarball?

**Comment by chipaca** [comment]
if I'm understanding correctly, that wouldn't give us what we want, which is a distinctive (and helpful) git version when we get a report from somebody running from git. It would also mean that the git tag used for release is not the actual release, which I'm not too fond of but wouldn't say it's a blocker.

On the other hand, maybe you mean have code that checks for version.py and if that doesn't work then get the version from git, ie something like
```python
try:
    from .version import version
except ImportError:
    proc = subprocess.run(...)
    # etc
```

that would work. And, don't know about the Makefile, but certainly it's something that `setup.py` can do.

**Comment by jameinel** [comment]
If you put it into the .tar.gz then it can be built from exactly the
release version that you tag. You can't check it into source code, but we
can freeze it for official builds.
