### ISSUE TITLE
Add [ops:<version>] to operator log lines

### ISSUE THREAD

**Issue by chipaca** [canonical/operator#306]

**Comment by jameinel** [comment]
In some ways I like this, in other ways we're just adding more noise because we want to see *our* things. I'm worried we might have a bit of bias in what makes good log output.

**Comment by chipaca** [comment]
this came about because I'd added a `Ops version {} up and running.` log line to `main`, but it's logged so frequently (naturally) that it gets annoying

**Comment by jameinel** [comment]
Does it make sense to report the operator framework version as a standard
procedure? I'd love to have an easy way to do it, and maybe it makes sense
at DEBUG level, but it feels like something that I agree shouldn't be
logged on every hook invocation.

What if we used a state file and reported it only when it changes? eg:
```
 with open('/tmp/ops-reported-version.txt', 'w+') as f:
  reported = f.read()
  if not reported or reported != ops.__version__:
    logger.info('Ops version: {}'.format(ops.__version__))
    f.seek(0)
    f.write(ops.__version__)
```

It isn't critical if that temp file gets deleted, it is just to keep us
from spamming the log file.
John
=:->

**Comment by chipaca** [comment]
hey, we could even store last-seen-version in framework._stored :-)

**Comment by stub42** [comment]
Conversely, if you have gone to the trouble of turning on DEBUG level logs, you are asking to see the information useful for debugging your charm. 'logged so frequently' is what I've explicitly asked for. At DEBUG level, as a charmer I'd expect log messages for at the start of main(), information about what hook is being run + relevant relation ids, when events fire such as the hook event, pre-commit and commit, and a successful termination message.

**Comment by jameinel** [comment]
I agree that it is fine to include at DEBUG level.

**Comment by chipaca** [comment]
As I understand it, the agreement from above is:
* if `JUJU_DEBUG` is set, then include `[ops:<version>]` in every log line
* otherwise, add a debug log of `Ops version {} up and running.`

is that right?

**Comment by jameinel** [comment]
My understanding is that we just always logger.debugf("Ops version...") so
that someone can always set "juju model-config logging-config=DEBUG" and
see that information.
