### ISSUE TITLE
Model.config is mutable

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#332]
ConfigData itself is just a LazyMapping and isn't a MutableMapping, but the attribute is just a regular attribute so it is possible to:

self.model.config = {'new': 'config'}

We should probably turn config into a @property so that it can only be read.

**Comment by chipaca** [comment]
is there anything on framework/model/etc that _is_ intended to be directly replaced?

**Comment by jameinel** [comment]
relation data for your unit is settable and status is settable. I can't
think offhand of anything else that should be mutable.

**Comment by chipaca** [comment]
in #411 i'm making model only have properties, no attributes at all.
