### ISSUE TITLE
debug-code silently fails if src/charm.py is not executable

### ISSUE THREAD

**Issue by stub42** [canonical/operator#339]
'juju debug-code' bombs out silently if the charm contains a src/charm.py that fails (eg. an import error). I think the same will happen if the execute bit is not set. If you are quick you will see a flash of traceback before the tmux window closes.

Perhaps the dispatch script should be a little smarter? Perhaps this is a juju issue instead, and a keypress required to close the tmux window if the hook failed.

**Comment by chipaca** [comment]
We'll look at fixing it on the juju side :-)

**Comment by chipaca** [comment]
This is lp:1885555

**Comment by jnsgruk** [comment]
I think this is adequately covered by https://bugs.launchpad.net/bugs/1885555, so I'll close this for now, but can reopen if this re-emerges as a framework issue
