### ISSUE TITLE
Harness could start with config initialized from config.yaml

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#345]
Currently the Operator framework never looks at config.yaml, assuming that you will get the appropriate config from Juju based on config.yaml and we don't need to do our own work.
As such, config.yaml isn't read by something like CharmMeta.
As such, Harness doesn't expose ways to read config.yaml to set the default config.

Currently, you have to call Harness.update_config() to set the initial content of the config.

We could
a) Add a parameter 'config=' to Harness's constructor, like we currently do for meta=, actions=, and if it isn't set, then default to reading config.yaml as we do for the other CharmMeta attributes.
b) Add a method read_default_config() that would read config.yaml and apply the settings there.

(a) has the small problem of possibly breaking tests that  have a config.yaml but don't expect the default from that config to be set. I think this case is relatively small, and outweighed by the benefit of having default config available during testing.

**Comment by alejdg** [comment]
:+1:
