### ISSUE TITLE
Support collect-metrics normally once Juju runs it as a normal hook

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#348]
This is mostly a place to keep a reference of the current issue, and provide people context and understanding of what is going on.

Traditionally, 'collect-metrics' was a hook run by Juju asynchronously from other hooks. (Most hooks run serialized, so 'start' is never run while 'install' is still running.) There were some design goals about collect-metrics that it always run deterministically every 5 minutes, so it could try to run while another hook was running. As such, it needed to run in a restricted context, so that you would never have 2 hooks mutating charm state simultaneously. This means that things like "config-get" and "relation-get" are not available during collect-metrics hooks.
But that also means that inside the Operator framework, we can't provide most of our functionality during collect-metrics, because the underlying events aren't available. 
https://github.com/juju/juju/blob/de695afe4f07fc4bad2012e55e81850357249b22/worker/uniter/runner/jujuc/restricted.go#L26 is a list of all the internal methods might be restricted.
https://github.com/juju/juju/blob/de695afe4f07fc4bad2012e55e81850357249b22/worker/metrics/collect/context.go#L43
is the list of methods that are allowed

There has been a relaxing of the design goal that collect-metrics *must* be run every 5 minutes, which would allow it to run as any other hook, with full context support. Once that is done, we'll want to have a way to know inside the operator framework that even though collect-metrics was traditionally restricted, it no longer is, so we can function as normal.

**Comment by benhoyt** [comment]
This requires a change to Juju to run collect-metrics as a normal event. We can reopen if and when that happens.
