### ISSUE TITLE
Support extra service names

### ISSUE THREAD

**Issue by knkski** [canonical/operator#356]
I have a charm called `pipelines-api` that is part of the Kubeflow bundle. There are other bits of Kubeflow that default to attempting to talk to the service at `ml-pipeline`. Right now, we solve this by `kubectl apply`'ing a Service called `ml-pipeline` that just redirects off to the `pipelines-api` Service, see here:

https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L289

Would it be possible to support creating multiple service names for a given charm instead of manually `kubectl apply`ing an extra Service?

**Comment by jameinel** [comment]
I think this is more of a Juju question than an Operator question.

**Comment by chipaca** [comment]
@knkski could you file this over in Juju, and link to that bug here? Thanks.

**Comment by knkski** [comment]
@chipaca: Sure, filed https://bugs.launchpad.net/juju/+bug/1887978
