### ISSUE TITLE
Add support for startupProbe checks

### ISSUE THREAD

**Issue by jayk-canonical** [canonical/operator#357]
Hello!

During testing and attempts to deal with application jobs, such as migration, I discovered that while the operator framework has support for kubernetes' livenessProbe and readinessProbe checks, it does not support specification of startupProbe checks.

Can you please add support for setting startupProbe checks?

In terms of reasoning - startupProbe checks are special in that kubernetes will not start probing for liveness or readiness until a startupProbe has been successful.  This is very useful when you have startup processes that can take some time that can not be easily predicted, such as a database migration.  

With a startupProbe, you have a way to let kubernetes know that the startup process is complete.  Without a startupProbe, kubernetes can start livenessProbes too soon and can view a pod as being not live during that startup job and will then kill the pod before it can finish.  In a worst case scenario this can lead to a 'pod can never finish starting' issue. 

Please let me know if I can provide any additional information.

**Comment by jayk-canonical** [comment]
This appears to be a limitation of Juju itself.  I have filed a bug with Juju [here.](https://bugs.launchpad.net/juju/+bug/1887440)

**Comment by jameinel** [comment]
That looks like it is fixed in Juju for 2.8.2
