### ISSUE TITLE
JUJU_VERSION not set during metrics hooks

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#372]
As seen by @camille-rodriguez :
During 'meter-status-changed'
https://paste.ubuntu.com/p/WZfMRkvgyn/

Metrics hooks run in a Limited context which seems to define its own set of vars:
https://github.com/juju/juju/blob/develop/worker/uniter/runner/context/context.go#L946
vs
https://github.com/juju/juju/blob/develop/worker/meterstatus/context.go#L44

Ideally this also gets fixed in Juju, but in the short term, we don't want to break because of a meter-status-changed or a collect-metrics hook getting triggered.

**Comment by jameinel** [comment]
https://bugs.launchpad.net/juju/+bug/1891337 is about fixing this in Juju

**Comment by chipaca** [comment]
I think doing #365 will address this, won't it?

**Comment by jameinel** [comment]
My concern is that Install will see a JUJU_VERSION of 2.8 above a threshold
but then collect-metrics runs and sees a version of 0.0 which ends up below
a threshold and confuses the charm.

**Comment by dstathis** [comment]
Should this still be open? #365 was merged already.

**Comment by jameinel** [comment]
I would certainly want us to test whether it works the way we want. The
issue is that you might see Juju 2.8+ and go with server-side storage, but
then a metrics hook fires without JUJU_VERSION and you think 'oh, I must
need local storage because my version is 0.0.0' and then the next hook that
fires sees that there is local storage, and ignores all of the state that
it had previously recorded in server-side storage.

**Comment by johnsca** [comment]
You could fall back to querying the machine agent, like [charmhelpers does](https://github.com/juju/charm-helpers/blob/master/charmhelpers/core/hookenv.py#L1287).

**Comment by benhoyt** [comment]
Can close this for now -- now always running "new Juju" (2.8 or whatever it is).
