### ISSUE TITLE
Add best practice suggestions into docs

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#386]
It will be useful to have a file enumerating best practice for developing operator charms . For example "Use of submodules must be avoided, all dependencies must be through a requirements.txt file" . The "docs" folder has index.rst file that aggregates API docs. Perhaps an "practice.rst" may be added to it.

**Comment by jnsgruk** [comment]
Hoping we can get this closed next week once the new docs are published @balbirthomas?

**Comment by balbirthomas** [comment]
> Hoping we can get this closed next week once the new docs are published @balbirthomas?

Agreed. Thank you.

**Comment by balbirthomas** [comment]
Closing since docs release are around the corner.
