### ISSUE TITLE
Create basic documentation

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#394]
These are items for docs that should live in Discourse or RTD (but as part of a narrative explaining how the system works, not fragmented texts in different docstrings)...

- [ ] Basic "how a charm works" documentation
  - what is StoredState and how it works, which types are allowed, how to init
  - how to hook events
  - what are `actions`, how they differ from regular events, and the differences in naming and where are declared
  - what is the `is_leader` flag, and in which cases it makes sense to use
  - how to import and use third party components
  
- [x] How to come to k8s-under-Juju from the pure-k8s world
  - conceptual changes
  - how to do regular operations in one and other environment
  - expected differences

- [ ] Components
  - concepts, when to use them, when not to
  - how to define and use custom events
  - good practices and recomendations
  - how to offer them to the world (put them under `opslib`)

- [ ] General "events" information
  - concepts, how to hook
  - different event types
  - what is to "defer" an event, when to use it, when not to

- [ ] Testing harness
  - concepts
  - provided functionality
  - common traps and how to avoid them

**Comment by ntorba** [comment]
Hey @facundobatista! Do these docs, or just some of them, live anywhere yet?

**Comment by jnsgruk** [comment]
Hoping to address all of this in an upcoming docs release late this week/early next week!

**Comment by jnsgruk** [comment]
There are comprehensive developer docs now live at https://juju.is/docs/sdk. Additionally, I created #511 which adds a slightly more verbose header to the ReadTheDocs entry, and points people at the developer docs.
