### ISSUE TITLE
Get container utility for easy pod_spec updates

### ISSUE THREAD

**Issue by justinmclark** [canonical/operator#397]
I saw this helper function in the Mattermost charm while working on another charm and I think this could possibly fit into the operator framework itself (most likely in the `ops.model.Pod` class)

Here's the snippet from the Mattermost charm [1]:
```python
def get_container(pod_spec, container_name):
    """Find and return the first container in pod_spec whose name is
    container_name, otherwise return None."""
    for container in pod_spec['containers']:
        if container['name'] == container_name:
            return container
    raise ValueError("Unable to find container named '{}' in pod spec".format(container_name))
```
[1] https://git.launchpad.net/~mattermost-charmers/charm-k8s-mattermost/tree/src/charm.py#n74

**Comment by facundobatista** [comment]
This is interesting to have. For sure we need to revisit this when we have a more object-like interface to PodSpecs, but we can have it before too.

At least we need to address two details:

- Not all versions of pod specs have `containers`

- Be more explicit about having only one container with that name (that is, exploding if there are 0 or >1).

**Comment by jnsgruk** [comment]
@jameinel Is this a close "won't fix" issue now sidecar charms are implemented?

**Comment by facundobatista** [comment]
Yes, exactly, we took a different path.
