### ISSUE TITLE
Allow way for harness to trigger upgrade-charm event

### ISSUE THREAD

**Issue by hloeung** [canonical/operator#402]
Hi,

There doesn't seem to be a way to trigger upgrade-charm events (also cannot find examples of it in operator/test/test_testing.py). For example, for config-change:

```
harness = Harness(DiscourseCharm)
harness.begin()
harness.update_config(config)
```

For leader-elected:

```
harness = Harness(DiscourseCharm)
harness.begin()
harness.set_leader(True)
```

Maybe something like this for upgrade-charm?

```
harness = Harness(DiscourseCharm)
harness.begin()
harness.upgrade_charm(True)
```

It may not be useful for K8s charms as they mostly just call something to assemble the pod spec and apply it but for non-K8s charms, it would be useful to test the functions or methods called for upgrade-charm without having to use harness.disable_hooks() then calling each of these functions/methods.

**Comment by jameinel** [comment]
You can always do:
```
harness.charm.on.upgrade_charm.emit()
```
The main reason for functions like "update_config" is that you want to
mutate the model, and let the charm know about it.

I would be happy to have us expose something like this, but given there
isn't much 'change to the model' what would the "True" represent in your
above use case?

John
=:->

**Comment by hloeung** [comment]
Ah, ```harness.charm.on.upgrade_charm.emit()``` seems to be just what I'm looking for, thanks.
