### ISSUE TITLE
Have a quick "what you should look for" as packaging docs

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#407]
Right now loading up:
https://ops.rtfd.io/

Takes you to a page that has a lot of detail for reference material, but the very first line is just:
```
ops package

The Operator Framework.
```

That feels like a good point to flesh out a little bit as it is a welcome page that we point people to.

I don't think it needs to be terribly verbose, and we can probably take some copy from some of the other documentation and put it there.

It just feels like a miss whenever I tell people about it and load that page, and see that it dumps you straight into a ops.charm.module ActionEvent, which is not where you'd want to start any story.

**Comment by jnsgruk** [comment]
Once the new SDK docs are up, we can take some content from there, and also link out to some more wholesome docs. Should be able to get this sorted by early next week.
