### ISSUE TITLE
Testing Harness to provide a way to check if an event was deferred

### ISSUE THREAD

**Issue by facundobatista** [canonical/operator#433]
Maybe we could do something generic like "recording all events triggered", that will be useful for this "checking if deferred" but also for other stuff we would want to check in the future regarding events.

**Comment by benhoyt** [comment]
I think in general a charm shouldn't be testing or need to know whether an event is deferred or not, or do something different depending on whether an event was deferred -- that seems like a code smell. In addition, we are seriously [considering deprecating defer](https://github.com/canonical/operator/issues/966) or at least recommending against its use in general, as it causes so many issues. Closing this.
