### ISSUE TITLE
Expose "public-address" (its not the same as ingress-address)

### ISSUE THREAD

**Issue by erik78se** [canonical/operator#449]
I would like to have the "public-address" be exposed in the operator framework.

There is a discussion about this on discourse:
https://discourse.charmhub.io/t/how-to-get-dns-address-from-aws-machine-in-my-iaas-charm-code/3789/6

**Comment by benhoyt** [comment]
Juju does have a public address for machines, but Juju doesn't currently expose it. Could re-open this as a Juju bug if this is still an issue.
