### ISSUE TITLE
is_doomed()

### ISSUE THREAD

**Issue by stub42** [canonical/operator#450]
It is useful in a number of situations to know that the current unit is being torn down. This is exposed by charmhelpers as `charmhelpers.core.hookenv.is_doomed()`. Current implementation uses `goal-state`, but I suspect Juju now provides this information through the environment.

Depending on how this is exposed, this could be implemented as model.is_doomed() or relation.is_doomed() in the Operator Framework. `doomed` is the term we used to use for some internal projects (for transactions that were destined to be rolled back), but seems suitable terminology here too, but alternative naming should be used if it better expresses the meaning.

**Comment by stub42** [comment]
(I suspect this is most useful for non-k8s workloads)

**Comment by benhoyt** [comment]
We have added `RelationDepartedEvent.departing_unit_name` (from `JUJU_DEPARTING_UNIT`), and you can check if that's equal to the current unit name (`self.unit.name`) to determine this. That's probably enough for now.
