### ISSUE TITLE
event.unit is None when using update_relation_data

### ISSUE THREAD

**Issue by dstathis** [canonical/operator#452]
It looks like when you try to set relation data in the application bucket, the remote unit is not set in the hook call.

```
PYTHONPATH=src python -m unittest -v tests.test_charm.TestCharm.test_alerting_config_is_updated_by_alertmanager_relation
test_alerting_config_is_updated_by_alertmanager_relation (tests.test_charm.TestCharm) ... Got null event unit on alertmanager changed
FAIL
```

My understanding is this should not be the case.

**Comment by chipaca** [comment]
from the [documentation of RelationEvent](https://ops.readthedocs.io/en/latest/#ops.charm.RelationEvent),

>     Attributes:
>        unit: The remote unit that has triggered this event. This may be `None` if the relation event was triggered as an `Application` level event

isn't this exactly what you are describing?

**Comment by jameinel** [comment]
Application data changes have no associated Unit data with them (eg
event.relation.data[event.unit] doesn't make sense because that data isn't
changing).
Thus we intentionally don't include the unit as part of the event.

**Comment by dstathis** [comment]
Yes I had misunderstood how this works
