### ISSUE TITLE
Facility to test changes when related units depart

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#454]
## Use Case

A charm author would like to test the behaviour of his/her charm when a related unit departs. The related unit may be a peer relation or a relation with another charm.

## Notes

1. At present the Operator Framework provides a method `add_relation_unit` but no corresponding method to remove a unit.
2. Is it better to add a `remove_relation_unit` method or trigger a `relation_departed` event after setting appropriate event data (what?) ?

**Comment by chipaca** [comment]
I hadn't noticed but we already have #445 for this one :-) thanks for the report though, and i agree
