### ISSUE TITLE
remove python 3.5

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#471]
Pypi is issuing warnings that they will no longer support python 3.5 as of Jan 2021. We always discussed that we wanted to get 1.0 out supporting Xenial, but post 1.0 we could move beyond it and drop support for 3.5. I think we're at that point now.

**Comment by jnsgruk** [comment]
This is definitely coming in the future, there is some more discussion on this in the linked PR (#607). I'm going to close this for now, but it's an issue that will be reopened and addressed in the future.
