### ISSUE TITLE
Ports not visible in `juju status` with pebble approach

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#487]
If you Deploy a charm written using the new pebble approach (e.g. https://github.com/benhoyt/snappass-test), the port(s) are not visible in `juju status`. For example:
```
$ juju status
Model     Controller           Cloud/Region        Version  SLA          Timestamp
snappass  microk8s-localhost2  microk8s/localhost  2.9-rc7  unsupported  07:03:51+13:00

App       Version  Status  Scale  Charm          Store  Channel  Rev  OS      Address  Message
snappass           active      1  snappass-test  local             0  ubuntu           snappass started

Unit         Workload  Agent  Address      Ports  Message
snappass/0*  active    idle   10.1.147.69         snappass started
```

**Comment by benhoyt** [comment]
I'll dig into this further, but from talking to the team it sounds like this is essentially a bug in the charm -- it should be calling open-port to signal to Juju which ports are open (this is distinct from `juju expose`). I'll see if I can update the test charm to do that.

**Comment by jnsgruk** [comment]
So this was handled automatically when we were using `pod.set_spec` it seems.This was possible because the ports required were specified in the pod. 

Do we want to be asking users to poke network ports open manually in their charm code? And if so, where is the "right place" for that? In the `install` hook or elsewhere?

There might be a way to handle this automatically by inspecting the ports that are exposed using the "EXPOSE" directive in the Dockerfiles?

**Comment by jnsgruk** [comment]
Further to my last, it seems if you run `open-port` in the context of a k8s charm it gets sad:

```
juju run --unit snappass-test/0 '/var/lib/juju/tools/unit-snappass-test-0/open-port 5000/TCP'
```

Results in the following in `juju debug-log`:

```
unit-snappass-test-0: 14:50:20 ERROR juju.worker.uniter.context cannot apply changes: cannot retrieve ports for unit "snappass-test/0": unit "snappass-test/0" is not assigned to a machine
unit-snappass-test-0: 14:50:20 ERROR juju.worker.uniter resolver loop error: executing operation "run action 2" for snappass-test/0: action "juju-run" (via unknown/invalid hook handler) failed: cannot apply changes: cannot retrieve ports for unit "snappass-test/0": unit "snappass-test/0" is not assigned to a machine
unit-snappass-test-0: 14:50:20 INFO juju.worker.uniter unit "snappass-test/0" shutting down: executing operation "run action 2" for snappass-test/0: action "juju-run" (via unknown/invalid hook handler) failed: cannot apply changes: cannot retrieve ports for unit "snappass-test/0": unit "snappass-test/0" is not assigned to a machine
```

**Comment by jameinel** [comment]
This should probably be moved to a bug in Juju vs operator framework:
https://bugs.launchpad.net/juju/+bug/1920960

**Comment by benhoyt** [comment]
Thanks @jameinel. I'll close this, as this is a Juju issue, not a Python Operator Framework one.
