### ISSUE TITLE
Method to reload services using pebble

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator#491]
Currently to update a service managed via Pebble using the Operator Framework, you do `container.stop('srv1'); container.start('srv1')`. This will mean an unnecessary service interruption if the service can be reloaded rather than requiring a restart.

**Comment by benhoyt** [comment]
Thanks. Agreed! This is definitely on my Pebble to-do list for the near future.

**Comment by rbarry82** [comment]
I like this idea in principle, but I'm concerned that it's too workload-specific to abstract. Will a `SIGHUP` do it? Some API endpoint? Does that need to be authenticated? What if the service doesn't support hot reloading at all?

There are a lot of assumptions baked into this which authors would need to think about to make it reliable, and at that point, it's not too much more work for them to implement the logic themselves (if their application) supports it

**Comment by jnsgruk** [comment]
Closing this for now, the requirement for the fundamental handling of different signals is being tracked in the Pebble repo, and there is a spec in progress. Please see https://github.com/canonical/pebble/issues/16
