### ISSUE TITLE
add_layer should not accept a bare "True" at the end

### ISSUE THREAD

**Issue by niemeyer** [canonical/operator#495]
The add_layer method currently accepts combined as a positional parameter, so there's code in use that does `add_layer(..., True)`, and that's unreadable.

That should really be an enforced keyword parameter.

**Comment by benhoyt** [comment]
I noticed this too, and thought it didn't read very well. Agreed! Fixing in https://github.com/canonical/operator/pull/496

**Comment by jnsgruk** [comment]
@jameinel This is now fixed, per comment above - not sure why it didn't auto close.

**Comment by jameinel** [comment]
I believe because it was stated as "per blah" and not "Fixes: blah"
