### ISSUE TITLE
CharmMeta class needs to be updated for Metadata v2

### ISSUE THREAD

**Issue by jnsgruk** [canonical/operator#498]
The `CharmMeta` class currently only represents the v1 Metadata spec - it needs to be updated to support metadata v2: https://discourse.charmhub.io/t/charm-metadata-v2/3674

**Comment by jameinel** [comment]
We will also need CharmMeta to be reading in `manifest.yaml` along with the other files.

**Comment by benhoyt** [comment]
We've added `containers` for Pebble, but not the other fields in metadata v2, nor `manifest.yaml` -- should still do this for completeness.

**Comment by benhoyt** [comment]
This is still worth doing for completeness (though presumably not high priority given lack of people asking for this). I've added the 24.04 label and we'll see if we can get to it next cycle.
