### ISSUE TITLE
autodetection of storage incorrect for sidecar charms

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#506]
See https://bugs.launchpad.net/juju/+bug/1923843

The current logic to see if we should use stage-get/state-set instead of a local sqlite database is:
```python
def _should_use_controller_storage(db_path: Path, meta: ops.charm.CharmMeta) -> bool:
    """Figure out whether we want to use controller storage or not."""
    # if you've previously used local state, carry on using that
    if db_path.exists():
        logger.debug("Using local storage: %s already exists", db_path)
        return False

    # if you're not in k8s you don't need controller storage
    if 'kubernetes' not in meta.series:
        logger.debug("Using local storage: not a kubernetes charm")
        return False

    # are we in a new enough Juju?
    cur_version = JujuVersion.from_environ()

    if cur_version.has_controller_storage():
        logger.debug("Using controller storage: JUJU_VERSION=%s", cur_version)
        return True
    else:
        logger.debug("Using local storage: JUJU_VERSION=%s", cur_version)
        return False
```

However, 'kubernetes' is not in meta.series for sidecar charms.

**Comment by jameinel** [comment]
related to issue #498

**Comment by jameinel** [comment]
Can be worked around in existing charms with:
`main(Charm, use_juju_for_storage=True)`

**Comment by petevg** [comment]
Darn it. This one is not the easy fix I initially thought it was going to be. (I hadn't loaded all the necessary decisions into memory when we were talking about this before.)

For charms using metadata v2, the information we need isn't actually in the metadata.yaml. It lives in the manifest.yaml. Juju gets that info at deploy time by making a query to CharmHub. It would not be correct to have the Operator Framework make a similar query. And it would also not be correct to parse the manifest.yaml -- it's not a "run time" piece of the plan.

To a certain extent, what the operator framework is doing here is not correct, period. I don't think that we want code at this level to know or care about the nature of the storage available in a cloud. The framework should just use storage, which Juju should provide. Of course, not all the pieces are in place for that (and yes, I was in some of the conversations where we decided not to connect those pieces -- I bear some responsibility for this particular annoyance).

I need to do some thinking, possibly some spec writing, and also bounce some ideas off of @hmlanigan and/or @SimonRichardson. Will drop in further notes here as I work on this ...

**Comment by rwcarlsen** [comment]
@pengale - what's the state of the situation around this - any updates?

**Comment by pengale** [comment]
@rwcarlsen this got stalled out in the discussion around whether or not to default to using controller storage in sidecar charms.

I think that the consensus is that we should not use controller side storage by default, and that charms that want controller side storage should say so explicitly. 

We can probably close this ticket as WONTFIX.
