### ISSUE TITLE
[RFE] Extend CharmBase to allow classes to insert config options and actions

### ISSUE THREAD

**Issue by phvalguima** [canonical/operator#510]
I am currently working on a set of charms that manages Java applications. That means each charm has a subset of configs and methods that essentially does the same thing. 

A practical example, I have to manage JMX exporter to send metrics to prometheus for all those charms. Ends up that all the charms have the same set of configs like "jmx_port". I am setting the logic into a common "JavaCharmBase" class but would be easier to also have JavaCharmBase pointing to its own config.yaml and one single definition of "jmx_port" option.

Once I run the "charmcraft build" command, that would assemble all the configs and actions of the CharmBase children classes and render the final config.yaml / actions.yaml of the charm.

**Comment by rbarry82** [comment]
This seems like an excellent use case for a library.

A couple of comments:

* Charmcraft is a [different project](https://github.com/canonical/charmcraft). By the time it reaches the Operator Framework invocation, all of this has already been set. While we  _could_ dynamically assemble all of this at runtime, it's not the best option unless there's a really strong push for a plugin system
* Writing a charm library which has a couple of pieces (`JavaCharmBase` which inherits from `CharmBase`, `JavaCharmMeta` which inherits from `CharmMeta` to set the configuration values you want). Notably, these values will not be available from `juju set-config` unless `charmcraft` handles the assembly of the Charm so Juju knows about it when you deploy, but if they're relatively static, a library is great.

I'm happy to help forward this to the right place or give guidance on writing a library
