### ISSUE TITLE
AttributeError: 'property' object has no attribute 'Layer' 

### ISSUE THREAD

**Issue by eminaktas** [canonical/operator#517]
Hello,

With the new release of the package (1.2.0) below error started while deploying the charm. I am not sure what causes this error but this happens at the very beginning of the code that importing the from `ops.charm import CharmBase`

```error
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install Traceback (most recent call last):
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "./src/charm.py", line 5, in <module>
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     from ops.charm import CharmBase
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/var/lib/juju/agents/unit-charm--0/charm/venv/ops/__init__.py", line 43, in <module>
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     from . import charm  # noqa: F401 (imported but unused)
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/var/lib/juju/agents/unit-charm--0/charm/venv/ops/charm.py", line 22, in <module>
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     from ops import model
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/var/lib/juju/agents/unit-charm--0/charm/venv/ops/model.py", line 1017, in <module>
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     class Container:
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/var/lib/juju/agents/unit-charm--0/charm/venv/ops/model.py", line 1053, in Container
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     combine: bool = False):
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     dict(self.__dict__), parameters, _root=True)
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/usr/lib/python3.5/typing.py", line 512, in __new__
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     self._eval_type(globalns, localns)
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install     eval(self.__forward_code__, globalns, localns),
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install   File "<string>", line 1, in <module>
unit-charm--0: 13:39:07 WARNING unit.charm-/0.install AttributeError: 'property' object has no attribute 'Layer'
unit-charm--0: 13:39:07 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-charm--0: 13:39:07 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-charm--0: 13:39:12 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

Thanks

**Comment by eminaktas** [comment]
Thanks for the quick response. I am using Python 3.5.2 on Ubuntu1604.

Currently, I switched to the older version(ops==1.0.1).

**Comment by jameinel** [comment]
So we do run a regression test on Python 3.5, but our test infrastructure
is 3.5.10. Is it possible for you to test with a newer version of Python?
That feels like the sort of thing they might have fixed upstream.
https://github.com/canonical/operator/runs/2395784540

**Comment by eminaktas** [comment]
The default version of Python for Xenial(Ubuntu1604) is 3.5.2. So, this could be a problem for someone who uses lxd-cloud.

My case: 
```bash
juju bootstrap lxd
juju add-model testing localhost/localhost
juju deploy ./mycharm.charm
```
It automatically downloads the Ubuntu image for Xenial and installs the charm. This case it will fail

**Comment by jameinel** [comment]
Note that we can try to fix this for 3.5.2 and 1.2.1. However, we will be
dropping support for Xenial and Python 3.5 relatively soon. (Probably it
will be dropped in 1.3).
The issue is that even PyPi is dropping support for Python 3.5 (they had
originally claimed they would drop it in Jan 2021). And Pip itself does
have: https://github.com/pypa/pip/pull/9189 which pulls 3.5 support out (in
Dec 2020).

There are several things that we would like to have from python 3.6+ (f
strings, better type annotations, more complete pathlib handling so you
don't have to str(path) on every stdlib call.)

John
=:->

**Comment by eminaktas** [comment]
Unfortunately, We still use Xenial in some cases.  ¯\(°_o)/¯. 
Thanks for the info John.

Emin

**Comment by benhoyt** [comment]
I've attempted a fix in #520. I tried to install Python 3.5.2 locally (with pyenv) but it's not working -- something to do with an incorrect libssl version. I'm not going to mess with it anymore, so let's just remove this type annotation for now. @jameinel can you please review?

**Comment by benhoyt** [comment]
@eminaktas I've fixed this on `master` now, but can't easily test against Python 3.5.2 locally. Can you please point your charm to the latest master commit (https://github.com/canonical/operator/commit/be1fdf0698e33ed2274eb417da5b64f2656239fb) and ensure that this works for you?

**Comment by eminaktas** [comment]
Thanks for the update @benhoyt . I just tested with the latest commit ([be1fdf0](https://github.com/canonical/operator/commit/be1fdf0698e33ed2274eb417da5b64f2656239fb))  it's perfectly working now.

**Comment by benhoyt** [comment]
Good to know, thanks for the report @eminaktas.
