### ISSUE TITLE
Support pebble push testing in harness

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#518]
### Use case

A recent commit pushed much needed support for `ops.harness` based unit testing of sidecar charms. However any method that involves a `pebble.push()` will raise an `NotImplementedError`. It will be useful to have support for `harness` based testing of such methods too, even though it is currently possible to write unit tests by mocking the `push()` method. Mocking may allow checking what is being pushed however testing code downstream of the push call may become more involved, if it depends on the pushed content.

**Comment by jameinel** [comment]
I definitely think we want to include support for testing push/pull. If you have thoughts on what you'd like to write as a test case, it would be good to include that here to guide the work to add support.

**Comment by balbirthomas** [comment]
> If you have thoughts on what you'd like to write as a test case, it would be good to include that here to guide the work to add support.

At present any test that invokes a code flow path that does a `push()` requires a `@patch('ops.testing._TestingPebbleClient.push')` . It would be nice if patching for harness based unit tests is _only required when isolating a charm from the underlying application that it manages_. I would expect if the test harness could actually accept the pushed file and store it in a temporary directory during the life time of the unit test, patching could be obviated. If this is possible then supporting the full pebble API -- `pull()`, `list_files()`, `make_dir()` and `remove_path()` would provide all that is needed for unit testing. `pull()` could for instance return the file contents to the unit test for validation.

**Comment by jameinel** [comment]
Is there any reason why we would actually need to create files on disk and not store things in a in-memory system?
Certainly we could just create a random tmp directory and pretend it matches the paths that are supplied. eg do you want to be testing whether they mkdir -p first?, do you need the testing infrastructure to always set up the directory that the underlying system would already be creating? (/var/lib/mysql probably doesn't exist in your /tmp dir, but it certainly likely does in your workload container)

I can see a case for a virtual PebbleClient that just injests what was passed and assumes it is valid (I don't expect charms to have complex try/catch logic in-case the container isn't what they expect, because they really can't do much but complain to the user that their expectation wasn't met)

It would also be possible to treat it strictly as a mock (it was called with what args). I'm not typically a fan of that style, but in this case it might be a much cleaner representation for push/pull.

**Comment by balbirthomas** [comment]
> Is there any reason why we would actually need to create files on disk and not store things in a in-memory system?

Indeed there is a use case for files on disk. For example Prometheus scrape configuration (a file on disk) is changed and recreated in response to config changed or relation events. I would expect manipulating config files on disk may be a frequent use case for charms. I do appreciate it is possible for the charms to use StoredState to store the current state of every file it changes. Is this a recommended practice ? If so then perhaps it is possible for unit tests to only check that the stored state is updated correctly and not bother testing if stored state is reflected correctly in the file on disk . If we choose to go down this route then we may want to make this recommendation explicit in Ops documentation as it may not be obvious to the Charm writer. 

> Certainly we could just create a random tmp directory and pretend it matches the paths that are supplied. eg do you want to be testing whether they mkdir -p first?, do you need the testing infrastructure to always set up the directory that the underlying system would already be creating? (/var/lib/mysql probably doesn't exist in your /tmp dir, but it certainly likely does in your workload container)

I suppose it may not matter how/where the testing harness pebble backend stores the files, as long as it keeps track of the expected path for each such stored file. The file path is and argument to `push()` so for example pebble testing backend can store files with a data structure that indexes the stored file (whatever its actual location) using the path argument of `push()`. Hence when a pull with the same path argument is invoked the pebble testing backend can return the same file.

**Comment by jameinel** [comment]
So the charms clearly need to manipulate files on disk.
Why does the *test suite* need files on disk?

**Comment by balbirthomas** [comment]
> So the charms clearly need to manipulate files on disk. Why does the *test suite* need files on disk?

If you are asking why test suite needs to implement file storage on disk, it may be that it is probably not necessary and can as well be in memory as long as it can imitate behaviour of Pebble API (`push()` and `pull()`). Although I wonder if there will be a need to unit test file permission and owner ship settings and if so, how this can be done with in memory representation of files. For example MongoDB is very stringent about the permission and ownership of the key file, when authentication is enabled. It insists that this key file is owned by user/group "mongodb" and that the permissions are read/write by owner only. If this condition is violated MongoDB fails to start. Setting owner, group and permissions is part of the Pebble `push()` API. The underlying question is if harness should allow unit testing all the functionality exposed by the Operator Framework API, without the need to patch the Operator Framework API itself. I can see there being divergent views on this. My own inclination is that making harness feature complete in this manner will be a more pleasant developer experience.  Thoughts ?

**Comment by jameinel** [comment]
In which case you really need to do it only in memory, as there may not be
a 'mongod' user on your host system, but again it would likely exist inside
the container image.

I certainly wouldn't want people to have to patch the functionality to do
basic testing. The question is more what leads to good, maintainable tests
such that we can guide people towards high quality charms.
