### ISSUE TITLE
allow stopping service by ServiceInfo

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#529]
Currently, the `Container.stop()` method only accepts strings:
https://github.com/canonical/operator/blob/ab6d06af6f0956903bbf6b25acdbcefedc6305c6/ops/model.py#L1048

It would be nice if it could also accept a `ServiceInfo`:
```python
def stop(self, *service_names: Union[str, 'pebble.ServiceInfo']):
```

**Comment by benhoyt** [comment]
Hi @sed-i -- thanks for the report. Can you please give an example in context of where this would be useful?

**Comment by sed-i** [comment]
I was about to comment with
```python
container.stop(container.get_services())
```
but I see now that `get_services()` returns `ServiceInfoMapping`, not `List[ServiceInfo]` so I could do
```python
container.stop(*container.get_services().keys())
```
