### ISSUE TITLE
Ability to detect if the charm is 'trusted'/has elevated permissions

### ISSUE THREAD

**Issue by jnsgruk** [canonical/operator#532]
It would be useful for the framework to detect if the administrator has "trusted" the charm with `juju trust`. 

At the moment I'm detecting this by trying something that shouldn't work without it, then catching the exception:

```python
try:
    auth_api.list_cluster_role()
except kubernetes.client.exceptions.ApiException as e:
    if e.status == 403:
        # If we can't read a cluster role, we don't have enough permissions
        self.unit.status = BlockedStatus("Run juju trust on this application to continue")
        return False
    else:
        raise e
```

**Comment by benhoyt** [comment]
Yeah, it looks like there's no easy way to do this right now. A `config-changed` hook *is* fired when you execute `juju trust`:

```
$ juju trust snappass-test --scope=cluster
$ juju show-status-log snappass-test/0
14 May 2021 17:26:26+12:00  juju-unit  executing    running config-changed hook
14 May 2021 17:26:26+12:00  juju-unit  idle    
```

However, it seems that `config-get` doesn't return the `trust` value on CAAS models:

```
$ juju run --unit snappass-test/0 "config-get trust"
$ juju run --unit snappass-test/0 "config-get"
{}
```

The "trust" value is stored in Juju "application config", for example when you type `juju config` on the client you can see it under "application-config":

```
$ juju config snappass-test
application: snappass-test
application-config:
  ...
  trust:
    default: false
    description: Does this application have access to trusted credentials
    source: user
    type: bool
    value: true
charm: snappass-test
settings: {}
```

But there's no way to get this using `config-get` from the charm. I've opened [LP 1928610](https://bugs.launchpad.net/juju/+bug/1928610) on the Juju side to add a `config-get --app` mode or similar to return those keys so we can access them in the charm. (And then you'd probably do something like `model.app_config.get('trust')` to check it.)

**Comment by jnsgruk** [comment]
Nice, that'd do it. Thanks Ben!

**Comment by benhoyt** [comment]
WIP spec: https://docs.google.com/document/d/1QeKJ8KjbBLTMkDBxN51NSw9iCpFjddpe1nwD4zFKFWA/edit

**Comment by benhoyt** [comment]
Would be worth seeing what `credential-get` returns on Kubernetes, as that might be a simpler workaround if it does.

**Comment by benhoyt** [comment]
@jnsgruk What are your current thoughts on this? I think this is interesting but probably not particularly high priority and perhaps doesn't add enough value to warrant adding new hook tools etc. Charms that need this can have a simple helper to look for the 403 or whatever from cloud/K8s APIs.

**Comment by jnsgruk** [comment]
I don't think it's super high-prio for your team right now; `trust` is going to need a bit of a rethink as to how it's modelled anyway.

Right now it lives in a sort of weird "application config" - which needs to go in Juju 4. The only other options that live there currently are PodSpec charm options which is deprecated in 4.0 anyway.

I don't know if @manadart has any thoughts on where else it might live, but either way I don't think there is much point in the `ops` team ticking this off just yet.

**Comment by benhoyt** [comment]
Let's close this for now then. As discussed, now that we have open-port on K8s trust comes up less often, and even when it's needed, the 3 lines of code to catch the API exception are not hard to add, whereas the Juju modelling issues are a lot harder to solve.
