### ISSUE TITLE
decorator for skipping function when called by non-leader

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#533]
We have a growing list of functions that only apply to leaders.
It could be handy to have an ops-provided decorator to skip functions for non-leaders, for example:

```python
def leader_only(func):
    @functools.wraps(func)
    def wrapped(self, *args, **kwargs):
        if not self.unit.is_leader():
            return
        func(*args, **kwargs)

    return wrapped
```

**Comment by rbarry82** [comment]
A decorator for two lines of code is a little excessive, especially if there are other tasks which authors want to accomplish even if they are not the leader (like reading information out of a data bag instead of setting it so they can configure themselves somehow)
