### ISSUE TITLE
pod-spec-set some Juju environment variables

### ISSUE THREAD

**Issue by hloeung** [canonical/operator#541]
Hi,

With the switch to sidecar charming and pebble, we no longer have control of the pod specifications. Any chance operator could expose the following environment variables?

    'JUJU_NODE_NAME': {'field': {'api-version': 'v1', 'path': 'spec.nodeName'}},
    'JUJU_POD_NAME': {'field': {'api-version': 'v1', 'path': 'metadata.name'}},
    'JUJU_POD_NAMESPACE': {'field': {'api-version': 'v1', 'path': 'metadata.namespace'}},
    'JUJU_POD_IP': {'field': {'api-version': 'v1', 'path': 'status.podIP'}},
    'JUJU_POD_SERVICE_ACCOUNT': {'field': {'api-version': 'v1', 'path': 'spec.serviceAccountName'}},

Also reported against Juju, https://bugs.launchpad.net/juju/+bug/1894782 but I think it might be one for Operator.

**Comment by jnsgruk** [comment]
Hey :) I agree it would be useful to have access to some of this data, though a lot of it can be derived from existing Operator Framework constructs for now:

In general:

- `JUJU_POD_NAME` == `self.unit.name`
- `JUJU_POD_NAMESPACE` == `self.model.name`
- `JUJU_POD_SERVICE_ACCOUNT` == `self.app.name`

There is another issue (#534) about an IP address getter - for now you can use `subprocess` to get the IP of the pod:

```python
import subprocess
ip = subprocess.check_output(["unit-get", "private-address"]).decode().strip()
```

Additionally, if the charm has a peer relation defined, you can get the IP of the pod using `[get_binding()](https://ops.readthedocs.io/en/latest/#ops.model.Model.get_binding)` in the Operator Framework to inspect the relation network binding and get the address.

The only one I don't think I know how to work out for now is the `JUJU_NODE_NAME`. Hope this helps you getting started in the meantime!

**Comment by hloeung** [comment]
@jnsgruk, I was looking into why I used the k8s special variables rather than just those available via the Operator Framework and it was due to prevent pods being redeployed - pod-spec-set content-cache/11, redeploy, pod-spec-set content-cache/12, redeploy, ...

Obviously this isn't an issue now with sidecar and pebble where charms do not need to call pod-spec-set directly so will try use those as suggested.

**Comment by rbarry82** [comment]
@hloeung still relevant?

**Comment by hloeung** [comment]
Probably not, will reopen if so.
