### ISSUE TITLE
add list of preconditions to event docstrings

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#543]
It would be valuable to document what each event guarantees.
For example, "RelationJoinedEvent" guarantees (i.e. has a precondition) that peer buckets are visible (cf. #542).
https://github.com/canonical/operator/blob/37e3399f2ab786cde1199af591c18910ad234e39/ops/charm.py#L352-L362

**Comment by balbirthomas** [comment]
> It would be valuable to document what each event guarantees.
> For example, "RelationJoinedEvent" guarantees (i.e. has a precondition) that peer buckets are visible (cf. #542).

I wonder if this should be in the docstring of `get_binding()` also. The precondition of `get_binding()` network for a peer relation or any relation is that the relation joined event for that particular relation and unit has happened.  It may be fair to add a cross reference in `RelationJoinedEvent` saying once this event has occured `get_binding()` will return a valid address.

**Comment by sed-i** [comment]
_Enumerating_ entry pathways is also useful, for example:
- RelationJoined:
  1. as part of the startup sequence (may appear multiple times);
  2. re-entry after defer().
- RelationChanged:
  1. immediately after a newly joint unit receives RelationJoined, all of its peers receive RelationChanged.
  2. when relation data bucket is modified.
  3. re-entry after defer().
- PebbleReady: 
  1. as part of the startup sequence; 
  2. re-entry after defer().

**Comment by benhoyt** [comment]
I think we can probably improve our docs here in places, however, I think it's probably better that the details are described in the Juju docs rather than in the ops API docs. We could even shorten our ops docs in some cases, and perhaps link to the relevant Juju doc.

**Comment by benhoyt** [comment]
@tmihoc You had some thoughts about making Juju event docs clearer -- what was your concrete plan for that again?

**Comment by tmihoc** [comment]
> I think we can probably improve our docs here in places, however, I think it's probably better that the details are described in the Juju docs rather than in the ops API docs. We could even shorten our ops docs in some cases, and perhaps link to the relevant Juju doc.

As we've already discussed, I agree -- the source of truth for how Juju hooks or hook tools behave is Juju, so we should define them well in Juju docs and then have Ops constructs that build on them link to them.

**Comment by benhoyt** [comment]
It seems like there's general agreement this belongs in the Juju docs (not Ops), and there's efforts underway to improve those. Closing here.
