### ISSUE TITLE
More runtime checks should be build-time checks

### ISSUE THREAD

**Issue by knkski** [canonical/operator#546]
Followup from #545. That is a pretty easy bug to fix, by allowing arguments with a `kind` of `VAR_POSITIONAL`. However, that brings up the question of: If we're doing this kind of deep introspection, why not do it inside of `charmcraft build` instead of at runtime (or both)? I would much rather have `charmcraft build` catch these kinds of errors and yell at me than to have to go through the process of deploying it and seeing where it falls down.

**Comment by rbarry82** [comment]
I agree in principle, though that sort of check should be in `charmcraft` instead. Since the OF is runtime rather than build time, this sort of static analysis isn't appropriate here outside of #545
