### ISSUE TITLE
Default 'debug-code' should include hooks

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#554]
Right now `juju debug-code myapp` defaults to `--at=all` which implies `JUJU_DEBUG_AT=all`.

Operator Framework currently interprets `all` to mean "all explicit breakpoints". However you have to do `juju debug-code --at=hook myapp` if you want to have operator framework stop at the event handler for a given hook.

I think this is counter intuitive for charm developers. It means you have to edit your charm in order to default drop into a debugger. (IOW going to an arbitrary OF charm and running `juju debug-code app` does nothing and never drops into a debugger.)

With `juju debug-hooks app` you default drop into a shell on any hook that exists, and it seems like that would be the right behavior for `juju debug-code app`.

**Comment by jameinel** [comment]
See https://bugs.launchpad.net/juju/+bug/1932248 for a case of user confusion.

**Comment by jameinel** [comment]
@facundobatista I'd like your thoughts on this, as you did the original implementation. I want to make sure I'm not overlooking something that you were thinking about.

**Comment by facundobatista** [comment]
IIRC, the idea was that dropping into a debug terminal for *every* hook would be annoying. 

I'm not opposed to this change, specially taking in consideration that is totally fine to change behaviours after we get real usage feedback, but please try in real life if the default behaviour of stopping on ALL hooks won't be a mess.

All that said, note that the user is left in the debug prompt **on the beginning of the hook's execution**, not after it was executed.
