### ISSUE TITLE
Container.start() silently accepts no arguments and does nothing

### ISSUE THREAD

**Issue by facundofc** [canonical/operator#555]
`Container.start()` takes a variable number of strings as arguments, each specifying a service to be started. The issue is that it also accepts zero arguments without complain, even though it clearly indicates a mistake on the user.

I believe it should raise some sort of exception in the case of no arguments.

Applying this patch to current master (`18477647`) demonstrates the issue:

```diff
diff --git a/test/test_model.py b/test/test_model.py
index ed64add..564681a 100755
--- a/test/test_model.py
+++ b/test/test_model.py
@@ -824,6 +824,10 @@ containers:
             ('start', ('foo', 'bar')),
         ])
 
+    def test_start_no_argument(self):
+        with self.assertRaises(Exception):
+            self.container.start()
+
     def test_stop(self):
         self.container.stop('foo')
         self.container.stop('foo', 'bar')
```

**Comment by benhoyt** [comment]
Fixed in #556 -- thanks for the report!
