### ISSUE TITLE
Enforce usage of charm libraries when provided

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#559]
# Introduction

Charm libraries are usually used to manage relations with charms. Such charm libraries provide clean separation of concerns between charms and the libraries. Charms manage their applications and charm libraries manage relations with other charms. The two of course collaborate and are closely coupled. There are two sides to managing any charm relation. A provider side and a consumer side. Charm libraries may be expected to implement both parts for example using the [ops.relation](https://ops.readthedocs.io/en/latest/#module-ops.relation) module. A present the use of charm libraries, *when provided* is not enforced. This may be problematic for reasons listed below.

Suppose charm X has a charm Provider/Consumer charm library for managing relation R. If charm Y chooses to bypass the "Consumer" provided by the library and instead interacts with X over R directly then

1. It is possible that some workflow/logic encapsulated in the Provider of charm X's library may need to be duplicated in charm X itself.
2. Any conventions regarding interactions over relations established between Provider and Consumer of charm X's library may be violated.

There could be other potential problems that are had to anticipate and detail at present. 

The availability of Provider/Consumer modules in the operator framework makes it easy to enforce the use of the interface provided by the library *only in the case* when such a library is provided. For example such a check may be implemented in `ProviderBase`. In effect this amounts to the design choice that when a charm library is provided the relation interface is no longer a public interface but a private one encapsulated within the interactions of the "Producer" and "Consumer". This encapsulation will allow charm libraries to evolve without breaking any public interfaces.

**Comment by mmanciop** [comment]
In case of reactive charms implemented in `bash`, we do not really get to use Charm Libraries right?

**Comment by balbirthomas** [comment]
> In case of reactive charms implemented in `bash`, we do not really get to use Charm Libraries right?

If that is the case, doesn't that mean that at least the Consumer charm libraries should not implement any logic that *critical* to managing the relation ?

**Comment by dstathis** [comment]
I don't really see how we could enforce this. If someone writes code that knows how to speak over the relation interface, I don't think there would be any way for the provider to know the difference.

**Comment by balbirthomas** [comment]
> I don't really see how we could enforce this. If someone writes code that knows how to speak over the relation interface, I don't think there would be any way for the provider to know the difference.

If anyone wants to "reverse engineer" the relation interface and write an alternative Consumer that behaves exactly as the consumer in the charm library, that effectively amounts to the library being "enforced". Enforcing can even be a documented convention. If desired there are a range of programmatic options, from trivial and hence easily bypassed to cryptographically secure. An easily bypassed trivial solution is to include an undocumented token and corresponding check. A secure solution is to use public key encryption. There is no need to reinvent the wheel on cryptographically secure solutions, for example this is what browsers do when authenticating users and websites. These more secure solutions need not and perhaps should not be the first step to enforcement. However the use case for charms authenticating each other is bound to crop up when charmed ecosystems begin to pervade very high security systems.

**Comment by mmanciop** [comment]
I am not sure it makes sense to solve this with technology. I think should document clearly that, [borrowing the terminology of Git CLI](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain), the relation data bags are _porcelain_, and the libraries are plumbing.

**Comment by balbirthomas** [comment]
Documenting relation data may be one way of enforcing them. But a data structure can not represent any dynamic behaviour implicit in a relation. If we ever want to build relations between charms has well defined sequential behaviour, such information can not be captured in a static structure. This is another reason IMHO relation data should not be the public interface once we have charm libraries.

**Comment by jnsgruk** [comment]
Following up on this after a discussion with @balbirthomas this morning...

I think I'm on the side of not enforcing this. We should absolutely encourage our community of charmers to use the provided charm libraries where they exist, and perhaps even suggest/contribute changes to such libraries if there are features missing that they require, but no doubt there will be edge cases for which library authors do not wish to modify their libraries.

Charm libraries are ultimately provided by charm authors to *ease* the integration of their charm with others, but if the library doesn't/won't fit, then there is no reason why developers shouldn't roll their own -- we don't provide any guarantees either way. I agree this may be more fragile, but ultimately it is a valid choice for the developer to make.

It'd be great if we could encourage a pattern of including good documentation of relation interfaces, how they behave, which data is passed under which circumstances, etc. with our charms.

**Comment by balbirthomas** [comment]
I am closing this ticket since I stand convinced of @jnsgruk more balanced view point on this matter, and thereby withdraw my request to enforce charm libraries. I appreciate that it is acknowledged that a charm developer who refuses to use a charm library when one is provided may risk introducing fragility into the system, and they do so at their own peril. I agree and anticipate that these matters would be best solved by building a sense of collaboration and community around the charms rather than strict enforcement.
