### ISSUE TITLE
Incomplete life cycle events for restarted pods on Kubernetes

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#562]
## Introduction

**Note**: This is probably a known issue or a designed feature and perhaps more relevant to Juju than the Operator Framework. Hence the purpose of this ticket is to highlight how this issue affects the usability of the Operator Framework and the challenges it imposes upon charm writers.

Suppose Charm X is related to Charm Y. Suppose further that each unit of Charm Y needs to set some data (say its own accessible unit bind address) on the relation joined event with Charm X. Now suppose a unit (Kubernetes pod) of Charm Y is restarted for whatever reason (even a user initiated `kubectl delete`) then the new unit of Charm Y does not get a relation joined event, and hence does not have the opportunity to set the required relation data. This problem is compounded by the fact that the new unit does not share the same attributes as the old (terminated) one (for example the bind address is different). It would be natural for a charm writer to expect that the life cycle of a newly started unit is akin to that an additional unit added (say using `juju scale-application). Additional units added using the Juju command line do get all the lifecycle events, hence the behaviour of restarted units is counter intuitive IMHO from the charm writer's perspective. It would have made sense to not raise all lifecycle events if all attributes and state from the old unit were transferred to the new unit, but clearly this is not the case.

Of course one could implement a workaround, for instance, by having units of Charm Y set the requisite data in the pebble ready event. For the specific example cited this may work, provided the pebble ready event guarantees that network setup is complete when pebble ready fires (does it ?). But more fundamentally this may lead to questionable practice when trying to write charm libraries. Suppose Charm X provides a **consumer** charm library to make it easy (automatically) for units of Charm Y to set the relevant relation data. Such a library would require that the Consumer of X is made aware of the pebble service of Y for which Consumer of X must observe pebble ready events. Is this a good idea or even acceptable ?

**Comment by balbirthomas** [comment]
ATTN: @jameinel @jnsgruk @rbarry82 @mmanciop

**Comment by rbarry82** [comment]
Indeed, this is more Juju focused than OF, since relation handling is passed into OF from there. `PebbleReady` is not quite the right place, since the Pebble services are started as a sidecar to the charm (which has the IP address, is the workload charm, etc).

The charm does get `start`, `config_changed`, `upgrade_charm`, `leader_elected` (possibly). There was a recent issue on Juju which [handled part of this use case](https://github.com/juju/juju/pull/13037), but there is clearly still a difference in behavior. I'd suggest opening an issue on Juju for `CaasApplicationProvisioner` to also send these events when it sees that it's restarting a unit because it stopped unexpectedly.

**Comment by balbirthomas** [comment]
> The charm does get `start`, `config_changed`, `upgrade_charm`, `leader_elected` (possibly).

I think the most troublesome issue here is that there is no guarantee that application and unit relation data is maintained across pod restart. Relation events do not seem to be included in the list of events that a charm receives on pod restart. As a result of these two behaviours a charm needs to set *the same* relation data both in relation events and pebble ready event (as was done in the [Prometheus consumer library](https://github.com/canonical/prometheus-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus.py#L628) using a "service event". It is not clear to me if this is intended behaviour or a bug. If it is intended behaviour the perhaps it must be explicitly documented in the [Operator Framework documentation](https://ops.rtfd.io) that relation data is not guaranteed exist across a kubernetes pod restart.

**Comment by jameinel** [comment]
So both the relation data that was set by the charm and the relation data
that was sent to the charm should very much be maintained across restarts.
If you can document an example case where you are not seeing this, then we
should definitely investigate.

**Comment by balbirthomas** [comment]
>  If you can document an example case where you are not seeing this, then we should definitely investigate.

I rechecked and I think I am mistaken here. The data do indeed persist. There is however a need to update some of the relation data, in particular unit IP address, which changes on Pod restart. So such data needs to be refreshed in the pebble ready event. I do not see the need to refresh any other data at the present time. This should be fine.

**Comment by rbarry82** [comment]
I'd suggest `on_start` or `config_changed` rather than `pebble_ready`. `pebble_ready` is ok, and it's very likely that actually _using_ any of the data from the relation will require that the workload sidecar is running, but "pebble is ready" is not always the same as "the charm is running", and the IP address is bound to the `charm` container first (the network namespace sharing is interesting, but the address can generally be updated _before_ pebble_ready).

You can (relatively) safely assume that killing/restarting/upgrading a charm will fire both events, but it bears considering.

**Comment by balbirthomas** [comment]
I will try and use `on_start` for refreshing IPs. Once again I would like to emphasise the need to document these behaviours of the Juju event model as exposed by the Operator Framework. Failing to do so would be an endless source of confusion for charm writers and an unpleasant developer experience. For example it may be prudent to make the following explicit in official docs either

1. What events do K8s charms get when pod is restarted ?" (This is mentioned above in this ticket but I have not seen this being made explicit associated docs).
2. What guarantees does a charm have in a start event ?  Will the workload container be up and running ? Will the network be configured ?
3. What guarantees does a charm have in a pebble ready event ? Will the network be ready ? Will the workload be started by a prior start event or a prior config changed event ?

Finally please do recognize that the number of times there have been questions and discussions on the appropriate ways to setup and update workload configurations that require unit addresses (for peers and other relations) is indicative of need for improvement here, at least in the documentation, if not in the API. Perhaps one or more "How-To" guides (as distinguished from other forms of documentation in the [Diataxis](https://diataxis.fr/) framework.) may be very useful.

**Comment by rbarry82** [comment]
I'll take a little time to think about this to update the docs.

However, it's worth considering that this is not "as exposed by the Operator Framework". This is simply, purely, "how does **Juju**'s event model behave on a pod restart". I'll grant that, as the principal interface that Charm authors see, this is on OF to document, but this is not OF filtering which events make it through to charms.

For all of these events, which come from outside of OF and are [simply dispatched](https://github.com/canonical/operator/blob/b1a8fffc053fbbdaf43b826e78c220bfdae4c8fe/ops/main.py#L177) by the operator framework, even determining the answers to some of these questions will take collaboration and experimentation.

The "right answer" to questions about how to setup and update workload configurations which require unit addresses is resolution of issues such as [this one](https://github.com/canonical/operator/issues/560), followed by a docs update. Right now, the OF is a bit of a moving target which is adding functionality as issues are raised. Investing time into documenting how to manage peer relations only to rewrite it (and it's not a complex issue request) borders on wasted effort considering that a significant investment of time needs to go into extending the framework into supporting machine charms, etc.

We will get there. Right now they are beta-quality docs for an in-development project.
