### ISSUE TITLE
[docs] What happens first: on.remove or on.stop?

### ISSUE THREAD

**Issue by heitorPB** [canonical/operator#575]
Hello,

I'm trying to understand what event happens first: `on.remove` or `on.stop`. It makes sense to first stop the charm and after that remove the files.

But the docstrings in https://github.com/canonical/operator/blob/master/ops/charm.py#L131-L146 do not say what happens first.

The documentation in https://juju.is/docs/sdk/events is not clear about it in the section about `stop`.

So, what event happens first?

**Comment by rbarry82** [comment]
Stop, then remove. In general, your charm should try to handle all necessary steps in the `stop` hook, since `remove` is actually terminating the pod/unit. Docs have been updated. The example workflow gave the steps in order, but it's been made more explicit.
