### ISSUE TITLE
RelationData submits a relation-set even if data is the same

### ISSUE THREAD

**Issue by phvalguima** [canonical/operator#578]
Hi,

One thing I've noticed is that, if I update the RelationData object with the same ```relation.data[key] = value```, it still issues a relation-set command. That will trigger a -changed event on all the other units of that same relation for no reason, given data is the same.

In some cases, I've ended up on an endless loop of -changed calls because the peers of the relation kept submitting the same data as they woke up and process their own RelationChangedEvents.

I don't see much benefit of just submitting it to relation-set without first recovering current value and checking if that is the same. Besides, if I am not mistaken, Operator framework converts it to string before submitting so we can compare the values of the strings before doing so.

In any case, I think it is cheaper to do the following before the data update:
1) Run relation-get
2) Compare the strings (new value and recovered value)
3) Run relation-set if the value is different

That will save calls to the controller and other units at the expense of some preprocessing.

**Comment by jnsgruk** [comment]
This seems like a relatively simple fix to me, @jameinel is there any background as to why we don't currently inspect the contents of a data bag before invoking `relation-set`.

I guess I'm also a little surprised that there isn't some checking in the `relation-set` hook tool itself; should there in fact be some logic there which prevents an emission of a `relation-changed` event if the data hasn't actually changed? (cc @wallyworld)

**Comment by jameinel** [comment]
On the Juju side, I'm relatively sure that calling 'relation-set' that
doesn't change the actual content won't actually trigger a relation-changed
event. I tested it out with a charm of ours, and I could even do:
 relation-set foo=a
 relation-set foo=b

within a single hook, and as long as it was always 'b' at the end, it
wouldn't trigger relation-changed.

**Comment by jnsgruk** [comment]
Aha, thanks @jameinel. @phvalguima can you also verify this your end? We can probably close this issue?

**Comment by rbarry82** [comment]
@phvalguima ping

**Comment by phvalguima** [comment]
@jnsgruk @rbarry82 I've tried to reproduce this issue on a simpler example but I could not. The original code I used to have this issue now has a lot of checks for that.

We can close this issue and if I get a reproducer I reopen it.
