### ISSUE TITLE
get_relation returns None for a peer relation

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#583]
While debugging an [alertmanager unittest](https://github.com/canonical/alertmanager-operator/blob/6e785756a98e60d005fc4ec5a561cc408d5a8668/tests/test_charm.py#L55) I noticed that passing a string for binding_key works:
```python
>>> self.model.get_binding('replicas')
<ops.model.Binding object at 0x7fa2df513850>
>>> self.model.get_binding('replicas').network.bind_address
IPv4Address('1.1.1.1')
```
However, at the same time, get_relation returns None:
```python
>>> type(self.model.get_relation('replicas'))
<class 'NoneType'>
```

https://github.com/canonical/operator/blob/7344b5c284ff4009dbde29c4df99205eaad2e8ba/ops/model.py#L165-L177

**Comment by jameinel** [comment]
I believe this is probably waiting for 'relation-created' to trigger, and
then get_relation will no longer return None. But during 'install' the
relation doesn't exist as exposed to the charm yet.
