### ISSUE TITLE
Redefine relation library in terms of sockets rather than multiplicity

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#586]
## Introduction
The `ops.relation` module was built under the assumption that `provides` and `requires` side of `metadata.yaml` are defined in terms of multiplicity in the relation. The provider being a singleton with potentially many consumers. However it has recently surfaced that Juju expects the provider to be the one that opens a server socket. This implies that the multiplicity assumption may not be valid. For example a [Prometheus](https://prometheus.io) charm may be related to multiple others charms which serve as metrics scrape targets. However since Prometheus makes the TCP request to gather metrics from each target, it is the targets that open a server socket. Hence the targets are providers with multiplicity greater than one and Prometheus is a consumer with multiplicity one. This shift in perspective may require some enhancements and modifications to the `ops.relation` module as detailed below. These suggestions are split into required and suggested sections.

### Required changes
1.  All events in `ConsumerEvents` descriptor may need to expose relation data or at least `event.relation.id`. This is necessary because a consumer may have multiple providers and so it would need to know which of those providers generated the event.

### Suggested changes
1. The `multi` parameter may now apply to both `ProviderBase` and `ConsumerBase`. Alternatively this parameter may just be removed and multiple relations of same type may just be supported by default.
2. `ready()` and `unready()` events may now apply to both `ProviderBase` and `ConsumerBase`.
3. Perhaps both provider and consumer may support validating each other instead of only consumer validating the provider.
4. Perhaps `ProviderBase` may also need to expose bespoke events like `ConsumerBase.`

**Comment by sed-i** [comment]
Also, provider needs to be able to take a spec instead of a version, otherwise:
```
    got = semver.Version.coerce(self._normalized_version(has))
  File "/var/lib/juju/agents/unit-karma-0/charm/venv/semantic_version/base.py", line 236, in coerce
ValueError: Version string lacks a numerical component: '>=0.86'`
```

**Comment by heitorPB** [comment]
The provides/requires terminology sometimes is confusing to me.

I am charming Fluent Bit as a subordinate machine charm to forward logs from our services to a centralized place.

This is the "workflow" :
- Main charm does stuff and generates/updates the log files, then it provides to Fluentbit-charm the log files to monitor.
- FluentBit provides/forwards the logs to a central place.

In this sense, the Fluentbit charm is related to the main charm (to read the log files), and also to the central-log-place charm (to forward the logs).

And Fluentbit could also be related to multiple centralized logging systems (it can forward to multiple places simultaneously).

**Comment by rbarry82** [comment]
> Also, provider needs to be able to take a spec instead of a version, otherwise:
> 
> ```
>     got = semver.Version.coerce(self._normalized_version(has))
>   File "/var/lib/juju/agents/unit-karma-0/charm/venv/semantic_version/base.py", line 236, in coerce
> ValueError: Version string lacks a numerical component: '>=0.86'`
> ```

Please be clearer about what you mean by "spec". What kind of specification?

**Comment by jnsgruk** [comment]
See #606
