### ISSUE TITLE
Add `copy()` method for StoredDict

### ISSUE THREAD

**Issue by mkalcok** [canonical/operator#587]
It would be nice if [StoredDict](https://ops.readthedocs.io/en/latest/index.html?highlight=StoredDict#ops.framework.StoredDict) objects had `copy` method like [regular dicts](https://docs.python.org/3/library/stdtypes.html#dict.copy).

This is merely a convenience method and right now it can be worked around by using `my_copy = dict(stored_dict.items())` but still...

**Comment by jameinel** [comment]
Should it return a dict or another StoredDict ?

**Comment by mkalcok** [comment]
That's a good question. I'd say that it should return pure `dict` as `StoredDict` is more of a internal class that is pretty transparent to the `ops` user and not meant for a direct usage?  (but I might be wrong here with the intentions for this class)

**Comment by rbarry82** [comment]
Returning a regular `dict()` is easy enough to do in this case. The semantics would not be exactly the same as `dict.copy()`, though, since `StoredDict` keeps the actual backing dict elsewhere, and the shallow copy would not necessarily be kept in sync with the backend changes.

If that's ok with you, then +1

**Comment by jameinel** [comment]
So 'dict.copy()' is certainly a shallow copy. If anything I'd rather
StoredDict.copy ended up being a deepcopy so we don't have accidental
mutation.
I find this behavior unfortunate:
```
>>> x = {1:2, 3:{4:5}}
>>> y = x.copy()
>>> x[1] = 3
>>> x[3][4] = 6
>>> x
{1: 3, 3: {4: 6}}
>>> y
{1: 2, 3: {4: 6}}
```

(some mutations of X affect its copy, but some don't). And certainly I know
why and can explain it, but it is non-intuitive for users.

**Comment by mkalcok** [comment]
Hi, sorry for the delay, I was off last 2 weeks.
The implementation in the linked PR looks good to me with the `deepcopy` behavior in `as_dict` method. Thanks.

**Comment by jnsgruk** [comment]
Hi,

Please see comments in #527 and #596. The best way to achieve this for now is indeed to use the `dict()` constructor.

Thanks!
