### ISSUE TITLE
Add `copy()` method for StoredList

### ISSUE THREAD

**Issue by heitorPB** [canonical/operator#602]
Hello,

It would be nice to have a `.copy()` method for a StoredList that returns a deep copy as a List object.

Right now we have to `new_list = list(self._stored.the_list).copy()` as a workaround.

Similar to #587

**Comment by jnsgruk** [comment]
Hi,

Please see comments in #527 and #596. The best way to achieve this for now is indeed to use the `list()` constructor.

Thanks!
