### ISSUE TITLE
Capture the stdout/stderr of the service in the ChangeError exception message when the service immediately exits

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#619]
When the workload executable cannot start due to e.g. incorrect arguments, the reason is not immediately obvious from the juju debug logs.
```
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "avalanche" (cannot start service: exited quickly with code 1)
```
It would be handy if the exception message included the error message emitted by the service (if any).

**Comment by benhoyt** [comment]
Good call. I have a quick fix in progress at https://github.com/canonical/pebble/pull/69

**Comment by jnsgruk** [comment]
+1 on this, would be super useful

**Comment by rbarry82** [comment]
@benhoyt This looks like it'll get consumed transparently by OF. Anything we need to do?

**Comment by benhoyt** [comment]
@rbarry82 Yep, that's right, it'll come through to OF automatically when the Pebble change is merged (and included in Juju). Happy to keep this issue open to track till then, however.

**Comment by benhoyt** [comment]
Merged, closing!
