### ISSUE TITLE
[pebble] Restart at on_config_change fails because of missing service

### ISSUE THREAD

**Issue by phvalguima** [canonical/operator#627]
I was building my code out of the template provided by [charmcraft](https://github.com/canonical/charmcraft/blob/master/charmcraft/templates/init/src/charm.py.j2) and I've added the following logic to my config-changed:

```
    def on_config_changed(self, event):
        . . . . . .

        if svc.is_running():
            container.restart("postgresql")
        else:
            container.start("postgresql")
```

That will fail complaining that service "postgresql" was not found. When I look at the logs, I can see that the following hooks have been executed:
1) install
2) config-changed

But "pebble ready" hook was not yet executed, which means the the layer containing the services was not passed on to pebble.
However, I need to run that (re)start procedure after every config-changed because I need the changes to be loaded.

The only solution I have so far is to have a condition to check if pebble-ready hook has been already ran or not. Something similar to:

```
    stored = StoreState()

    def __init__(self):
         self.stored.set_default(pebble_was_ran=False)

    def on_config_changed(self, event):
          if not self.stored.pebble_was_ran:
              event.defer()
              return
          . . . . 

    def pebble_ready(self, event):
          # Run pebble start logic
          self.stored.pebble_was_ran = True
```

Does it make sense to have config-changed events before pebble-ready happens?

**Comment by jnsgruk** [comment]
We did discuss this a while ago, the pebble-ready event is not triggered in the same way as other events in the model, because it's dependent on how long it takes for Kubernetes to schedule a pod, the container to come up, and the pebble API to be up.

I think you could solve your problem, though with a combination of `can_connect` and `get_services` to check if the service is defined, and either defer, or define the service?

**Comment by jnsgruk** [comment]
A side note, `container.restart` is idempotent, so you can drop the conditional based on whether the service is running and just call the restart method in every case :)

**Comment by phvalguima** [comment]
Hi @jnsgruk, thanks for the feedback.

Indeed I need to handle that case in my code rather than having the operator to do it. Some automatic deferring is not a good idea. What happens if the charm is a k8s charm without pebble?

My suggestion would be to review the charmcraft template to already come with this case covered and enough comments explaining it or pointing to some external documentation.

I will close this issue as it has nothing to be done on operator side.
