### ISSUE TITLE
File permissions in testing harness may not reflect production Juju behavior

### ISSUE THREAD

**Issue by pengale** [canonical/operator#670]
This came up in the discussion around PR #645 

Since Pebble runs as root, it may not respect file system permissions in the same way that the testing harness attempts to respect them.

We might want to do some work to bring the harness' behavior in line with Juju's. And also keep an active line of communication open so that it also reflects any changes and fixes in core :-)

**Comment by benhoyt** [comment]
I think this is a valid issue, but also vague -- "it may not respect file system permissions". I'm going to close this issue and we can open others for specific issues.
