### ISSUE TITLE
Harness should know the app name before `begin`

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#675]
## Intro
I am writing a test for a multi unit cluster.
Per docstring, `harness.add_relation` must be called before `begin`:

https://github.com/canonical/operator/blob/9cfa44b110388fd44c4c29adcb1c2fd40be104be/ops/testing.py#L160-L171

(Indeed, if I call `harness.add_relation` after `begin` I get `ops.model.TooManyRelatedAppsError: Too many remote applications on replicas`)

For a peer relation, the "remote app" is in fact `harness.charm.app.name`, however, that is not available before `begin`: if I try to use it before `begin` I get:
`AttributeError: 'NoneType' object has no attribute 'app'`

## Steps to reproduce
```python
    def setUp(self):
        self.harness = Harness(AlertmanagerCharm)
        self.addCleanup(self.harness.cleanup)

        self.peer_rel_id = self.harness.add_relation("replicas", self.harness.charm.app.name)
        self.harness.begin_with_initial_hooks()
```

## Expected result
`setUp` to succeed and my `test_` methods to start running.

## Actual result
```
Traceback (most recent call last):
  File "/home/tux/charms/alertmanager-operator/tests/unit/charm/test_push_config_to_workload_on_startup.py", line 31, in setUp
    self.peer_rel_id = self.harness.add_relation("replicas", self.harness.charm.app.name)
AttributeError: 'NoneType' object has no attribute 'app'
```

Same thing for `harness.charm.meta.name`:
```
Traceback (most recent call last):
  File "/home/tux/charms/alertmanager-operator/tests/unit/charm/test_push_config_to_workload_on_startup.py", line 32, in setUp
    self.peer_rel_id = self.harness.add_relation("replicas", self.harness.charm.meta.name)
AttributeError: 'NoneType' object has no attribute 'meta'
```

**Comment by rwcarlsen** [comment]
You should be able to use `self.model.app.name` before `begin` is called - this is what we do in the ops framework tests for the harness.  If there are other related issues you are having, please let us know.

**Comment by sed-i** [comment]
That works, thanks!
Closing.
