### ISSUE TITLE
remove_path in test harness should behave like `rm -f` if path not found

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#676]
## Intro
Switching to use the filesystem impl introduced in #645 in the prometheus unit tests resulted in `FileNotFoundError` because `remove_path(..., recursive=True)` behaves like `rm -r` and not `rm -rf`:

https://github.com/canonical/operator/blob/9cfa44b110388fd44c4c29adcb1c2fd40be104be/ops/testing.py#L1548-L1549

For this reason charm author should be able to:
- pass the equivalent of `--force` to `remove_path`; or
- have api to check if a path exists and use it before calling `remove_path`

## Steps to reproduce
```python
container.remove_path("/non/existing/path", recursive=True)
```

## Expected result
Function call should succeed (not raise) even if path does not exist.

## Actual result
```
  File "/home/tux/charms/prometheus-operator/.tox/unit/lib/python3.9/site-packages/ops/model.py", line 1299, in remove_path
    self._pebble.remove_path(path, recursive=recursive)
  File "/home/tux/charms/prometheus-operator/.tox/unit/lib/python3.9/site-packages/ops/testing.py", line 1549, in remove_path
    file_or_dir = self._fs.get_path(path)
  File "/home/tux/charms/prometheus-operator/.tox/unit/lib/python3.9/site-packages/ops/testing.py", line 1679, in get_path
    raise FileNotFoundError(str(current_object.path / token))
FileNotFoundError: /etc/prometheus/rules
```

**Comment by benhoyt** [comment]
For the record, Pebble itself does behave as you expect here, so I think this is just a bug in the test filesystem harness. Using the Python Pebble test CLI:

```
$ ls -d asdf
ls: cannot access 'asdf': No such file or directory
$ PEBBLE=~/pebble python3 -m test.pebble_cli rm /home/ben/w/operator/asdf -r
removed remote path /home/ben/w/operator/asdf
```

**Comment by benhoyt** [comment]
I forgot to mention that (for better or worse) Pebble's behavior on "file not found" is different for recursive vs non-recursive. For recursive mode it's not an error, for non-recursive mode it *is* an error:

```
$ PEBBLE=~/pebble python3 -m test.pebble_cli rm /home/ben/w/operator/asdf
Traceback (most recent call last):
  ...
ops.pebble.PathError: not-found - remove /home/ben/w/operator/asdf: no such file or directory
$ PEBBLE=~/pebble python3 -m test.pebble_cli rm /home/ben/w/operator/asdf -r
removed remote path /home/ben/w/operator/asdf
```
