### ISSUE TITLE
Harness: `add_relation` or realtion joined do not emit "relation changed"

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#682]
"Relation changed" always follows "relation joined":

https://github.com/canonical/operator/blob/28d9870b5b76be12c949c7b49964dcc26969f68f/ops/charm.py#L373-L375

However, `add_relation` emits `relation_created` but not `relation_changed`:

https://github.com/canonical/operator/blob/28d9870b5b76be12c949c7b49964dcc26969f68f/ops/testing.py#L510-L511

and manually emitting "relation joined" does not cause "relation changed" to be emitted, for example:
```python
        self.harness.begin_with_initial_hooks()
        self.harness.set_leader(True)
        self.rel_id = self.harness.add_relation("logging", "loki")
        self.harness.charm.on.logging_relation_joined.emit(self.harness.charm.model.get_relation("logging"))
        # relation changed is not emitted
```

This behavior is the same for when `add_relation` is called before or after `begin_with_initial_hooks`.

If this is intentional to facilitate testing then a doc update to `add_relation` indicating that test code needs to emit both `relation_joined` and `relation_changed` manually is probably needed.

https://github.com/canonical/operator/blob/28d9870b5b76be12c949c7b49964dcc26969f68f/ops/testing.py#L484-L493

**Comment by jameinel** [comment]
Add relation says that you have a relation with an application.
add_relation_unit is what fires relation-joined and relation-created.

John
=:->

**Comment by sed-i** [comment]
Thanks @jameinel ! I should go fix a few tests now :)
