### ISSUE TITLE
Evaluate and improve push/pull performance

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#684]
Push and pull implementations have potential for various improvements including:

* Pull buffers (post #667) all content onto disk - even small file contents - this could be done in-memory
* Pull currently reads/caches the entire file content onto disk before returning to the caller.  It should be possible to immediately return a file-like-object to the caller while the data is streamed into it behind the scenes.

To guide these types of improvements it will be important to have some good push/pull performance tests/profiling so we don't end up making code less straight forward for only (unrealized) theoretical gains.

**Comment by benhoyt** [comment]
Going to close this. We haven't seen any problems with this to date, and disk I/O is usually pretty efficient these days. We can reopen if this becomes an actual problem in practice.
