### ISSUE TITLE
Document remove_path method behaviour and exceptions properly

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/operator#699]
The `remove_path` method in `pebble` has an optional argument `recursive: bool = False`:

```python
def remove_path(self, path: str, *, recursive: bool = False):
```

Let's say that you need to delete a **file** from a container's directory. But it's possible that the file you trying to delete it is not **yet** in the directory.

If you have:

```python
container.remove_path(path)
```
You will get a `PathError` exception since the file does not exist. This makes sense, it is behaviourally similar to `rm <file>`:

```bash
➜  rm pepe.txt
rm: cannot remove 'pepe.txt': No such file or directory
```
But there is no explicit option that behaves similar to `rm -f <file>` (do nothing if the files is non-existent):

```bash
➜  rm -f pepe.txt
➜
```

Anyway you can achieve that behaviour by using `recursive=True` 

```python
container.remove_path(path, recursive=True)
```

`recursive=True` behaves in 2 ways:

- If `path` is a directory recursively deletes it and everything under it.
- If the `path` is a file, delete the file and do nothing if the file is non-existent. Behaviourally similar  to `rm -rf <file|dir>`

Using `recursive=True` when trying to delete a file and do nothing if file is non-existent (`rm -f <file>`) is a little bit confusing.

Shouldn't we try to mimic the rm behaviour where we have: [`-r` for recursive and `-f` for "ignore nonexistent files and arguments, never prompt"](https://www.man7.org/linux/man-pages/man1/rm.1.html#OPTIONS)?

**Comment by pengale** [comment]
Thank you for filing this!

**Comment by balbirthomas** [comment]
Another way to view the alternative suggested above is to ask the question "when will it happen that a developer would *not* want to use the `-f`" option ? If the answer is never then a `-f` method argument is redundant.

**Comment by jameinel** [comment]
It depends. rm a missing file is usually an error because it is usually a
sign of a typo and you should be made aware that what you thought would be
removed isn't.

**Comment by balbirthomas** [comment]
> It depends. rm a missing file is usually an error because it is usually a sign of a typo 

That is a good point and a valid concern indeed. However if a typo is made in a interactive command such as `rm` then a human being may notice it and fix it. But what is a charm supposed to do when it tries to delete a file and realizes it does not exist ? Go into blocked state ? If the charm goes into blocked state what is the system administrator supposed to do ? Alternatively a charm can just log the error and continue, in which case I see not any difference from the operator framework just logging the error instead of raising an exception or requiring an additional method argument.

**Comment by pengale** [comment]
I suspect that a lot of people using the lib would just pass -f, and create their own problems detecting typos.

I like the simplicity of having the library work one way, with my preferred way being to remove a path if it exists, and log a warning if it does not. (The warning gives typo makers a chance to catch their error.)

**Comment by benhoyt** [comment]
I think at this point we should simply "solve" this by documenting the existing behaviour -- making clear what exceptions are raised when, and how it's different if `recursive=True`.

Related: right now the docstrings have gotten out of sync between `pebble.Client.remove_path` and `model.Container.remove_path`, so we should get them back in sync too.

**Comment by amandahla** [comment]
I was about to file an issue regarding this. I missed the docs warning about how remove_path raises PathError.
