### ISSUE TITLE
remove charmhelpers lib references from docs

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#706]
charmhelpers is an outdated lib/way of getting info.  Replace instances in the docs of this with the new ops framework way of doing things.  e.g. all the `python` examples here need to be fixed: https://discourse.charmhub.io/t/hook-tools/1163

**Comment by benhoyt** [comment]
Yeah, this is definitely still an issue in published docs [here](https://juju.is/docs/sdk/hook-tool). Needs to be updated.

**Comment by benhoyt** [comment]
These docs have been overhauled since then, and it looks like this is done.
