### ISSUE TITLE
`leader-settings-changed` firing before unit departure

### ISSUE THREAD

**Issue by MiaAltieri** [canonical/operator#708]
Hi team. I had some weird behavior for this set up / situation

For Example. If you have these units:
```
A *
B
C
```
and `A` departs then you get these events hooks for each unit:
`A`:  `leader-settings-changed` , `mongodb-storage-detaching`, `mongodb-relation-departed`(for A-B), `mongodb-relation-departed`(for A-C), `stop`, `remove`
`B`: `mongodb-relation-departed` (for A-B)
`C`: `mongodb-relation-departed` (for A-C), 

According to @wallyworld and @rwcarlsen this is unexpected behaviour and should be looked into. As requested, [this](https://github.com/canonical/mongodb-operator/tree/DPE-65-relation-departed) is my repo/branch where I observed this behaviour. It can be observed by first creating the necessary environment according to [CONTRIBUTING.md](https://github.com/canonical/mongodb-operator/blob/main/CONTRIBUTING.md). Once the environment has been created you can reproduce this with:
```
# pack and deploy
charmcraft pack
juju deploy -n3 ./*charm

# in a separate session
juju debug-hooks <leader_unit>

# remove unit 
juju remove-unit <leader_unit
```

**Comment by rwcarlsen** [comment]
If @wallyworld could clarify exactly what juju *should* be doing here that would help inform the best approach for dealing with things in the ops framework here.

**Comment by jameinel** [comment]
This doesn't feel like an operator framework issue, but a juju issue
https://bugs.launchpad.net/juju/+filebug

**Comment by rwcarlsen** [comment]
FWIW  [these docs](https://discourse.charmhub.io/t/implementing-leadership/1124) suggest that the leader-settings changed event should be firing like this.

**Comment by rwcarlsen** [comment]
I hunted in the juju code for a bit and couldn't find anywhere that triggered a leader-settings-changed hook for unit departure.  But my eyes and brain aren't very trained on reading the juju codebase yet.  So maybe that doc page is just wrong (or out of date)...

**Comment by MiaAltieri** [comment]
@jameinel [bug filed](https://bugs.launchpad.net/juju/+bug/1964582)

**Comment by jnsgruk** [comment]
Nice, thanks all. Will close this for now and we can track this issue in the bug that Mia filed :)
