### ISSUE TITLE
Improve situation around charm versioning

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#718]
There was lots of discussion on #692 about inconsistent/poor version handling for charms in the framework, charmcraft, etc.  This needs to be improved.  There are some relevant charmcraft issues - e.g. canonical/charmcraft#37.  But probably more needs to be done both to track/provide version info to charms as well as doc'ing the situation.

**Comment by mmanciop** [comment]
For context, in COS we want to collect the charm version so that, as charms get updated, we can document improvement or regressions in performance.

**Comment by benhoyt** [comment]
@simskij This is an old issue, but do you have any thoughts or issues about charm versioning you want to surface? Do you know what the actual issues are here?

**Comment by benhoyt** [comment]
This is very general. Several version-related issues have been fixed, but we'd need more specifics of what we're trying to achieve here for this to be meaningful -- closing.
