### ISSUE TITLE
`begin_with_initial_hooks` should end up in UnknownStatus if charm did not `set-status` during startup

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#726]
It seems that at the moment, `begin_with_initial_hooks` would end up in MaintenanceStatus if the charm didn't `set-status`, 

https://github.com/canonical/operator/blob/45e1e5a9e4e99492d09423436b8378f955c4f0a3/ops/testing.py#L1034

unlike juju, which ends up in UnknownStatus. This behavior is also documented in an ops docstring:

https://github.com/canonical/operator/blob/45e1e5a9e4e99492d09423436b8378f955c4f0a3/ops/model.py#L885-L891

If you deploy a blank charm,

```shell
mkdir blank
charmcraft init -p blank
cd blank
# comment out: self.unit.status = ActiveStatus()
charmcraft pack
juju deploy ./blank_ubuntu-20.04-amd64.charm --resource httpbin-image=kennethreitz/httpbin
```

Then it indeed goes into UnknownStatus.

**Comment by jameinel** [comment]
FWIW, Juju starts in Maintenance, and if at the end of Install a charm has
not otherwise set a status, we go into Unknown.

**Comment by sed-i** [comment]
I observe a slightly different behavior with the blank charm: during config changed it is still maintenance, not unknown:

| Workload    | Agent      | Message                                    |
|-------------|------------|--------------------------------------------|
| waiting     | allocating | installing agent                           |
| waiting     | allocating | agent initializing                         |
| running     | idle       | Started container httpbin                  |
| maintenance | executing  | (install) installing charm software        |
| maintenance | executing  | installing charm software                  |
| maintenance | executing  | (config-changed) installing charm software |
| unknown     | idle       |                                            |

**Comment by pengale** [comment]
Updated PR to address the above.
