### ISSUE TITLE
KeyError: storage_name mismatch 

### ISSUE THREAD

**Issue by jardon** [canonical/operator#729]
When upgrading a charm from ops 1.2 to 1.3, I hit the following KeyError:

```
self = <ops.testing._TestingModelBackend object at 0x7f067bdd77f0>, name = 'minio_data'

    def storage_list(self, name):
>       return list(index for index in self._storage_list[name]
                    if self._storage_is_attached(name, index))
E       KeyError: 'minio_data'

.tox/unit/lib/python3.9/site-packages/ops/testing.py:1132: KeyError
```

Here is my `metadata.yaml`
```yaml
storage:
  minio-data:
    type: filesystem
    location: /data
    minimum-size: 10G
```

Here is some debugging info:
```
(Pdb) self._storage_list
{'minio-data': {}}
(Pdb) self._meta.storages
{'minio-data': <ops.charm.StorageMeta object at 0x7fd5f6c74d90>}
(Pdb) name
'minio_data'
```
This seems to be caused by `storage_name = storage_name.replace('-', '_')` on line 181 of `testing.py` transforming the name unnecessarily.  To fix this, I had to change the storage name in the `metadata.yaml` to use an underscore instead of a hyphen.

**Comment by rwcarlsen** [comment]
The fix for this has already been merged and should be coming in 1.4: https://github.com/canonical/operator/pull/680
