### ISSUE TITLE
[Feature request] Be able to set configuration options

### ISSUE THREAD

**Issue by erik78se** [canonical/operator#730]
This is a feature request.

To be able to set a configuration option/value from within the code would be very handy.

It would allow to revert a config change that would be "invalid". Today, if you set a config value wrong, a user can end up in a situation where it can be an irrecoverable problem but there is very little a developer can do to help the user not to enter a bad config value even before the change takes place. 

To be able to catch situations like this and "roll-back" a configuration change would give charm developers a means to protect deployments and reduce chances and fear of errors introduced by re-configuration.

**Comment by jnsgruk** [comment]
Hi Erik

While I can see your point, this is a very deliberate part of the design of Juju. By allowing charm authors to modify config, it could really confuse admins who think they have set a specific option, which then somehow reverts back in production.

The correct way to handle this situation is to signal to the user that something is up with the config using a combination of a status message and log messages. If the config is truly "bad" and needs human intervention to be fixed, then the charm should probably be placed into a Blocked state.

Closing this issue for now - we won't implement this feature, but happy to continue the discussion about patterns to handle these situations over at https://discourse.charmhub.io! :)
