### ISSUE TITLE
Some events should not be deferrable

### ISSUE THREAD

**Issue by pengale** [canonical/operator#740]
When Juju is tearing down a unit, deferring does not work as one might naively expect. Since the controller does not have a view of "deferred" or "non deferred" events, the controller will simply assume that the "deferred" hook finished, and will continue the teardown.

When charm authors call event.defer on events like `storage-detached`, and possibly `relation-departed` and `relation-broken`, the framework should raise an error.

Error states *are* visible in the controller. This means that the code will do what the charm author probably "intended", which is to block the teardown until something else happens.

**Comment by jameinel** [comment]
We already have code that actions cannot be deferred, we can probably use
the same errors in this situation.

**Comment by pengale** [comment]
> We already have code that actions cannot be deferred, we can probably use the same errors in this situation.

Excellent. Writing less code is always good :-)

**Comment by benhoyt** [comment]
Events like `ActionEvent.defer` raise `RuntimeError` for this, so we could follow that precedent for these "tearing down" events.

**Comment by benhoyt** [comment]
This is still an issue. However, we're thinking of (maybe!) deprecating defer in general, see https://github.com/canonical/operator/issues/966

**Comment by tonyandrewmeyer** [comment]
This was done in #1122, and I missed linking the PR to the ticket, sorry :disappointed:.
