### ISSUE TITLE
Harness to auto attach storage?

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#750]
Following up on https://github.com/canonical/operator/pull/734, I tried it out in some unit tests and had the following recurring code:

```python
storage_id = self.harness.add_storage("name")[0]
self.harness.attach_storage(storage_id)
```

Would it be feasible/sensible to auto attach all storages in metadata (perhaps with `count=1` by default)?

For example,

```python
self.harness.auto_attach_storages()
self.harness.begin_with_initial_hooks()
```

**Comment by PietroPasotti** [comment]
Shouldn't the storage-attached events be part of the 'initial hooks' in the `begin_with_initial_hooks` sense?
If that method is meant to be a 'simulate a happy-path situation where all is good', and https://github.com/PietroPasotti/charm-events is correct, then I'd expect all relevant storage-attached events to be the first thing to fire when I call `begin_with_initial_hooks`.

**Comment by sed-i** [comment]
Thanks @PietroPasotti. 
I do see that `begin_with_initial_hooks` [emits](https://github.com/canonical/operator/blob/eb33286800bf94b60b7354b350f2725ab5b81865/ops/testing.py#L233) `storage_attached`, so I guess all I need to do is 
`self.harness.attach_storage(storage_id)`?

My [code](https://github.com/canonical/cos-configuration-k8s-operator/pull/21) is still a draft but unit tests currently fail if I do not have the `add_storage` calls.

**Comment by rwcarlsen** [comment]
Yes - you will need to use `add_storage` before the begin_with_initial_hooks call even if you already have the storage in your metadata.  This was a design decision that was made before I was around, so I'm not sure the reasoning behind it.  But it definitely seems reasonable to consider adding all meta-data storage automatically in begin_with_initial_hooks.  I'll have to think about it more first though.  At a minimum it may break tests for existing charms :-/

**Comment by pengale** [comment]
The charm should behave well (i.e. set a useful error message) if the person deploying the charm has neglected to add storage to the cloud. I think that it is reasonable to expect a charm author to remember to do something if that charm author is also expecting an operator to do that thing :-)

We can make the harness error message as friendly as possible, though. The harness might even suggest that a charm author check for the existence of the storage, and set model.application.status to something like `ErrorStatus("this charm requires storage: see docs @ ..."`

**Comment by sed-i** [comment]
Agreed. Not sure what's best for harness.
- on one hand, `juju deploy` takes care of storages defined in metadata, and `begin_with_initial_hooks` does take care of many other aspects of startup;
- on the other hand, we do need to manually emit the pebble-ready event anyway.

**Comment by rwcarlsen** [comment]
Yeah - there is definitely a case for `begin_with_initial_hooks` to just simulate what juju does in production (i.e. automatically add storage in metadata.yaml) - since that is sort of the benchmark for how it operates generally.

**Comment by sed-i** [comment]
I have some issues with my unit tests (they fail if I omit a call to `attach_storage`) so I was wondering:
1. Seems like `storage_name = storage_name.replace('-', '_')` is missing from `add_storage` and `attach_storage`.
1. Currently `add_storage` calls `storage_attached.emit()`. Is that intentional?
1. Should `add_storage` and `begin_with_initial_hooks` use `attach_storage` instead?

`add_storage`:
https://github.com/canonical/operator/blob/eb33286800bf94b60b7354b350f2725ab5b81865/ops/testing.py#L473-L477

`attach_storage`:
https://github.com/canonical/operator/blob/eb33286800bf94b60b7354b350f2725ab5b81865/ops/testing.py#L511-L515

`begin_with_initial_hooks`:
https://github.com/canonical/operator/blob/eb33286800bf94b60b7354b350f2725ab5b81865/ops/testing.py#L229-L234

**Comment by rwcarlsen** [comment]
1. The -/_ replacement occurs automatically with the `.on[...]` call: https://github.com/canonical/operator/blob/eb33286800bf94b60b7354b350f2725ab5b81865/ops/framework.py#L453
2. I'll need to look into this more.  At first glance, it seems like we should definitely use more care with how we handle add/attach/detach - it looks like there may be a few subtle bugs lurking.
3. Possibly.  I'll dig into this as well.

**Comment by rwcarlsen** [comment]
The trick with auto-attaching on begin_with_initial_hooks is the harness doesn't know how many instances of each particular storage it should create/mount for cases where there can be multiple.  If we did do that, we'd need to implement some logic mirroring how juju decides.  And also we'd have to think carefully about how to deal with cases where we a charm dev has manually attached some storage prior to calling begin_with_initial_hooks.  My inclination right now is to just leave it as is require devs to explicitly add storage for their tests.
