### ISSUE TITLE
Allow (or document) Container.push behavior on overwrite

### ISSUE THREAD

**Issue by paulomach** [canonical/operator#752]
## Issue

`Container.push` currently does not allow file overwriting, but the behavior is not documented in docs.

## Suggestion

1. Add a boolean `overwrite` flag that when `True` test if path exists and remove it before pushing.
2. Update docs about overwrite behavior.

**Comment by benhoyt** [comment]
@paulomach I can't reproduce this locally. I'm running the Pebble server/daemon in one terminal:

```
$ PEBBLE=~/pebble go run ./cmd/pebble run
...
```

And then using the test Pebble CLI to execute a `push`, like so:

```
$ PEBBLE=~/pebble python3 -m test.pebble_cli push ./setup.py /home/ben/w/pebble/setup.py
wrote ./setup.py to remote file /home/ben/w/pebble/setup.py
$ PEBBLE=~/pebble python3 -m test.pebble_cli push ./setup.py /home/ben/w/pebble/setup.py
wrote ./setup.py to remote file /home/ben/w/pebble/setup.py
# modify ./setup.py
$ PEBBLE=~/pebble python3 -m test.pebble_cli push ./setup.py /home/ben/w/pebble/setup.py
wrote ./setup.py to remote file /home/ben/w/pebble/setup.py
# changes appear in /home/ben/w/pebble/setup.py
```

I can do the push successfully many times, and when I make changes in the source, the destination updates fine.

Are you able to send a repro for the case you're seeing, and the error messages you get?

**Comment by rwcarlsen** [comment]
This is because another process has `resolv.conf` opened - the file is currently in use and can't be removed/overwritten.  You can `lsof | grep 'resolv.conf'` to check what processes are using it.

**Comment by paulomach** [comment]
Hey @rwcarlsen , that's was my initial thought also, but there's no process owning the file. 
Running `lsof` does not show any process with the file open ([link to pastebin](https://pastebin.canonical.com/p/xN6C2zGsJy/))
And this can be reproduced to others containers files, not only `resolv.conf`.

**Comment by rwcarlsen** [comment]
Sounds like this might be the issue: https://stackoverflow.com/questions/60549775/device-or-resource-busy-when-i-try-move-etc-resolv-conf-in-ubuntu18-04-how

**Comment by rwcarlsen** [comment]
It's probably worth mentioning in docs somewhere that bind mounts for files will interfere with workload-side file operations.

**Comment by benhoyt** [comment]
Yeah, let's update the push docs to mention this gotcha and perhaps suggest a workaround for locked file / bind mount cases ("use Container.exec for full control" or whatever).
