### ISSUE TITLE
Framework Attribute Name

### ISSUE THREAD

**Issue by dshcherb** [canonical/operator#76]
`self.framework` seems like a long variable to type to me:

- `self.framework.observe(self.on.config_changed, self)`
- `self.framework.model.config['server_name']`

I would like to discuss potential shorter alternatives before this is carved in stone - maybe we can come up with something short and straightforward.

I think of this framework as:

- A charm runtime library;
- A **base** library for building charms.

Thus, I have the following candidates:

- `self.rt`
   - `self.rtl` ~ "Runtime Library"
   - `self.rte` ~ "Runtime Environment"
   - `self.crt` ~ "Charm Runtime"
- `self.base`
- `self.f` and `self.fw` crossed my mind as contractions of `framework` as well.

`self.rt` is short and the two characters are next to each other on a QWERTY keyboard.
`self.base` has a potential of being confused with the base class concept.
`self.f` and `self.fw` correspond to the current type name `Framework`.

As this is a rather subjective topic any feedback is appreciated.

**Comment by niemeyer** [comment]
The `self.framework` name feels pretty reasonable to me. It's something that reminds of the framework project itself (Operator Framework), it's unlikely to conflict with user code, and it's indicative of its role and behavior of that class in the project.

We can surely rename, but all the suggestions above seem detrimental to those points. They're vague, easy to conflict with, and not indicative of the object purpose.

Happy to reevalute this with other suggestions, and happy to talk in our call, but so far these suggestions don't feel like an improvement.
