### ISSUE TITLE
Do not log "legacy hook does not exist" for sidecar charms

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#761]
For every event, our logs always include a line that is (probably?) not relevant for sidecar charms:

> `Legacy hooks/(whatever) does not exist.`

https://github.com/canonical/operator/blob/979e86ca7ceb2be0dd134c0995f85abfe661c391/ops/main.py#L252-L255

Would it make sense to have this disabled when it is not relevant?

**Comment by jnsgruk** [comment]
I'm not sure it's strictly always not relevant. IIRC one can still add files in a hooks directory even for a sidecar charm... I've never seen it done, but it's supported nonetheless

**Comment by sed-i** [comment]
This proposal is better received as part of #796 :)
Closing.
