### ISSUE TITLE
Testing the action event

### ISSUE THREAD

**Issue by rgildein** [canonical/operator#762]
Right now there is no option how to test action event with Harness.
I believed it should be added as a feature and if I'm not mistaken, it could be an easy task.

Example, how I'm testing it now:
```python
os.environ["JUJU_ACTION_NAME"] = "<action-name>"
harness.charm.framework.model._backend.action_get = mock_action_get = MagicMock()
harness.charm.framework.model._backend.action_set = mock_action_set = MagicMock()
harness.charm.framework.model._backend.action_fail = mock_action_fail = MagicMock()
harness.charm.on.<action-name>_action.emit()
```

**Comment by rwcarlsen** [comment]
This should be pretty straight forward.  We'll need to add something similar to `Harness.update_config` that allows tests to set what the action params/args are when the event is triggered - e.g. `harness.run_action(*args)`.  And then implementing action-get/set/etc funcs for the testing backend.

**Comment by PietroPasotti** [comment]
I still have to implement this in scenario as well, good to keep in mind :)

**Comment by benhoyt** [comment]
For the record, this would still be very useful. Also for the record, Pietro has now included this in Scenario.

@tonyandrewmeyer is going to try to tackle this in the next few weeks.
