### ISSUE TITLE
docs: explain transactional nature of hooks/events

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#767]
It's not clear from the docs how the juju "world" is viewed and interacted with.  For example, when setting status, changes within a single hook invocation are not realized to the juju world - the changes are not committed/public until the hook finishes (successfully).  Another concept is that the state of relation data and config is current as of the _start_ of an event hook.  There may be a few places where details like this are mentioned in passing (I couldn't find much), but we should probably make these concepts more prominent.  I've encountered questions along these lines several times (even had them myself).

**Comment by PietroPasotti** [comment]
Sounds like something we should clarify in https://discourse.charmhub.io/t/a-charms-life/5938 as well as https://discourse.charmhub.io/t/talking-to-a-workload-control-flow-from-a-to-z/6161

as for in-code documentation, I'm wondering where we could be writing this information...

**Comment by PietroPasotti** [comment]
I worked out this representation. It splits a charm's execution in three phases - setup (charm inits), observers run (all registered event handlers execute) and commit (charm tears down, framework on.commit() fires), ops exits.

It attempts to capture what data is fetched when, and whether it is or it is not cached in its way in or out of the charm 

![image](https://user-images.githubusercontent.com/6230162/185070885-6d7b067f-5dbd-4f4f-b263-9c2e0d17a54c.png)

Feedback @jameinel ?

**Comment by PietroPasotti** [comment]
I also added this and some notes on synchronization to https://discourse.charmhub.io/t/talking-to-a-workload-control-flow-from-a-to-z/6161 which felt like the most appropriate place for this information. Once we're happy with it, we could push some of it to docstrings

**Comment by rwcarlsen** [comment]
I thought that relation data views are locked-in/snapshotted on the juju side when a hook starts (maybe I'm mis-remembering though?).  The diagram provides some clarity, but I think still leaves room for misunderstanding without careful inspection.  Not sure how to improve though - sorry for my lazy comment :P

**Comment by PietroPasotti** [comment]
I'm pretty confident `RelationDataContents(LazyMapping)` is triggering relation-get the first time you attempt to `__getitem__` on it

```python

    def __getitem__(self, key: str) -> str:
        return self._data[key]
        
    @property
    def _data(self) -> Dict[str, str]:
        data = self._lazy_data
        if data is None:
            data = self._lazy_data = self._load()
        return data

    def _load(self) -> '_RelationDataContent_Raw':
        """Load the data from the current entity / relation."""
        try:
            return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
        except RelationNotFoundError:
            # Dead relations tell no tales (and have no data).
            return {}
```

**Comment by rwcarlsen** [comment]
Yes, but I think the juju agent still provides you a snapshot of the (relation data) state from when the hook started running - the agent doesn't continue to live-update the relation data it presents via hook tools as the hook execution proceeds.  @jameinel - is this accurate?

**Comment by PietroPasotti** [comment]
Ah, in that sense. That I don't know :)

**Comment by benhoyt** [comment]
I've created PR https://github.com/canonical/operator/pull/1029 to tweak the docstrings for status. In addition to Pietro's docs (and the new collect-status, which is documented as operating at the end of the hook already), we can open more specific issues for doc fixes as they come up.
