### ISSUE TITLE
Add runtime warning if user forgot to override `snapshot/restore` in EventBase subclasses.

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#769]
Typically, when you inherit EventBase and add some instance attributes

```python
class MyEvent(EventBase):
    def __init__(...):
        self.a = 42
```

it is because you expect `self.a` to be accessible from the event instance in your event handler. However, since all events get snapshotted and restored before being fired, that is not so. Docstrings warn of this behaviour but further there is no runtime warning or way to check that the methods have been overridden.

**Comment by benhoyt** [comment]
Just doing some issue cleanup: looking over the rejected implementation at #770, I'm not sure there's a straight-forward way to do this without false positives and rather dirty code. I'm not sure it's worth it. Our documentation on [`EventBase`](https://ops.readthedocs.io/en/latest/#ops.framework.EventBase) is clear: "Inherit this and override 'snapshot' and 'restore' methods to build a custom event." Happy to revisit if we think up a more robust approach in future, but I think that's enough for now.
