### ISSUE TITLE
Add ability to run observed event ONLY on Juju leader

### ISSUE THREAD

**Issue by marcoppenheimer** [canonical/operator#774]
## Reasoning
It's very common to have the first part of any event handler to be ```
    if not self.charm.unit.is_leader():
        return
    ```
Usually this is because the handler sets app data, but there can be other reasons why you might want to only run on leader.

Although it's small, it would be nice to have some functionality to avoid this.

## (IDEA) - Maybe a decorator?
I have a pretty crappy decorator that I wrote that looks roughly like the following:

```python
def leader_check(func: Callable) -> Any:
    def check_unit_leader(*args, **kwargs):
        if not kwargs["event"].unit.is_leader():
            return
        else:
            return func(*args, **kwargs)

    return check_unit_leader

@leader_check
def _on_relation_joined(self, event):
    set_app_data()
```

but that doesn't run on every event. It would be nice if we could reduce the leader-checks overall in some way.

**Comment by rwcarlsen** [comment]
The `event.unit` attribute (which is only on relation events) refers to the remote application unit that triggered the event.   You would probably want `kwargs["event"].framework.model.unit.is_leader()`.  @PietroPasotti and others have spent some time thinking about similar needs/issues.  We'll keep this suggestion on our radar - it's a good thought.

**Comment by sed-i** [comment]
There are scenarios in which only some parts are leader-guarded, [for example](https://github.com/canonical/grafana-k8s-operator/blob/a2db8772c929ce0d1c91cffc78052341c948f0df/lib/charms/grafana_k8s/v0/grafana_source.py#L418):

```python
    def _set_sources(self, rel: Relation):
        """Inform the consumer about the source configuration."""
        self._set_unit_details(rel)

        if not self._charm.unit.is_leader():
            return

        logger.debug("Setting Grafana data sources: %s", self._scrape_data)
        rel.data[self._charm.app]["grafana_source_data"] = json.dumps(self._scrape_data)
```

So we'd end up either using both the decorator and the explicit form, or, refactor the function into two function, perhaps artificially.

At some point I tried to [generalize](https://github.com/canonical/cos-configuration-k8s-operator/issues/12) this concept to precondition decorators:

```python
    @defer_unless(network_ready, WaitingStatus("Waiting for ip address"))
    def _on_alertmanager_pebble_ready(self, event: ops.charm.PebbleReadyEvent):
        # ...

    @defer_unless(network_ready, WaitingStatus("Waiting for ip address"))
    @skip_unless(config_valid, BlockedStatus("PagerDuty service key missing"))
    def _on_config_changed(self, event: ops.charm.ConfigChangedEvent):
        # ...
```

but this was abandoned due to insufficient flexibility.

**Comment by rwcarlsen** [comment]
There are definitely subtleties.  I think there is potential in this space to provide some helpful tools.  I'm just not sure what they should look like yet.

**Comment by benhoyt** [comment]
I'm not in favour of decorators and suchlike for this. I think `ops` should reflect the Juju model pretty directly, and I think we should use the simple and straight-forward version:

```python
if not self.charm.unit.is_leader():
  return
```

If charmers are using this a ton and really want to make their own decorator for this, `ops` won't stop them.
