### ISSUE TITLE
Harness.update_relation_data should complain if you pass anything but Dict[str, str]

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#778]
I just realised it's totally fine to do 
`harness.update_relation_data(foo, bar, {'a': 42, 'b': {1:2}})`

and then, without flinching, you get it back:
`relation.data[foo] == {'a': 42, 'b': {1:2}}`

I think the least we should do is type the kwarg key_values to be Dict[str,str] instead of Mapping (on my way), but we should consider being more strict in validating that data.

**Comment by rwcarlsen** [comment]
Agree - we should do more validation/checking here.  Rather than quietly deferring until later and letting an error crop up later.

**Comment by pengale** [comment]
+1. It'll cause errors pretty quickly, but it would be nice if we had a nice, clean, helpful error message at the time that the params are passed.
