### ISSUE TITLE
Not v4 UUID in `_TestingModelBackend`

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/operator#779]
## Description

In `_TestingModelBackend` `__init__` method  [we have](https://github.com/canonical/operator/blob/main/ops/testing.py#L1094):

```python
self.model_uuid = 'f2c1b2a6-e006-11eb-ba80-0242ac130004'
``` 

This UUID is used by Harness when creating a model. This UUID is v1.

```python
>>> uuid.UUID("f2c1b2a6-e006-11eb-ba80-0242ac130004").version
1
```

The problem with this is that [Juju generates UUID v4](https://github.com/juju/utils/blob/master/uuid.go#L62):

```go
// NewUUID generates a new version 4 UUID relying only on random numbers.
func NewUUID() (UUID, error) {
	uuid := UUID{}
	if _, err := io.ReadFull(rand.Reader, []byte(uuid[0:16])); err != nil {
		return UUID{}, err
	}
	// Set version (4) and variant (2) according to RfC 4122.
	var version byte = 4 << 4
	var variant byte = 8 << 4
	uuid[6] = version | (uuid[6] & 15)
	uuid[8] = variant | (uuid[8] & 15)
	return uuid, nil
}
```

So, if you have a [lib or a charm that validates](https://github.com/canonical/observability-libs/issues/16) UUIDs [unit tests will fail](https://github.com/canonical/prometheus-k8s-operator/runs/6889022732?check_suite_focus=true#step:5:567)

## Possible solution

Change `self.model_uuid` with a hardcoded UUID v4, for instance:

```python
self.model_uuid = 'f2c1b2a6-e006-41eb-ba80-0242ac130004'
``` 

```python
>>> uuid.UUID("f2c1b2a6-e006-41eb-ba80-0242ac130004").version
4
```
Or, use the python `uuid` module to generate the value on the fly

```python
self.model_uuid = str(uuid.uuid4())
```

**Comment by rwcarlsen** [comment]
This seems like a good suggestion.  I'd lean toward just choosing a static v4 uuid rather than having it dynamically generated.

**Comment by Abuelodelanada** [comment]
> This seems like a good suggestion. I'd lean toward just choosing a static v4 uuid rather than having it dynamically generated.

Using a static v4 uuid led us to a very simple PR... but in the other hand having it dynamically generated it's more realistic in terms that mimics better Juju behaviour....

Anyway I have no strong opinions here. I can open a PR with one or other approach.

**Comment by Abuelodelanada** [comment]
> It is reasonable to move to uuid.uuid4, but I have to ask why you would care to validate the UUID vs it being a strictly opaque token that gets passed around when needed. John =:->


We validate uuid in our [`JujuTopology` lib](https://github.com/canonical/observability-libs/blob/main/lib/charms/observability_libs/v0/juju_topology.py#L90) because you can create a JujuTopology object from a charm (in this case there is no need to validate UUID) OR you can create a JujuTopology object from a dictionary that we do not necessary trust.
