### ISSUE TITLE
Better error messages on permission errors with accessing relation databags

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#784]
In non-peer relations, a unit cannot read or write its own application's databag, which results into authorization errors.
However, those errors surface in unexpected places which can confuse developers:

```
self.unit.is_leader() # False
self.relation.data # -->  ModelError("ERROR permission denied")
self.relation.data[relation.app]  # {}
self.relation.data[self.app]  # -->  ModelError("ERROR permission denied")
self.relation.data[relation.app]['foo'] = 'bar' # -->  ModelError("ERROR permission denied")
self.relation.data[relation.units[0]]['foo'] = 'bar' # -->  ModelError("ERROR permission denied") 
```

goal:
```
self.unit.is_leader() # False
self.relation.data # RelationData(local_app: <N/A>, local_unit: {...}, remote_app: {...}, remote_unit: {...}) 
self.relation.data[relation.app]  # {}
self.relation.data[self.app]  # -->  ModelError("ERROR permission denied: non-leader units cannot read or write their own application's databag.")
self.relation.data[relation.app]['foo'] = 'bar' # -->  ModelError("ERROR permission denied: cannot write databags of remote applications")
self.relation.data[relation.units[0]]['foo'] = 'bar' # -->  ModelError("ERROR permission denied: cannot write databags of remote units"") 
```

**Comment by rwcarlsen** [comment]
Relatedly, when trying to print or get a repr on the relation data, ops needs to skip trying to access local app data for non-leader units in order to avoid these errors.

**Comment by jameinel** [comment]
For the "non-leader units cannot read or write" it can be useful to also use a name there, rather than just a generic error string. `"mysql/1" is not a lead unit, and cannot read the application data bag of "mysql"`
I'm not trying to bikeshed a lot, just trying to point towards "can we include names" for users understanding.
