### ISSUE TITLE
Better error on attempting to set a broken relation data; facilitate guarding

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#793]
If you attempt to set relation data on a relation-broken hook, you'll get 

```ops.model.ModelError: b'ERROR cannot read relation application settings: permission denied (unauthorized access)```
Which is confusing and already tracked on #784

When it came to fixing the error, I thought of all patterns I've seen; from setting a `self._is_relation_departed=True` flag, to having dedicated code paths, passing down kwargs etc... I thought, wouldn't it be nice to have a relation status?

```python
if self.unit.is_leader() and relation.status.name != 'broken':
   relation.data[self.app][foo] = bar
```

I feel that there is something of a relation Status in the works (is there?), so I'm not sure if this would be compatible with that. Food for thought?

**Comment by benhoyt** [comment]
This will be solved with #940: `Relation.broken`, though we may go with `Relation.active` or `Relation.status` (enum) instead.
