### ISSUE TITLE
Operator Framework Not Working on Xenial

### ISSUE THREAD

**Issue by tlm** [canonical/operator#798]
Hey Guys,

Trying to deploy the ubuntu charm recently and seeing it fail in the install hook with the following:

```
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install Traceback (most recent call last):
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "./src/charm.py", line 7, in <module>
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     from ops.charm import CharmBase
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/__init__.py", line 43, in <module>
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     from . import charm  # noqa: F401 (imported but unused)
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/charm.py", line 22, in <module>
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     from ops import model
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/model.py", line 1239, in <module>
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     class Container:
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/model.py", line 1395, in Container
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     level: Optional['pebble.CheckLevel'] = None) -> 'CheckInfoMapping':
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     return Union[arg, type(None)]
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     dict(self.__dict__), parameters, _root=True)
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 512, in __new__
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     self._eval_type(globalns, localns)
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     eval(self.__forward_code__, globalns, localns),
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install   File "<string>", line 1, in <module>
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install AttributeError: 'property' object has no attribute 'CheckLevel'
```

Looks to be an issue with Python 3.5. Possible to get a fix for this for Juju testing 2.9 testing purposes.

Ta
tlm

**Comment by benhoyt** [comment]
Thanks for the report, @tlm. It's very strange that our unit tests, which run successfully on Python 3.5, aren't catching this ([for example](https://github.com/canonical/operator/runs/7217384819?check_suite_focus=true)).

This is happening because the type annotations are being evaluated on import, and `Optional` is trying to look up `pebble.CheckLevel`. But the `pebble` object referenced is the `Container.pebble` property, not the imported `pebble` module.

In addition, Python changed type annotations from evaluated-on-import to lazily-evaluated-if-needed in Python 3.7, I believe ... though I think it was only turned on by default in 3.10. See [What's New In Python 3.7](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations).

I don't understand why. When I install Python 3.5 locally and run the following repro script, it works fine (i.e., it's not evaluating the annotations).

```python
import collections
from typing import Optional

class Cls:
	@property
	def collections(self):
		return None
	
	def f(self, x: Optional['collections.Counter']):
		print('f', x)

Cls().f(collections.Counter())
```

@PietroPasotti, we need to figure out why our unit tests aren't catching this. Pyright should also catch it, as it's a bug in the types (FWIW, I just tried Mypy, and it does catch this ... along with a whole host of other things). It looks like Pyright is incorrectly handling the scope of `pebble` -- differently to how Python itself does it.

**Comment by benhoyt** [comment]
FWIW, the line numbers in `typing.py` in the traceback don't match those of my version of Python 3.5 at all.

```
unit.ubuntu-xenial/0.install   File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
unit-ubuntu-xenial-0: 08:17:32 WARNING unit.ubuntu-xenial/0.install     return Union[arg, type(None)]
```

The `return Union[arg, type(None)]` is on `typing.py:846` on my install. Might be a different patch version (I'm running 3.5.9).

Ah yep, sure enough. The version in Xenial is likely 3.5.2, as the line numbers for 3.5.2 matches up exactly: https://github.com/python/cpython/blob/v3.5.2/Lib/typing.py#L649 ... boy, they made significant changes to `typing.py` between patch versions, and it's breaking us here. That seems strange!

Clearly we need to fix the issue (and the type checking), though I'm not sure if we can run the unit tests on 3.5.2 exactly to match Xenial.

**Comment by pengale** [comment]
Thanks for the detective work, @benhoyt!

Zooming out a bit, there is definitely a class of problems that show up when running tooling on an unpatched cloud image from an older release. We probably need to make sure that our unit tests run on Python 3.5.2 (if we can), along with the default Python version on bionic, focal, etc.

**Comment by PietroPasotti** [comment]
I agree with the diagnosis, we need to tighten the screws on our CI it seems...
I didn't know that mypy and pyright diverged that much, but I heard that there's no way to happify both.

**Comment by pengale** [comment]
It might be a better idea to just add a smoke test to ops, which deploys a minimal charm on various substrates, and waits for active status.

It's probably sufficient to be able to run it manually as a first step. I'm working on a draft of something now ...

**Comment by sed-i** [comment]
Perhaps related:
The [static job](https://github.com/canonical/operator/blob/4ffc12569dc576d2a9f9f44269b77616b15dc430/.github/workflows/framework-tests.yaml#L26) runs on python 3.10 ([example](https://github.com/canonical/operator/runs/7277665006?check_suite_focus=true#step:3:6)).

**Comment by rwcarlsen** [comment]
Ugh - can't even compile python 3.5.2 on my local ubuntu 21.10 - python needs libssl1.0 (not 1.1) let's see if I can disable the cpython ssl extensions...

**Comment by chanchiwai-ray** [comment]
As per the problem, can we just change the property name to something other than `pebble` such as `pebble_client`? Just to make all python version happy about this.

**Comment by benhoyt** [comment]
@chanchiwai-ray We can't just change the property name -- it's part of the public/documented interface, so that would be a backwards-incompatible change for charms.
