### ISSUE TITLE
Disappearing hook deferral problem

### ISSUE THREAD

**Issue by rwcarlsen** [canonical/operator#806]
This is a theoretical problem that I haven't actually tested out.  But it seems like it is possible for a hook observation call - for example `self.framework.observe(...)` to be run conditionally (e.g. inside an if-block).  If this happens it is possible for that registered hook callback function to defer an event and then when the deferred event is retried in the future, the observe call doesn't run (e.g. the if condition changed).  Then our deferred event cannot be re-dispatched and we get errors/problems.  What should we do?

**Comment by benhoyt** [comment]
I think this is correct, but basically the answer is "don't do this". It's rare (and recommended against) to have conditional `framework.observe` calls, and we're also even thinking of deprecating defer more generally.
