### ISSUE TITLE
testing storage is somewhat broken

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#819]
There is a bug in the testing backend:
![image](https://user-images.githubusercontent.com/6230162/186390695-fab55d65-6592-4140-b83b-d55e8af328e0.png)

`include_detached` is namely not used and the code behaves as if it was always True.
I couldn't find any tests for it, in fact.

Attempting to fix it 'the obvious way', i.e.
```python
        return list(index for index in self._storage_list[name]
                    if (include_detached or self._storage_is_attached(name, index)))
```

Breaks the existing unittests, so there are more issues downstream.

**Comment by PietroPasotti** [comment]
I think the issue is that the harness does not drop a snapshot of the newly-added storage on `attach_storage` calls. When the storage-attached event is emitted, it attempts to load a snapshot that doesn't exist.
![image](https://user-images.githubusercontent.com/6230162/186392117-e46ba3f0-5e59-4507-b56b-c1e8f9bf6eb1.png)

**Comment by rwcarlsen** [comment]
A meta comment here - I'm an old guy who prefers text-based code snippets over screenshots :P
