### ISSUE TITLE
Consider renaming `emitter` in `EventsBase`

### ISSUE THREAD

**Issue by dshcherb** [canonical/operator#82]
`emitter` parameter name has a different meaning in `EventsBase` (parent, e.g. CharmBase instance) and `BoundEvent` (EventsBase instance).

**Comment by dshcherb** [comment]
@johnsca @jameinel

**Comment by johnsca** [comment]
Specifically in https://github.com/canonical/operator/blob/master/ops/framework.py#L225-L230 the `emitter` is actually the parent instance and is in fact only used to be passed into the constructor as the `parent` param.  I vote for changing that from `emitter` to `parent` (and `emitter_type` to `parent_type`).

**Comment by johnsca** [comment]
It's also worth noting that the `EventsBase` instance (the `on`) is the actual emitter in that case, not the charm instance.

**Comment by niemeyer** [comment]
The name of the _emitter_ variable is semantic in the context of EventsBase. Every framework _Object_ may have a parent. But this is an EventsBase, supposed to handle boilerplate for emitting events for a certain object. Which object?  The emitter, which we receive via the decorator protocol on the `__get__` method. As such, the fact we _want_ an emitter as the parameter of that function is relevant, and makes the code more readable than if it was just another parent. 

Looking at `BoundEvent`, it seems to me that the exact same is true. The emitter there is the object emitting events.

Please do raise the issue again if that's off in any way. For now, I'm tentatively closing the issue as it all seems to make sense.
