### ISSUE TITLE
ExecProcess.wait_output can leak a 'socket.timeout' exception

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#826]
As seen here:
https://bugs.launchpad.net/juju/+bug/1989004
https://paste.ubuntu.com/p/KzS4r2PVV2/

The definition of `wait_output` is that it waits up to 'timeout' seconds for the response of the requested process, but if you pass a `timeout` of None, it will wait indefinitely.
The traceback looks like the code is trying to interact with the Pebble API for Wait Change (`_wait_change_using_wait` and `_wait_change`), but while trying to make the request against pebble it is getting a socket.timeout (`_request_raw', ... `http._read_status`)

Some other bits of note:

1. The time from the previous log message to the uncaught exception is 13s. The actual command being run likely takes about 3s (though the system might be under additional load). Either way, 13s is kind of an odd time for a socket.timeout
2. We do set a timeout on the Unix Socket here: https://github.com/canonical/operator/blob/main/ops/pebble.py#L229
I'm not positive where that timeout comes from, though presumably it is because we are passing a timeout to the do_open.
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/pebble.py#L1553
3. pebble.Client has a standard timeout of 5s for any conversation with Pebble:
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/pebble.py#L1469
I believe the intent for it is: "If we have sent a request to pebble, and it hasn't responded within 5s, loop around again and poll some more".
4. `_raw_request` does have a lot of handling of various bits
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/pebble.py#L1554
notably, none of those are socket.timeout.
5. It is surprising that we are passing a socket.timeout to the _UnixSocketConnection but nowhere in the code do we ever handle `socket.timeout` that can happen because of that failure.

I don't know if this exec would ever fail: `container.exec('sleep 10; echo true')`. It may be that it should be handled by this code:
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/pebble.py#L1761

That code would seem to give us a buffer of 1s for pebble to respond to our request before the HTTP connection dies due to socket.timeout.
I wonder if under load the issue is that we aren't actually able to get pebble to respond in time. Imagine the scenario:

1. We set client.timeout to 5s, causing the HTTP + Unix socket to have a kernel managed 5s timeout
2. We run a command that is going to take 10s to complete
3. `_wait_change_using_wait` is going to compute that we should send pebble a message to wait up to 5-1=4s 
4. Since ExecProcess.timeout is None, `time_remaining` and `this_timeout` don't come into play.
5. We make a request from pebble to find out "what is the status of this change that I started, make sure you respond in 4s."
6. Pebble is actively polling internally, but sees that the sub process has not completed yet after 4.1s
7. Pebble is thrashing and just not able to return information within that 1s window, and the Kernel takes over triggering a socket.timeout.

I *think* we should trap socket.timeout (possibly in `_wait_change_using_wait`), and treat a `socket.timeout` as just another 'nope, the process hasn't completed yet, lets poll it one more time.'

I don't think there is an advantage to saying "well, Pebble failed to respond in the 1s window that we gave it, therefore we should crash the charm with an Error".

**Comment by jameinel** [comment]
Note also that while pebble.Client has a configurable timeout talking to pebble:
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/pebble.py#L1469

That is not exposed anywhere up the stack:
https://github.com/canonical/operator/blob/main/ops/model.py#L2466
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/model.py#L1373
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/model.py#L1946

So there is no way for a *charm* to tweak the default connection timeout to Pebble, without hacking the Ops library itself.

**Comment by jameinel** [comment]
Anyway, at a more fundamental level

Operator Framework is intentionally setting a socket timeout without charms explicitly asking for it.
https://github.com/canonical/operator/blob/16295e4828e37ed3d0b6de46e19c4b51e8f45116/ops/pebble.py#L248

but nowhere in the code is it handling socket.timeout, which happens as a result of settimeout.

**Comment by benhoyt** [comment]
@jameinel I know this has been a year (time flies!), but did you just end up working around this in your charm by catching `socket.timeout`?

I agree this should be fixed -- thanks for the thorough report.

**Comment by benhoyt** [comment]
Assigned to @IronCore864 to do together with the related doc fix here: https://github.com/canonical/operator/issues/1131
