### ISSUE TITLE
EventsBase instances can conflict

### ISSUE THREAD

**Issue by johnsca** [canonical/operator#83]
Because `EventsBase` overrides `handle_kind` at the class level, two instances assigned to the same parent will have conflicting handle paths, potentially causing events to collide and lead to duplicate events being emitted.  Instances attached to different parents will not have this issue, of course, so it's fairly limited in scope of impact.  The one use-case I can come up with for this would be for a component to have separate private and public event collections.  It would be fairly easy, though, to have the `handle_kind` driven by the attribute name rather than being hard-coded.

**Comment by niemeyer** [comment]
I don't actually understand the issue. Can you demonstrate such events colliding in any way that wouldn't be a developer mistake that could easily be achieved by similarly broken code anyway?

**Comment by niemeyer** [comment]
After a conversation online, I'm convinced this was a misunderstanding and is not a real issue, on the basis that the default `handle_kind` for an object is its type. Every object of that type will share the same _handle_kind_, and that's by design. Disambiguation happen via their the handle key.
