### ISSUE TITLE
App vs. unit inconsistency in `set_workload_version`

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#832]
`juju status` prints the workload version per app, not per unit:
```
App         Version  Status   Scale  Charm           Channel  Rev  Address        Exposed  Message
prometheus  2.33.5   active       2  prometheus-k8s             0  10.152.183.58  no       

Unit           Workload  Agent  Address      Ports  Message
prometheus/0*  active    idle   10.1.13.182         
prometheus/1   active    idle   10.1.13.171         
```

However:
- We use `self.unit` rather than e.g. `self.model` to set it: `self.unit.set_workload_version(version)`.
- The operation succeeds without a leader guard, i.e. a non-leader unit does not error for trying to set the workload version.

**Comment by PietroPasotti** [comment]
I think it'd be most consistent to do `self.app.set_workload_version`, rather than `self.model`. Maybe there are reasons behind the choice to keep it in `Unit` though? Does maybe @pengale know the history here?

**Comment by sed-i** [comment]
cc: @dstathis re: potentially needing leader guard.

**Comment by sed-i** [comment]
> I think it'd be most consistent to do `self.app.set_workload_version`, rather than `self.model`. Maybe there are reasons behind the choice to keep it in `Unit` though? Does maybe @pengale know the history here?

- Technically, workload version is indeed a per-unit property.
- Displaying a workload version for every unit in the status is redundant, most of the time.
- Perhaps juju keeps the app version string up to date from the leader unit?

If this makes sense for everyone then this is not a bug but a feature.

**Comment by dstathis** [comment]
* There could be a situation where not every unit is running the same binary but it would be exceedingly rare.
* In the event you did have different versions for different units, it would not be displayed by `juju status`
* It is possible to see the per unit workload version with `juju status --format`

Given all this, I think the way it is currently done seems appropriate. It is displayed as a single value but advanced users can see the per unit values. I'm still not sure where `juju status` pull the app workload version from. Is it just the leader version?

**Comment by sed-i** [comment]
Thanks. I think we can close this issue, as far as OF is concerned.
@PietroPasotti, @pengale ?

**Comment by pengale** [comment]
Agree that this is Working as Intended.

More generally, the Operator Framework views things from the perspective of an individual unit, while `juju status` displays things from the perspective of the model overall. It's perfectly appropriate for OF to set the workload version of the unit, and juju to make a decision about what to display based on the input from all the units. OF has a local scope; the juju cli client has a model scope.
