### ISSUE TITLE
Relation data aliases

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#834]
Relation data is central to charming, and in unit tests I often use something like

```python
    def app_data(self, rel_name: str):
        relation = self.harness.charm.model.get_relation(rel_name)
        return relation.data[self.harness.charm.app]
    
    def unit_data(self, rel_name: str):
        relation = self.harness.charm.model.get_relation(rel_name)
        return relation.data[self.harness.charm.unit]
```

I was wondering if OF should have something like this built-in.

**Comment by sed-i** [comment]
Yes,
- in unit tests, there is no `event`.
- in charm code, we often have a leader iterating over everything ([prom](https://github.com/canonical/prometheus-k8s-operator/blob/a161ac8529e64582d3d04c77cdd640637756afc4/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L883), [am](https://github.com/canonical/alertmanager-k8s-operator/blob/a518b17cadf76e0c29541975aaca79f4cb738835/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py#L290), [graf](https://github.com/canonical/grafana-k8s-operator/blob/19a0d38ba1784d631b140266dc88bf85f586cd3e/lib/charms/grafana_k8s/v0/grafana_source.py#L460)).

**Comment by PietroPasotti** [comment]
@sed-i And again you read my mind: https://discourse.charmhub.io/t/a-relation-data-wrapper-for-unit-and-integration-testing/7051
Also a related prototype that ended up being abandoned (but I secretly keep having high hopes for): https://github.com/PietroPasotti/relation-wrapper

**Comment by benhoyt** [comment]
Charm Tech discussed, and we would rather not implement this. It's a simple shortcut that you could easily factor out in your tests, if it's something that you're repeating over and over. Better to keep the Ops "model" simple and consistent, and users can write helpers if they want.
