### ISSUE TITLE
Need a way to abort charm execution

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#839]
As a charmer, I'd like a way to abort charm execution **from anywhere**.
Use case:
I have a charm with many event handlers, but regardless of which event we're in, I want the charm to do nothing and exit with blocked state if a certain precondition is not met, say, a certain config value is provided.
Right now I have to, for each event handler, add a check:
```
if not self.condition():
    self.unit.status = ...
    return
````

I could raise an exception in `__init__`, but that would leave the charm in error state.

I propose to add a `Framework.abort()` method that raises an exception that gets caught in `main` and terminates charm execution without committing any state (status will pass through because that's committed synchronously).

With that, I would only need to add these three lines:
```
# in MyCharm.__main__:
if not self.condition():
    self.unit.status=...
    self.framework.abort()
```

**Comment by jameinel** [comment]
If you are in a state where you don't want any processing done, isn't that
Error state, not Blocked?

**Comment by PietroPasotti** [comment]
I'm not sure that's always the case. 
If I have, say, a charm that cannot be scaled up, I could write:
```python
def __init__(...):
    if not self.unit.is_leader():
        self.status = Blocked('cannot scale this app')
        self.framework.abort()
```
I think that gives a cleaner message to the user, better than an error state and having to dig through the logs to find an exception stack trace that, at the end, says 'cannot scale this app'.

In traefik, for example, there is a 'required' config value, which until it is provided puts the charm in a waiting state. There I'd do:
```python
def __init__(...):
    if not self.config.get('foo'):
        self.status = Waiting('cannot scale this app')
        self.framework.abort()
```

**Comment by beliaev-maksim** [comment]
waiting on relation might be also the use case. Sometimes it even does not make sense to start the app without a relation, eg database.
so, you can do a check for relation, set waiting, exit without handling return values in multilayer functions

**Comment by PietroPasotti** [comment]
![image](https://user-images.githubusercontent.com/6230162/198290433-99a17415-6e59-4586-b368-f2488b52a14c.png)

apparently it has been in the air for quite a while

**Comment by benhoyt** [comment]
I don't quite understand the need for this: how does `framework.abort()` differ from `sys.exit(0)` (or `sys.exit(nonzero)` if you want an error signalled)?

**Comment by beliaev-maksim** [comment]
Check the proposed PR, you may want to commit existing changes and close connections

While direct exit will not exit gracefully

**Comment by PietroPasotti** [comment]
Maksim's PR is actually not exactly what I had in mind. 
What I was proposing is a `framework.abort(status:StatusBase=None)` that would exit immediately with code 0 without executing any further charm code.

For example, in `__init__`:

```python
if self.config_is_bork():
    self.framework.abort(status=BlockedStatus('config is bork'))
```

Without this, I'd have to prefix every single event observer with:
```python
if self.config_is_bork():
    self.unit.status = BlockedStatus('config is bork')
    return
```

**Comment by beliaev-maksim** [comment]
@PietroPasotti 
in your example you use `return`, which will not work in nested structures.

and I am afraid that just going immediately with system exit will non handle any storage commits, that were performed during runtime. Otherwise, you can indeed just do `sys.exit(0)` in your code.

or what is the difference?

**Comment by PietroPasotti** [comment]
Had a chat with @beliaev-maksim and we're on the same page.
Amending my proposal above, I think the way to go is:
```python
self.unit.status = BlockedStatus('config is bork')
self.framework.abort()
```

`framework.abort()` would raise a SysExit or some other special exception type that's caught at the root (`operator/main.py`) and ensure a clean exit (whatever that means now, or ten years from now).

**Comment by benhoyt** [comment]
What about doing this in your charm class's `__init__`:

```python
def __init__(self, *args):
    super().__init__(*args)
    if self.config_is_borked():
        self.framework.commit()  # if you want to save snapshots, commit, etc
        sys.exit()  # same as "raise SystemExit"
```

We could add a `Framework.abort()` method, but literally all it would do is `sys.exit()`. I think if it's called "abort" it *shouldn't* save/commit, because the name implies not doing that. If we want it to commit as well, I think it should be something like `Framework.exit()` or similar.

Speaking of which, are status updates immediate in any case, whether or not the framework executes successfully?

**Comment by benhoyt** [comment]
Yep, I just checked, and -- unlike relation data and so on -- `status-set` updates go through immediately (by design), whether or not the hook exits early, or even whether or not it succeeds. So we don't actually need the `self.framework.commit()` in my example above.

**Comment by beliaev-maksim** [comment]
Hi @benhoyt

Question here would be if we preserve the same code structure for the next ten years or not, because if we educate users to exit by themselves, then we are limited to try/except block only

Second, if I understood correctly,  the difference is also about committing or not. If we are taking about the status, then it looks to be not necessary. However, I think there could be scenarios where it is required and I think it is better to incorporate this logic. What do you think? 

Note, I will be happy to rename the method from `abort` to `exit`

**Comment by PietroPasotti** [comment]
@benhoyt for my best understanding of what happens when in terms of syncing with juju: see the second section of this doc https://discourse.charmhub.io/t/talking-to-a-workload-control-flow-from-a-to-z/6161

The logic of the code you wrote above is what we need, the issue is: do we want to expose a high-level callable that abstracts it, or do we leave it to the charmers to remember to call `framework.commit()` before they exit?

**Comment by beliaev-maksim** [comment]
in proposed PR we either face an error while committing and then non-zero happens and we end up in ErrorState, which most probably makes sense

or if commit is successful, then we proceed to `sys.exit(0)` -> which to above mentioned logic should let juju save the changes

**Comment by benhoyt** [comment]
@PietroPasotti Good explanation in your [doc](https://discourse.charmhub.io/t/talking-to-a-workload-control-flow-from-a-to-z/6161) about why status-set updates are immediate -- nice doc BTW!

I'm still not sure this is worth it. If we did want to add `Framework.exit()`, it's still debatable whether we want to commit by default. We could make it `Framework.exit(commit=True)` I guess.

But part of the reason I don't like it is it's hidden control flow (this function exits the program, and whatever statements after it won't be executed). I know `sys.exit()` does the same thing, but that's a well-known built-in function, so it can get away with it.

I recommend that for this use case we just encourage people to write `raise SystemExit` and document that pattern. It's raising an exception, so it's clear it's control flow. In your use case in `__init__` where you're just setting a status, that happens immediately, so you wouldn't even need to commit.

@jameinel What are your thoughts?

**Comment by PietroPasotti** [comment]
A precedent for the pattern of calling an exit function instead of raising an exception would be pytest's `xfail()`, which I like a lot. But I don't mind asking the user to raise `SystemExit` or a specific exception subclass we provide (probably better than overloading sysexit IMHO) if that feels more intuitive.

Or we could have the best of both worlds and do:

```raise self.framework.exit(commit:bool)```

(joking, but only half)

**Comment by beliaev-maksim** [comment]
what is about?
considering that sys.exit will be caught by the `main`

```python
    def exit(self, commit: bool = True):
        """Stop the execution of the framework and exit."""
        if commit:
            self.commit()
            
        sys.exit(0)
```

**Comment by beliaev-maksim** [comment]
@PietroPasotti @benhoyt 
what do you think about implementation as in https://github.com/canonical/operator/issues/839#issuecomment-1318370421 ?

**Comment by benhoyt** [comment]
@beliaev-maksim I like that most of all the versions so far. However, I'm just not convinced it's necessary.

If someone wants to exit early without committing, they can simply call `sys.exit()`, which has a well-documented meaning, both for Python and in the context of a hook (hook exiting with code 0 means "successfully ran hook"). That's what @PietroPasotti would use in his original use case, after updating the status to blocked.

If someone wants to commit and exit, they'll call `self.framework.commit()` followed by `sys.exit()`. Nice and explicit, and means people don't have to look up what our new function does.

What we could do is have a short section of documentation on this pattern in our Discourse docs, with an example use case like Pietro's "config borked" status blocked one. Want to take a crack at that, @beliaev-maksim?

**Comment by beliaev-maksim** [comment]
@benhoyt
I will add it as part of sdk tutorial and also add "how to" section on juju.is

I will let you review it once ready
