### ISSUE TITLE
Cache `Handle.__hash__()`

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#84]
Hashing a long chain of handles could get expensive. Handles are immutable and therefore the result of hashing operation could be cached and re-used.  

https://github.com/canonical/operator/blob/82d570e80faa14e9f8c586c58507b34283acba96/ops/framework.py#L46-L47

**Comment by niemeyer** [comment]
Some useful details when discussing performance:

1) What's the actual cost of that operation?
2) What's the cost of caching that value, in terms of memory and time?
3) How many times are we calling this function?

**Comment by niemeyer** [comment]
Tentatively closing. If we get actual data showing these numbers to be relevant, please let us know and we reopen it.

**Comment by timClicks** [comment]
My reasoning is that we are altering algorithmic complexity of fundamental data types[1]. Dictionaries back the representation of classes and hash maps are expected to provide O(1) operations. Hashing a chain of parent objects breaks that, because the number of operations now depends on the length of the chain.

The size cost would be pretty minor, about as small as Python will allow. It's a boxed PyObject containing an integer. 

[1]: "Fundamental" in the sense of being important to CPython.

**Comment by niemeyer** [comment]
Yeah, I get it, but this has the full smell and taste of early optimization. Don't get me wrong.. I'm not suggesting we should be writing wasteful code, but if we get to the point where we need to cache tuple checksums to squeeze out a few more microseconds, we're in the territory of performance optimization, and I'm sure there will be more serious things broken that need fixing by then.

The phase we're in right now is on creating an API we're happy to use, and happy to recommend.
