### ISSUE TITLE
framework.Object needs a better name

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#86]
Calling a type `Object`, even within a namespace, is bound to cause confusion. (Sidebar - "framework" is not an effective namespace). Colliding with `object` will alienate experienced programmers and will cause beginners to become trapped.

**Comment by niemeyer** [comment]
Yeah, might be good to have a better name, but we couldn't find any that would be better than Object so far. The conflict with _object_ doesn't bother me too much, because it's precisely the generality of _object_ that we're after here. That said, if we find a better term in time we can switch still.

**Comment by zicklag** [comment]
Brainstorming other ideas:

  - `Component`
  - `Thing`
  - `Element`

:slightly_smiling_face:

**Comment by chipaca** [comment]
It's been nearly 5 months and we haven't really found an alternative, despite this being constantly on our minds. I'm closing this, because it's apparent no better name is to be found, and at some point we just need to bite the bullet.

**Comment by timClicks** [comment]
Please reconsider. Any of the alternatives would be better than this. "Object" will clash with every programmer's mental model.

Closing the issue now prioritises the team over downstream developers.

**Comment by niemeyer** [comment]
> "Object" will clash with every programmer's mental model.
> Closing the issue now prioritises the team over downstream developers.

-- Tim, the guy that suggests naming it **Thing**

;)

**Comment by timClicks** [comment]
Fair point!
