### ISSUE TITLE
Project needs setup.py; otherwise IDEs are unable to import it

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#87]
The end-user ergonomics of the library are significantly impaired because of how it needs to be vendored into a charm's source code. Despite my best efforts with `sys.path` hacking, `git subtree` and symbolic links, I haven't been able to convince PyCharm to believe that `ops` is a valid Python package.

**Comment by niemeyer** [comment]
Being sorted out in #90.

**Comment by johnsca** [comment]
In PyCharm, right-click on the `lib/` directory and select `Mark Directory As` -> `Sources Root`.  Do the same for the `src/` directory. This seems to work for me,  using the patterns recommended in the README.
