### ISSUE TITLE
Rename project "charmed_ops"

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#88]
The project's name has gone through lots of churn already, but it's still not right. `ops` is far too generic. It will be impossible to search for and difficult to describe to others. `charmed_ops`, would work well. It's easy to say, retains the "ops"/"operator" motif, stays on brand with the rest of Canonical's offerings and says exactly what it does.

**Comment by niemeyer** [comment]
People I discussed this with find _ops_ shorter, cleaner, and sweeter, and I agree as well.

We won't reach consensus about naming.
