### ISSUE TITLE
Expose full metadata through `CharmMeta.raw`

### ISSUE THREAD

**Issue by agathanatasha** [canonical/operator#881]
Not all metadata fields are accessible through `self.meta` . The current workaround is to do `yaml.safe_load`. It would be useful to expose the full content.

[Discussion Reference](https://chat.charmhub.io/charmhub/pl/diq8qx8mypgimqk48yr1haayro)

**Comment by benhoyt** [comment]
Thanks for the report. I briefly discussed this with John and Jon S today, and while we're not averse to adding `CharmMeta.raw`, we don't necessarily want to make it easier to access things the charm probably shouldn't be accessing.

It seems to me the charm shouldn't be using the field `upstream-source`, so I'd like to understand the need for that a bit more clearly. What's your use case? Is that field needed in the charm itself, or in unit or other tests?

**Comment by agathanatasha** [comment]
The team wants to keep track of the database migration version ran using the image version in the peer relation databag.

**Comment by benhoyt** [comment]
Thanks for the info. We're not going to expose `CharmMeta.raw` right away, however (I understand you're moving on) if a member of your team wants to discuss a use case with a few more details, we'd be happy to reopen.
