### ISSUE TITLE
Missing README/docs link

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/operator#89]

**Comment by niemeyer** [comment]
Being sorted out in #90.

**Comment by ryan-beisner** [comment]
Wait, what?  The issue should remain open until the fix is actually committed.  Please re-open.

**Comment by niemeyer** [comment]
On Thu, Dec 19, 2019 at 2:41 PM Ryan Beisner <notifications@github.com> wrote:
> Wait, what? The issue should remain open until the fix is actually committed. Please re-open.

If you want the README, please do see the PR and help us out by reviewing its content.

If you want to argue about re-opening an issue whose entire content is "Missing README/docs link", I'm the wrong guy. :-)

Happy holidays to both of you.

**Comment by sparkiegeek** [comment]
> On Thu, Dec 19, 2019 at 2:41 PM Ryan Beisner [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Wait, what? The issue should remain open until the fix is actually committed. Please re-open.
> 
> If you want the README, please do see the PR and help us out by reviewing its content.
> 
> If you want to argue about re-opening an issue whose entire content is "Missing README/docs link", I'm the wrong guy. :-)

Heh, fair point - I was surprised when I saw that both were missing, and wanted to record it quickly before closing the tab.

I have editted the initial report to try to expand on my expectations

> 
> Happy holidays to both of you.

Likewise! :christmas_tree:

**Comment by ryan-beisner** [comment]
Apologies if I was terse in reply.  It's not my intention to cause a debate.  I'm looking for solid examples of usage and will track the branches and PRs where that is forming.
