### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by tinvaan** [canonical/operator#893]
Operator codebase contains a `pyproject.toml` and a `setup.py` file at present. Modern `pyproject.toml` specifications allow us to build `pip` packages without needing to define a setup module for invoking `setuptools`.

Read More -
- https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
- https://github.com/tinvaan/operator/pull/1#discussion_r1071713196

**Comment by benhoyt** [comment]
We're leaning towards not doing this *at present*, but Tony's going to look into it further and make an evaluation.

**Comment by tinvaan** [comment]
Have been away from the project for a while, let me know about the result of the evaluation. Happy to help with a PR, if needed.

**Comment by tonyandrewmeyer** [comment]
setup.py currently replaces `version.py`, which I believe is exactly the sort of thing pyproject.toml buliding is aiming at preventing (running arbitrary code). I think we would want to resolve #1039 (no so much bumping the fallback version but whether we want to keep the current system) before doing this ticket.

**Comment by benhoyt** [comment]
Possibly useful reading when we start on this: https://til.simonwillison.net/python/pyproject

**Comment by tonyandrewmeyer** [comment]
> Possibly useful reading when we start on this: https://til.simonwillison.net/python/pyproject

Simon also recently linked to [this post on moving off setup.py](https://gregoryszorc.com/blog/2023/10/30/my-user-experience-porting-off-setup.py/).
