### ISSUE TITLE
`push` with `make_dirs=True` does not create the nested subdirs and silently fails

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#898]
I am trying to push with nested dirs that do not exist:
```python
self._container.push(path, contents, make_dirs=True, encoding="utf-8")
# path is /mimir/ruler_storage/anonymous/juju_test-alert-propagation-nxl2_0badd9d0_avalanche-k8s.rules
```
However, the dirs are not created, the file is not pushed (and it silently fails), unless I first
`self._container.make_dir(..., make_parents=True)`

**Comment by benhoyt** [comment]
Hmm, the "silently fails" thing is very concerning. We've run into stuff like this before with permissions issues, but that would raise loudly. Do you have a minimal repro charm or branch of a charm that can repro this? Are there any errors or warnings at all in the logs?

**Comment by sed-i** [comment]
Not so minimal:
https://github.com/canonical/mimir-k8s-operator/blob/c8729f85c0ee33240fa78a60ac6f2f83ea4721e4/src/charm.py#L218
When that line is removed, the subsequent `self._container.push(path, rules, make_dirs=True)` has no effect.
I didn't see anything in the logs.

**Comment by sed-i** [comment]
[Here's a minimal repro](https://github.com/sed-i/empirical-charming/tree/feature/push-make-nested-subdirs/push-make-nested-subdirs), but it fails to reproduce: push works without `make_dir`.
Perhaps with mimir there is some interaction with the workload app. Not sure yet.

**Comment by benhoyt** [comment]
@sed-i Did you ever figure this out? If not, I'm tempted to close this as "can't repro", as the minimal case doesn't have the issue.

**Comment by sed-i** [comment]
Let's close this for now.
