### ISSUE TITLE
uncaught error in `Secret.get_info()`

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#899]
the following error appears while running the `owner` charm in [this demo bundle](https://github.com/PietroPasotti/secrets-demo-charms/tree/main)

![image](https://user-images.githubusercontent.com/6230162/216614436-164e80c9-0649-4d68-af38-a2ec516b83af.png)

**Comment by PietroPasotti** [comment]
I believe the culprit is model.py:1079. If the secret has a label and an ID, the hook tool will be called with both and complain.

**Comment by benhoyt** [comment]
I've fixed this in #900. I was thinking of releasing an ops 2.0.1 to fix this bug after that, however I probably won't, given that there's a Juju bug that prevents it anyway:

> However, due to https://bugs.launchpad.net/juju/+bug/2004672, when this is fixed you get a "secret not found" error when secret-info-get is used in the same hook as the secret-add, because secret-info-get is not looking at pending creates.
