### ISSUE TITLE
Fix type annotation issues with VS Code and generating docs

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#911]
There seems to be some inconsistency with our type annotations that's causing VS Code problems. From David Anderson, who raised this issue [here](https://docs.google.com/document/d/109MTW_hSb2PlJp5v9SvwFFNPdGpuKkluZ3NcXNbS6nI/edit):

> David: It would be good to limit the use of the Any type. E.g., self.unit.get_container().exec returns the Any type
>
> Me: In this specific case, exec() does not return Any, but ExecProcess
>
> David: It seems that the reason is that the import fails in VSCode because the ExecProcess is imported from pebble rather than ops.pebble in model.py. When I change the import from pebble to ops.pebble the type hint is correctly identified.
> 
> The other thing is that the class for the type hint (ExecProcess) is actually imported on line 63 where line 59 says from pebble import (..., ExecProcess, ...). Thats the line I had to change to from ops.pebble import (..., ExecProcess, ...) (other imports omitted), referring to model.py here
>
> The pebble import is on line 54, I'm not sure how that line interacts with line 59
> 
> if the type hint on line 2297 in model.py was changed to "pebble.ExecProcess" VSCode is fine with that too

**Comment by benhoyt** [comment]
@jdkandersson Can you please confirm this is fixed in VSCode on the main branch, by https://github.com/canonical/operator/pull/944 and https://github.com/canonical/operator/pull/942? I suspect it won't be an issue any more.

**Comment by jdkandersson** [comment]
Yes looks like this got fixed, thanks!
![Screenshot 2023-06-14 at 12 55 59 pm](https://github.com/canonical/operator/assets/51036209/d4db0a56-be42-401f-996e-bf588b5430eb)

**Comment by benhoyt** [comment]
Nice, thank you for checking!
