### ISSUE TITLE
Would it be possible to not return path to empty resources

### ISSUE THREAD

**Issue by mkalcok** [canonical/operator#912]
Hi,
as a title says, I think it'd be handy if there was a way to treat empty resource files as if there was no resource at all. Since there's [no way to define optional file resources](https://juju.is/docs/sdk/define-a-resource-for-your-charm) and Charmhub does not allow you to publish charms without resources attached, a lot of charms resort to attaching empty "dummy" resource in place of optional resources.
* [juju-lint](https://charmhub.io/juju-lint/resources/juju-lint)
* [kubernetes-control-plane](https://charmhub.io/kubernetes-control-plane/resources/kubectl)
* [vault](https://charmhub.io/vault/resources/vault)
* ...

Perhaps `Resources.fetch`
https://github.com/canonical/operator/blob/34e5dfb08251295c96cbfd3976c78b41c991b4ec/ops/model.py#L1649-L1659
could be modified to have parameter `raise_on_empty=False`. With this parameter set to `True` it would raise the same exception as when resource is not attached, if the resource file size is 0.

**Comment by benhoyt** [comment]
Can you provide a (moderately realistic) example of how this would be used in a charm with an optional resource? What would the charm do in case it's missing -- provide a default?

I'm unsure that raising would be the best thing to do here. Note that you can also use `resource.stat().st_size == 0` on the returned `Path` object to determine this directly.

**Comment by mkalcok** [comment]
The optional resources that I have in mind are usually snap files. So the charm flow is usually:

1. Check if snap file is attached as a resource
2. If yes, install snap from file
3. else, install snap from snapstore

I lately find myself often writing a helper function/property that fetches the path to resource file and then performs additional size check. This prompted me to suggest baking this functionality into the `Resources.fetch()` directly.

I suggested raising exception because [that's the current behavior when charm tries to access a resource that's not attached](https://juju.is/docs/sdk/access-a-resource-from-your-charm). So my suggestion basically is to add ability to treat "empty" resource files as if no file was attached at all.

**Comment by benhoyt** [comment]
Thanks for that. I don't love the overloading of the proposed API with a boolean flag that says to change the behaviour. I'd sooner add a new `Resources` API function. Here's the current way you'd do this, with your proposal and a couple of other options:

```python
# CURRENT:
path = resources.fetch('snapresource')
if path.stat().st_size != 0:
	run(['snap', 'install', path])
else:
	run(['snap', 'install', 'thesnap'])

# YOUR PROPOSAL:
try:
	path = resources.fetch('snapresource', raise_on_empty=True)
	run(['snap', 'install', path])
except NameError:
	run(['snap', 'install', 'thesnap'])

# ALTERNATIVE 1:
if resources.is_provided('snapresource'):
	run(['snap', 'install', resources.fetch('snapresource')])
else:
	run(['snap', 'install', 'thesnap'])

# ALTERNATIVE 2:
path = resources.fetch_non_empty('snapresource')
if path is not None:
	run(['snap', 'install', path])
else:
	run(['snap', 'install', 'thesnap'])
```

The proposed option doesn't seem clearer to me, and the two alternatives I've shown aren't much of an improvement either. IMO we should just stick to `.stat().st_size != 0` (and maybe document that idiom).

**Comment by benhoyt** [comment]
Ah yeah, `os.path.getsize()` seems nicer than `.stat().st_size`. (Though `size == 0` seems clearer than `not size > 0`.) Also, wouldn't the more likely error be `NameError`, the one that `fetch()` raises if the resource doesn't exist? (But maybe `resource_get` can raise `ModelError` too, or what fetch have already raised `NameError` at that point? I guess you could catch both.)

You could simplify slightly with:

```python
try:
    snap_path = self.model.resources.fetch("snapresource")
    if os.path.getsize(snap_path) == 0:
        raise NameError
    run(["snap", "install", snap_path])
except NameError:
    run(["snap", "install", "thesnap"])
```

Overall I'm still not sure the new API is worth it.

@jameinel What do you think about `Resources.fetch_non_empty`, which would raise `NameError` *either* if it didn't exist or it was a zero-length file?

**Comment by mkalcok** [comment]
Thanks for consideration.

> But maybe resource_get can raise ModelError too

Both exception can be raised by `fetch()`
* `NameError` - Resource with given name is not defined on the charm
* `ModelError` - Resource is defined but not attached.

**Comment by benhoyt** [comment]
Tony and I discussed this further, and we don't think the new API is worth it. It's easy to add the `os.path.getsize()` to detect this in the few places where it's needed.
