### ISSUE TITLE
Improve open_port / close_port docs

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#918]
The docstrings for [`open_port`](https://github.com/canonical/operator/blob/eb8e25a5314ca2063f4689fa829c8bdca652ce1f/ops/model.py#L605) and `close_port` have a bunch of Juju detail that probably shouldn't be here, and some of it isn't correct -- for example, the bit about "registering intent ... juju expose" is true for VM charms but not for K8s sidecar charms.

I think what we want to do here is improve our [Juju docs about open-port](https://juju.is/docs/sdk/hook-tool#heading--open-port) and then link to those, to avoid documenting too much Juju behaviour in `ops` docstrings.

**Comment by erik78se** [comment]
I'm trying to use this feature in "ops" but I don't know how to 

1. Detect that the "juju expose" or "juju unexpose"  has happened. Special events hooks?
2. How to use it, apart from what is obvious from the code - which isn't ideal.

**Comment by benhoyt** [comment]
@erik78se Sure, in the meantime, I'll try to answer those here:

1. I don't think there's a way to detect that, as that's an administrator concern, not a charm concern. The charm opens the port or ports, but then -- on virtual machine models -- the admin has to run `juju expose` to actually expose those port(s) to the outside world. For K8s models, the `juju expose` step isn't required (though on K8s ingress works differently, so the ports may or may not be exposed to the outside world, depending on how the K8s cluster networking is set up -- once again, admin-dependent).
2. Using `open_port` in charms is fairly straight-forward:

```python
class MyCharm(CharmBase):
    def _on_some_event(self, event):
        self.unit.open_port('tcp', 8080)
```
