### ISSUE TITLE
Update docs to recommend new import style

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#921]
Now that https://github.com/canonical/operator/pull/910 has been merged and released in ops 2.2.0, we should update our [SDK docs](https://juju.is/docs/sdk) and their examples charms to recommend the simpler approach of just using a single `import ops` (and `import ops.pebble` and `import ops.testing` where appropriate).

See also https://github.com/canonical/charmcraft/pull/1055, where we're updating the `charmcraft init` templates.

**Comment by benhoyt** [comment]
From sergiusens on Mattermost, regarding the charmcraft templates: "the template is only for init, so it should be fine to bump the min req and make the changes in charm.py".

**Comment by benhoyt** [comment]
Going to modify this to just "update docs", as I've opened a [separate PR on charmcraft](https://github.com/canonical/charmcraft/pull/1055) to track updating the charmcraft init templates, and I'm not going to have time to update the charms before I go away, so removing that item.

**Comment by tonyandrewmeyer** [comment]
Updated [the setup doc](https://discourse.charmhub.io/t/set-up-your-development-environment/7379) to fix the `tox` installation.

**Comment by tonyandrewmeyer** [comment]
Updated [first step of k8s charm tutorial to use the new style](https://discourse.charmhub.io/t/create-a-minimal-kubernetes-charm/7388)

(I'll submit PRs for the repo with the code once I'm done with all the changes).

**Comment by tonyandrewmeyer** [comment]
Updated [k82 charm tutorial config step to use the new style](https://discourse.charmhub.io/t/make-your-charm-configurable/7401)

**Comment by tonyandrewmeyer** [comment]
Updated [k8s charm tutorial version step to avoid bad versions of requests](https://discourse.charmhub.io/t/expose-the-version-of-the-application-behind-your-charm/7406)

**Comment by tonyandrewmeyer** [comment]
Updated [k8s charm tutorial integration section to use the new style, and a bit of help at the end for validating](https://discourse.charmhub.io/t/integrate-your-charm-with-postgresql/7414)

**Comment by tonyandrewmeyer** [comment]
Nothing required in the [preserve data section of the k8s tutorial](https://juju.is/docs/sdk/preserve-your-charms-data), although the repo branch will need the preceding changes.

**Comment by tonyandrewmeyer** [comment]
Updated [k8s tutorial action section to avoid the `raise SystemExit` technique (which I also edited out earlier)](https://discourse.charmhub.io/t/expose-operational-tasks-via-actions/7592)

**Comment by tonyandrewmeyer** [comment]
Nothing required in the [cos-lite section of the k8s tutorial](https://juju.is/docs/sdk/observe-your-charm-with-cos-lite)

**Comment by tonyandrewmeyer** [comment]
Adjusted [leader](https://discourse.charmhub.io/t/leader-ops-model-unit-is-leader/4464)

**Comment by tonyandrewmeyer** [comment]
Adjusted [scenario](https://discourse.charmhub.io/t/scenario/10583)

**Comment by tonyandrewmeyer** [comment]
Adjusted [integration](https://discourse.charmhub.io/t/integration/4465)

**Comment by tonyandrewmeyer** [comment]
Adjusted [accessing a resource](https://discourse.charmhub.io/t/how-to-access-a-resource-from-your-charm/5608)

**Comment by tonyandrewmeyer** [comment]
Adjusted [how to run workloads with your charm](https://discourse.charmhub.io/t/how-to-run-workloads-with-your-charm/4457)

**Comment by tonyandrewmeyer** [comment]
Adjusted [interacting with pebble](https://discourse.charmhub.io/t/how-to-interact-with-pebble/4554)

**Comment by tonyandrewmeyer** [comment]
Updated [best practices](https://discourse.charmhub.io/t/charm-development-best-practices/5396) - @benhoyt do you think there should also be a section in this doc that explicitly explains the "import ops" style?

**Comment by benhoyt** [comment]
Yeah, probably, but nothing big. Maybe even in the [first section](https://discourse.charmhub.io/t/charm-development-best-practices/5396#heading--programming-languages-and-frameworks) which mentions ops, just add a small paragraph like "The recommend way to import the library is to write `import ops` and then use it as follows [couple of lines of charm code]".

**Comment by tonyandrewmeyer** [comment]
The [machine charm tutorial](https://juju.is/docs/sdk/build-and-deploy-minimal-machine-charm) doesn't have any code in it, and instead refers to [Erik's repository of basic charms](https://github.com/erik78se/juju-operators-examples). I'll open a PR for adjusting those.

**Comment by tonyandrewmeyer** [comment]
@benhoyt other than the [one page I can't edit](https://discourse.charmhub.io/t/how-to-turn-a-hooks-based-charm-into-an-ops-charm/5657), I believe this is done now. Do you want to review any of this, or should I just close this as done?

**Comment by benhoyt** [comment]
I've had a very quick check of a few pages and they look fine, thanks! Just close when done.
