### ISSUE TITLE
consider adding `get_ingress_address` and/or `get_bind_address` shortcuts to `model.Unit`

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#939]
Right now, charm code needs to:

```python
my_bind_address = self.model.get_binding('<explicit-endpoint>').network.bind_address
my_ingress_address = self.model.get_binding('<explicit-endpoint>').network.ingress_address
```

which is a bit too verbose for such a simple and common use case.
We see that charmers struggle quite a bit to remember how to get to that data. 
Also, there is a (silently deprecated) `unit-get private-address` hook tool that could be used to get to the same data, which means confusion.

To simplify the process of accessing the data (and offer an unambiguous 'this is the way' to get to it), I propose adding to `ops.model.Unit` some shortcuts for getting bind and ingress addresses from an endpoint.

The API could look like:
```
def get_bind_address(self, endpoint:str) -> str: ...
def get_ingress_address(self, endpoint:str) -> str:...
```

Cfr [original discussion on MM](https://chat.charmhub.io/charmhub/pl/5ubj6xrnj38u7bfbzrytattigw)

**Comment by benhoyt** [comment]
Should this be on `Model` rather than on `Unit`? So it would be (for example):

```python
# old way
addr = self.model.get_binding('endpoint').network.bind_address

# new way
addr = self.model.get_bind_address('endpoint')
```

I'm not opposed to this change to make the common case simple and more visible (via code completion and so on).

**Comment by PietroPasotti** [comment]
aren't those addresses different for each unit? 
Also the other (now deprecated) mechanism for getting that address is called `unit-get`.

**Comment by benhoyt** [comment]
I'll have to think about and test that. The way I was thinking about it was simply: `get_binding` is currently a method on `Model`, so `get_bind_address` / `get_ingress_address` should be too.

**Comment by benhoyt** [comment]
I've thought about this a bit more, and I agree the current API is awkward, but I'd prefer not to add more than one way to get to this info.
