### ISSUE TITLE
Project layout convention should be to symlink hooks/start,  rather than hooks/install to charm.py

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#94]
The install hook is not run for charms run within Kubernetes. Using `hooks/install` as the default entrypoint means that we'll need a second set of conventions/docs for Kubernetes.

**Comment by niemeyer** [comment]
The install hook should run in Kubernetes as well as discussed in the last sprint, and if we expect to handle a hook in the framework, it needs to be there by the time it's called. Calling the framework after install has run means never handling install.

**Comment by timClicks** [comment]
But it doesn't. This library shouldn't wait for upstream changes, but instead represent the status quo. The current behaviour has been established for multiple years at this point.

**Comment by niemeyer** [comment]
Yes, that's exactly why things work the way they do today, so we can remain compatible with old juju. Can you point me to some actual code or documentation that disagrees with that?
