### ISSUE TITLE
Add Relation.broken to allow querying if a relation is broken (breaking)

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#940]
It's sometimes good to be able to query for relations and then determine if the relation you're looking at is broken (due to the current event being a relation-broken event for the relation in question, or while handling deferred events before that event). So it would be good to add a `Relation.broken` boolean attribute (or perhaps its inverse, `Relation.active`?) that ops sets based on the relation data and incoming event.

This is to solve the issue I've been discussing with @carlcsaposs-canonical with the mysql-router-k8s charm using a ["stateless status setting" approach](https://github.com/canonical/mysql-router-k8s-operator/commit/608c094273afdb7adb8ad3e9ef975ca4f8af4865), but having to pass the current event down to all their get-status functions. It'd be conceptually simpler (and perhaps better in the case of deferred events?) to just be able to query `relation.broken`.

So this should probably be done as part of or shortly after the multi-status work (spec OP033).

**Comment by sed-i** [comment]
Would it make sense for ops (or juju?) to partition relation data to "relation data" and "departing relation data"?
This way charm code wouldn't need to communicate deltas when operating on relation data as a whole.

Related: https://github.com/canonical/operator/issues/888

**Comment by benhoyt** [comment]
@ca-scribner and I were discussing this on Mattermost, and agree that the "positive" is probably the way to go, i.e., `Relation.active` rather than `Relation.broken`.

**Comment by sed-i** [comment]
> It'd be conceptually simpler (and perhaps better in the case of deferred events?) to just be able to query `relation.broken`.

I don't think I've encountered yet a use case where a broken relation is useful to have around when iterating over them.
Since [juju/2024583](https://bugs.launchpad.net/juju/+bug/2024583) was downgraded to "Wishlist", perhaps ops could simply hide it away from us?

From an API standpoint, instead of adding **everywhere** the active conditional:
```python
relations = [relation for relation in self.charm.model.relations["whatever"] if relation.active]
```
I'd much rather have the opposite:
```python
for relation in self.charm.model.broken_relations[self.name]:
```
or move it out into the event class:
```
for relation is event.broken_relations:
```

Technically this would be a breaking change, but I think "only active" is what everyone actually expect.

**Comment by benhoyt** [comment]
That's a reasonable idea, @sed-i, thanks. I intend to discuss this with John M a couple of others next week, to see if we can finalize which approach we take.

**Comment by ca-scribner** [comment]
@sed-i I'm with you that I (and I think, most people) would have expected `model.relations["my-relation"]` during a `relation-broken` event to exclude the application that is currently breaking.  I wonder if there's a safe way to implement that now, however.  Anyone who relies on the opposite could get burnt.

It would be nice to avoid having to do `[relation for relation in self.model.relations["my-relation"] if relation.active]` every time I wanted to loop through relations though.  Maybe we're stuck adding a getter like `relations.get_active()`?

**Comment by benhoyt** [comment]
I discussed this with @jameinel today, and we lean towards excluding the broken relation from `model.relations["foo"]` during `relation-broken` (but not from prior `relation-departed` events). This makes more sense, and is what charmers expect.

In terms of backwards-compatibility and whether this would be a safe change to make, I've done a cursory look through a bunch of charms I have downloaded, and where they iterate over `model.relations` it looks like it's in contexts where the broken relation shouldn't be included anyway. So I think it probably would be safe to do this.

One tricky thing is what `model.get_relation()` would return, and what the `.relation` attribute of the `RelationBrokenEvent` should be in the `relation-broken` hook. If we just made the change to `model.relations` to exclude the broken relation, `get_relation()` would also return None and the `RelationBrokenEvent.relation` would be None. (This would happen as it's no longer in `model.relations["foo"]`, and `get_relation` uses that via `RelationMapping._get_unique`.) I'm not sure that's a good idea.

Ideally we'd make the change to Juju's `relation-list` hook tool. However, ops would still have to exclude it manually for older versions of Juju.

As next steps, @wallyworld said he'd bring this up at the next charm guild meeting next week to try to discuss the Juju aspects of this then.

**Comment by sed-i** [comment]
> we only want to clean up the user when the relation breaks, not when a unit departs

Deltas vs. holistic :)

Would it work for you to compare & cleanup expected users and existing users?

**Comment by sed-i** [comment]
Not sure I follow. If the current composition of relation data gives you the model-backed existing users, then could you query the database itself and delete all the users that are in the database but not in reldata?

**Comment by sed-i** [comment]
Ah I see.
In that case seems like you're already affected by https://bugs.launchpad.net/juju/+bug/1960934.
We sometimes use a peer relation for in place of stored state. Might be awkward for your case though.

**Comment by benhoyt** [comment]
FYI we going to be discussing Juju's handling of relation-broken (including this issue) at a session during the mid-cycle virtual roadmap sprint later this month.

**Comment by benhoyt** [comment]
Per [notes](https://docs.google.com/document/d/1TOvhoB8_bvfxIlHe8O80AyzSz0x2O6zG0AcYoOhxKaQ/edit#heading=h.6vay0gz4vbq4) from a meeting about this at the virtual product sprint, we're planning not to remove the broken relation ID from the `relation-ids` list in Juju (which would reflect in ops). Still undecided whether to add `Relation.broken` or `Relation.active` though, as you could still access the `event.relation` instance or get `Relation` instance by specific ID.
