### ISSUE TITLE
ResourceMeta requires "filename" but that's optional

### ISSUE THREAD

**Issue by timClicks** [canonical/operator#95]
We currently require a `filename` key for resources, but that isn't actually a requirement. 

https://github.com/canonical/operator/blob/af37ba04af8d1545994bfe654078463283722f79/ops/charm.py#L226-L232

Many k8s charms omit them:

https://github.com/wallyworld/caas/blob/84018271459aaa124b10f824b36159aecc7f1cad/charms/mysql/metadata.yaml#L19-L21

**Comment by niemeyer** [comment]
@johnsca Can you please look into that?

**Comment by johnsca** [comment]
This was fixed in #93
