### ISSUE TITLE
Support unified charmcraft.yaml

### ISSUE THREAD

**Issue by syu-w** [canonical/operator#969]
Hi,

`charmcraft` is now moving to use unified `charmcraft.yaml` for all `metadata.yaml`, `actions.yaml`, and `config.yaml` as specs in ST087. While the old style is still supported and we doing backward compatibility for now, the unit tests for the charms are not happy because it try to read `metadata.yaml` but did not found the metadata it needs.

So this might be a good time for ops to first try to read `charmcraft.yaml` to get `metadata`.

An example of the new unified `charmcraft.yaml`
https://github.com/canonical/charmcraft/blob/main/tests/test_metafiles.py#L29

**Comment by benhoyt** [comment]
Thanks for the note @syu-w. If you or one of your team is able to help with a PR here, that would speed things up. Otherwise I'll try to get to this before the next release of ops (likely early August).

**Comment by syu-w** [comment]
@benhoyt I am going to see if I can create a PR next week.

**Comment by benhoyt** [comment]
I'm reviewing #977 now, but just wondering about the spec for this. [ST087](https://docs.google.com/document/d/1IctKhAv2H_HUk96g0p2QGx_CAYVLGIQH_CWydLIkzFE/edit) doesn't seem to mention `actions.yaml` and `config.yaml` at all. It looks like the things in `actions.yaml` are included under an `actions` key in `charmcraft.yaml`, and the `options` from `config.yaml` are included directly. Is that correct? Is there a spec / doc for that somewhere?

**Comment by jnsgruk** [comment]
@benhoyt the intention is this:

- You can still include a `metadata.yaml`, but fields that appear in both `charmcraft.yaml` and `metadata.yaml` will cause a build error
- You can still include a `config.yaml` seperately, **or** you can add `options:` in the charmcraft.yaml. This allows for splitting things out in charms with a lot of config options
- You can still include `actions.yaml` **or** you can add `actions:` to your `charmcraft.yaml`

**Comment by benhoyt** [comment]
Thanks for the PR, @syu-w -- merged!
