### ISSUE TITLE
Improve typing for RelationEvent.unit

### ISSUE THREAD

**Issue by yanksyoon** [canonical/operator#976]
Related to [discussion point](https://github.com/canonical/jenkins-k8s-operator/pull/11#discussion_r1264776509) on Jenkins-k8s PR, the `RelationEvent.unit` property is typed as `Unit | None`. 
Types such as `RelationJoinedEvent` can have the type narrowed down to `Unit` (without `None`) so that the user does not have to typecast the `unit` property.

**Comment by tonyandrewmeyer** [comment]
It looks like only the various relation events have any optional attributes, so they are the only ones that could have their type narrowed down in this way.

Documenting my reasoning (@benhoyt feel free to correct any of this, or just ignore it :smile:):

`main.main()` calls `main._emit_charm_event()` to emit the `BoundEvent`. `BoundEvent.emit()` instantiates the various event objects. `main._emit_charm_event()` gets the args/kwargs for the event from `main._get_event_args()`.

`main._get_event_args()` adds `unit` and `app` to the `kwargs` iff `JUJU_REMOTE_APP` or `JUJU_REMOTE_UNIT` (with a `/` for the app, which must be present if it has a value and the app envar does not), using `Model`'s `get_app` and `get_unit`.

`Model.get_app` and `Model.get_unit` both do `self._cache.get(T, app_name)`, where `_cache` is a `_ModelCache`. `_ModelCache.get(T, name)` can't return `None` - it will either return an existing object or create one and return it.

So it comes down to whether those two envvars are provided. It looks like this is something that Juju does (or does not do), so I'll try to figure that out.

**Comment by tonyandrewmeyer** [comment]
I think [this](https://github.com/juju/juju/blob/e8525c0bb14b765af125f5add89c8bce55393059/worker/uniter/runner/context/context.go#L1331) is saying that they will both be set to `remoteUnitName` and `remoteApplicationName`. Those are [documented here](https://github.com/juju/juju/blob/e8525c0bb14b765af125f5add89c8bce55393059/worker/uniter/runner/context/context.go#L236):

> remoteUnitName identifies the changing unit of the executing relation
> hook. It will be empty if the context is not running a relation hook,
> or if it is running a relation-broken hook.

> remoteApplicationName identifies the application name in response to
>relation-set --app.

**Comment by tonyandrewmeyer** [comment]
[Asked for clarification](https://chat.charmhub.io/charmhub/pl/xqfcmpbpapbfpdnmmt9hh7zuqr).

**Comment by tonyandrewmeyer** [comment]
I guess I could also stop looking at the code and just trigger some events and look at what they have :)

**Comment by tonyandrewmeyer** [comment]
I made a small charm that just logged the environment variables on the various relation events, and integrated it with postgresql-k8s. When I did the integration I got these events:

| event | JUJU_REMOTE_APP | JUJU_REMOTE_UNIT |
| ------------- | ------------- | ------------- |
| relation-created | postgresql-k8s | |
| relation-joined | postgresql-k8s | postgresql-k8s/0 |
| relation-changed | postgresql-k8s | postgresql-k8s/0 |
| relation-changed | postgresql-k8s/0 | |

(The two relation-changed events were identical in envvars other than `JUJU_REMOTE_UNIT` and `JUJU_CONTEXT_ID`).

When I removed the integration, I got these events:

| event | JUJU_REMOTE_APP | JUJU_REMOTE_UNIT |
| ------------- | ------------- | ------------- |
| relation-departed | postgresql-k8s | postgresql-k8s |
| relation-broken | postgresql-k8s | |

**Comment by tonyandrewmeyer** [comment]
So I believe the situation is, based on that, plus the code, plus the info from Mattermost:

* `JUJU_REMOTE_APP` is always provided for all relation hooks, as the comment suggests.
* `JUJU_REMOTE_UNIT` *might* be provided with relation-changed, *will not* be provided with the application level events (relation-created, relation-broken), and *will* be provided with the unit level events (relation-joined, relation-departed)

I'll adjust based on this conclusion.

**Comment by tonyandrewmeyer** [comment]
Hmm, [apparently `JUJU_REMOTE_APP` might not be set for relation-broken](https://bugs.launchpad.net/juju/+bug/1960934). Although in that bug John says he checked machine charms and they did, and my (cursory) test above was k8s and it also did. But that bug is still open, so it seems like we actually cannot rely on `JUJU_REMOTE_APP` being present for relation-broken at this time.

**Comment by benhoyt** [comment]
See also the similar issue https://github.com/canonical/operator/issues/1040 (opened today based on the extra asserts needed in a charm).
