### ISSUE TITLE
Unable to pin dependencies without modifying charm libs

### ISSUE THREAD

**Issue by kian99** [canonical/operator#985]
Hi,

Following on from #984, I was trying to pin my Ops version to 2.4.1 by adding `ops == 2.4.1` in my requirements.txt but my build fails with the following,

```python                                    
2023-08-02 10:52:09.737 :: 2023-08-02 08:52:08.652 :: Running external command ['/root/parts/charm/build/staging-venv/bin/pip3', 'install', '--upgrade', '--no-binary', ':all:', '--requirement=requirements.txt', 'ops>=2.0.0']                                                                                                           
2023-08-02 10:52:09.737 :: 2023-08-02 08:52:09.300 ::    :: ERROR: Double requirement given: ops==2.4.1 (from -r requirements.txt (line 1)) (already in ops>=2.0.0, name='ops')                                                          
```
This extra requirement for `ops>=2.0.0` seems to be coming from the `data_platform_libs` charm's `data_interface.py` library which specifies `PYDEPS = ["ops>=2.0.0"]`.

Is there a way to overcome this without modifying the data_interface.py file? After removing the pydeps line, I can successfully build the charm with the desired ops version.

**Comment by benhoyt** [comment]
This is actually a `charmcraft pack` issue. I wonder what version of `pip` is being used? It seems that newer versions of pip, as of 20.3, use the [new dependency resolver](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html) that can handle double requirements as long as there's not a conflict. See also https://github.com/pypa/pip/issues/2367. I'm using pip 22.0.2 locally, and this works fine:

```
$ cat req.txt 
ops==2.4.1
$ pip install --upgrade --no-binary :all: --requirement=req.txt ops>=2.0.0
$ # no error
```

Does the full `charmcraft pack` log show what version of pip is being used?

Charmcraft could probably work around this, though it looks like they also recently updated their dependency handling to install requirements.txt and libs PYDEPS in one command: https://github.com/canonical/charmcraft/pull/1157/files. Looks like they're reconsidering the Charmcraft dependency management more generally: https://github.com/canonical/charmcraft/issues/1140

I think the best think to do is figure out how to get Charmcraft to use a later version of pip. I'll ask on the thread there what they suggest.
