### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/operator#990]
Since `2.5.0` and (I think) specially after #960

In [Loki unit test we are getting](https://github.com/canonical/loki-k8s-operator/actions/runs/5867832804/job/15909377429?pr=299#step:5:402) ([PR-299](https://github.com/canonical/loki-k8s-operator/pull/299)):

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/runner/work/loki-k8s-operator/loki-k8s-operator/tests/unit/test_log_proxy_consumer.py", line 310, in test__fetch_promtail_from_attached_resource
    self.harness.charm.log_proxy._push_promtail_if_attached(binary_path)
  File "/home/runner/work/loki-k8s-operator/loki-k8s-operator/lib/charms/loki_k8s/v0/loki_push_api.py", line 2027, in _push_promtail_if_attached
    self._push_binary_to_workload(resource_path, workload_binary_path)
  File "/home/runner/work/loki-k8s-operator/loki-k8s-operator/lib/charms/loki_k8s/v0/loki_push_api.py", line 1995, in _push_binary_to_workload
    self._container.push(workload_binary_path, f, permissions=0o755, make_dirs=True)
  File "/home/runner/work/loki-k8s-operator/loki-k8s-operator/.tox/unit/lib/python3.8/site-packages/ops/model.py", line 2073, in push
    self._pebble.push(str(path), source, encoding=encoding,
  File "/home/runner/work/loki-k8s-operator/loki-k8s-operator/.tox/unit/lib/python3.8/site-packages/ops/testing.py", line 2596, in push
    shutil.copyfileobj(cast(IOBase, source), cast(IOBase, f))
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
TypeError: write() argument must be str, not bytes
```

The error is in [loki_push_api.py line 1995](https://github.com/canonical/loki-k8s-operator/blob/main/lib/charms/loki_k8s/v0/loki_push_api.py#L1995):

```python
self._container.push(workload_binary_path, f, permissions=0o755, make_dirs=True)
```
The [`.push()` method receive](https://ops.readthedocs.io/en/latest/index.html#ops.pebble.Client.push):

- path – Path of the file to write to on the remote system.
- source – Source of data to write. This is either a concrete str or bytes instance, or a readable file-like object.

Debugging the code, in that line I'm sending:

```python
(Pdb) workload_binary_path
'/tmp/promtail-linux-amd64'
(Pdb) f                   
<_io.BufferedReader name='/tmp/tmp-ops-test-resource-26vkn2p2/promtail-bin/promtail-linux-amd64'>
(Pdb) f.name              
'/tmp/tmp-ops-test-resource-26vkn2p2/promtail-bin/promtail-linux-amd64'
```

**Comment by benhoyt** [comment]
Thanks @Abuelodelanada for the report. I've confirmed this is a bug in the new testing filesystem implementation: we're supposed to ignore the default `encoding` of "utf-8" in the case of pushing a binary file, but we're not right now. Fix proposed at https://github.com/canonical/operator/pull/991

In the meantime, you can work around by explicitly saying `encoding=None` in your charm's push call in `_push_binary_to_workload`. This bugfix will be included in 1.6.0 coming out at the end of August, or I can release a 1.5.1 if you're desperate -- let me know. :-)

**Comment by Abuelodelanada** [comment]
Thanks for your quick answer @benhoyt!

I'll work around this and release a new version of the lib tomorrow morning (my morning ;-P).

The only problem I see is that the issue is reflected on the consumer side of the library: [`LogProxyConsumer`](https://github.com/canonical/loki-k8s-operator/blob/main/lib/charms/loki_k8s/v0/loki_push_api.py#L19) so someone can pack again their charm without updating the lib (`charmcraft fetch-lib`) and it will break since `charmcraft pack` may grab ops 2.5.0.

If you can release 2.5.1 will be awesome, so we cover everything.
(The first round of beers in Riga is on me ;-) )

**Comment by benhoyt** [comment]
Sounds good -- I'll release 2.5.1 first thing tomorrow.

**Comment by benhoyt** [comment]
@Abuelodelanada At your service: [2.5.1 released](https://github.com/canonical/operator/releases/tag/2.5.1) and shipped to PyPI.

**Comment by benhoyt** [comment]
Oops, and yes, I meant 2.6.0 and 2.5.1 in my earlier comment -- fixed.

**Comment by Abuelodelanada** [comment]
Thank you very much @benhoyt !!!
