### ISSUE TITLE
Simplify adding relation units and data in test harness

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#992]
When using `testing.Harness`, it's *very* common to see these two or three calls in a row: add relation, (often) add relation unit, and (often) update relation data. It [came up recently](https://github.com/tim-hm/ratings/blob/38e379881e998c97932ee4260e70ec0a7deedf1c/operator/tests/unit/test_charm.py#L34C1-L36) in a simple charm @jnsgruk was writing, and there are many more examples. Here are just a few from a quick grep of the charms I have checked out locally:

```python
# alertmanager-k8s-operator/tests/unit/test_charm.py
self.relation_id = self.harness.add_relation("alerting", "otherapp")
self.harness.add_relation_unit(self.relation_id, "otherapp/0")

# grafana-k8s-operator/tests/unit/test_auth_proxy_provider.py (slightly modified)
relation_id = self.harness.add_relation("grafana-auth", "requirer")
urls = {"urls": json.dumps(EXAMPLE_URLS)}
self.harness.update_relation_data(relation_id, "requirer", urls)

# prometheus-k8s-operator/tests/unit/test_endpoint_aggregator.py
alert_rules_rel_id = self.harness.add_relation(ALERT_RULES_RELATION, "rules-app")
self.harness.add_relation_unit(alert_rules_rel_id, "rules-app/0")
self.harness.update_relation_data(
    alert_rules_rel_id, "rules-app/0", {"groups": ALERT_RULE_1}
)
```

Even our API reference docs have examples with this pattern in it, for example the [`begin_with_initial_hooks` docstring](https://ops.readthedocs.io/en/latest/#ops.testing.Harness.begin_with_initial_hooks).

This is a bit annoying and certainly verbose for authors of charm unit tests.

I propose we add a simplified API that rolls these two or three calls into one. This is somewhat similar to how in Python 3.5 they added [`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run) to simplify a number of common patterns and reduce verbosity.

There are various ways we could approach this, but I think the simplest and most discoverable would be to augment `add_relation` with two new optional keyword arguments: `unit` and `data`. If you specified a `unit`, it would call `add_relation_unit` after adding the relation, and if you specified `data` it would also call `update_relation_data`. The new signature of `add_relation` and the (trivial) implementation would be:

```python
def add_relation(self, relation_name: str, remote_app: str,
                 unit: Optional[str] = None,
                 data: Optional[Mapping[str, str]] = None) -> int:
    # ... existing add_relation implementation ...
    if unit is not None:
        self.add_relation_unit(relation_id, unit)
    if data is not None:
        self.update_relation_data(relation_id, unit or remote_app, data)
    return relation_id
```

The charm test examples from the top would be simplified to:

```python
# alertmanager-k8s-operator/tests/unit/test_charm.py
self.relation_id = self.harness.add_relation("alerting", "otherapp", unit="otherapp/0")

# grafana-k8s-operator/tests/unit/test_auth_proxy_provider.py
urls = {"urls": json.dumps(EXAMPLE_URLS)}
self.harness.add_relation("grafana-auth", "requirer", data=urls)

# prometheus-k8s-operator/tests/unit/test_endpoint_aggregator.py
self.harness.add_relation(ALERT_RULES_RELATION, "rules-app", unit="rules-app/0",
                          data={"groups": ALERT_RULE_1})
```

**Comment by paulomach** [comment]
Yes please

**Comment by jnsgruk** [comment]
I wonder about the necessity of making the `unit` argument so explicit - perhaps it would make more sense to have the `unit` argument implied, but only if `data` is also supplied?

So for example:

```
self.harness.add_relation("grafana-auth", "requirer", data={"foo": "bar"})
```

Is actually equivalent to:

```
self.harness.add_relation("grafana-auth", "requirer", data={"foo": "bar"}, unit="requirer/0")
```

Unless the author decides to override the `unit` arg themselves?

**Comment by benhoyt** [comment]
@jnsgruk Those two are actually different: the first is adding relation data to the *application* data bag, the second (with the `unit`) parameter is adding to the *unit* data bag. So the `unit` parameter in my proposal both sets the unit name and selects to set unit data rather the app data.

@jameinel and I were discussing this this morning. He's not opposed to this, but noted previous discussion, which I'll try to summarize here: adding a `data` argument to `Harness.add_relation` has been considered before, but was seen as "yet another way of doing things", and keeping them separate allows fine-grained control over when the various events are fired (eg: `relation_joined` is fired when you call `add_relation_unit`). Read a bit more in [this comment](https://github.com/canonical/operator/issues/794#issuecomment-1177336832).

Just because it's been considered before doesn't mean it's out. As I've shown above, we're making the very common patterns (used in almost all Harness tests) difficult for people, which pushes them to 1) be annoyed with Harness, 2) create their own helper functions, or 3) use other tools like ops-scenario. There's nothing wrong with using other tools if they're better! But we also want to make the official tools something people like to use!

John also noted that it's possible in the Juju model to have application data without a unit, but not normal: it only occurs if you add a relation and unit(s) and application data, and then scale down to zero units. But in charm tests we often ignore the fact that's it's not typical and just take a shortcut: call `add_relation` followed directly by `update_relation_data` (with no `add_relation_unit`).

We could also consider a slightly more explicit API that would always call `add_relation_unit` to fire `relation_joined`, which is more how a real Juju model works. For example:

```python
# if app_data provided, call add_relation, generate a unit name and call add_relation_unit,
#    and call update_relation_data to set app data
# if unit_data provided, call add_relation, generate a unit name and call add_relation_unit,
#    and call update_relation_data to set unit data
# it would be an error to provide both app_data and unit_data
def add_relation(self, relation_name: str, remote_app: str, *, app_data=None, unit_data=None) -> int:
    ...
```

**Comment by jnsgruk** [comment]
Oh I do like that last suggestions with `app_data` and `unit_data` both explicitly in the signature :)

**Comment by jnsgruk** [comment]
John and I discussed the above today -- indeed the proposed API looks good but we both agree that it doesn't necessarily need to  be an error to provide both unit and app data?

**Comment by jameinel** [comment]
I like where we ended up. As Jon noted, we can allow them to set both, because there isn't ambiguity. The only thing that I hesitate at all is that creating the unit is based on whether you supply app_data, but that is a compromise I can live with for backward compatibility. (if we just made (`add_relation(relation, app)` always create a unit it would break any test suite that was then calling add_unit with the same name, and probably some other ones that check how many units there are.)

**Comment by benhoyt** [comment]
> only thing that I hesitate at all is that creating the unit is based on whether you supply app_data

@jameinel Do you mean "whether you supply app_data or unit_data", as surely we should call `add_relation_unit` if they supply unit_data too?

So this is the updated proposal:

```python
    def add_relation(self, relation_name: str, remote_app: str, *,
                     app_data: Optional[Mapping[str, str]],
                     unit_data: Optional[Mapping[str, str]]) -> int:
        """Declare that there is a new relation between this app and `remote_app`.

        ... existing docstring ...

        If app_data or unit_data are provided, also add a new unit to the
        relation and trigger ``relation_joined``. Then update the application
        data if ``app_data`` is set and unit data if ``unit_data`` is set, triggering
        ``relation_changed`` after each update.
        """
        # ... existing add_relation implementation ...

        if app_data is not None or unit_data is not None:
            remote_unit = remote_app + '/0'  # or possibly a small random number?
            self.add_relation_unit(relation_id, remote_unit)
            if app_data is not None:
                self.update_relation_data(relation_id, remote_app, app_data)
            if unit_data is not None:
                self.update_relation_data(relation_id, remote_unit, unit_data)

        return relation_id
```

Any further comments?
