### ISSUE TITLE
`cgi` module deprecated in Python 3.11

### ISSUE THREAD

**Issue by NucciTheBoss** [canonical/operator#995]
The `cgi` module in used in pebble.py is deprecated as of Python version 3.11 and is slated for removal in Python version 3.13. For example, when running charm unit tests through Python 3.11, you will see the following warning message:

```
.tox/unit/lib/python3.11/site-packages/ops/pebble.py:21
  /home/nucci/Documents/projects/work/operator-libs-linux/.tox/unit/lib/python3.11/site-packages/ops/pebble.py:21: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

We luckily still have a bit before we absolutely must remove `cgi` from pebble.py, but we should likely make plans to remove it before 24.04 LTS so that charm others do not get bombarded with `DeprecationWarning` messages. _I'm assuming that 24.04 will have at least Python 3.11 or 3.12_. [PEP594](https://peps.python.org/pep-0594/#cgi) provides some example alternatives that we could use, but there does not seem to be a direct replacement unfortunately :disappointed:

**Comment by benhoyt** [comment]
Thanks for the report @NucciTheBoss. Fixed in https://github.com/canonical/operator/pull/996 -- feel free to review.
